### ISSUE TITLE
Unknown google gson problem

### ISSUE THREAD

**Issue by AhRoon** [montlikadani/TabList#1]
How do I fix this issues?
Config: https://pastebin.com/8u52wd9K
Log: https://pastebin.com/bShbnfiq

**Comment by montlikadani** [comment]
@AhRoon 
Please send all the plugins, Minecraft version you are using and the full log file.

**Comment by montlikadani** [comment]
@AhRoon 
Try updating to the latest version.

**Comment by montlikadani** [comment]
**Try updating to the latest version.**

**Comment by montlikadani** [comment]
This is not the plugin error. The plugin doesn't support the Google GSON. Try updating the Java to the latest version.
