### ISSUE TITLE
It does not show row 2 in the tablist when more than 15 players are online

### ISSUE THREAD

**Issue by montlikadani** [montlikadani/TabList#10]
This should be displayed but not: https://gyazo.com/283ce5748a70a7783869bb2f64d0b7ab

**Comment by montlikadani** [comment]
Same as [#c1](https://dev.bukkit.org/projects/animated-tab-tablist#c1)

**Comment by NEZNAMY** [comment]
This is completely client-sided and adds another row every 20 players up to a maximum of 4 rows with 80 visible players.

**Comment by montlikadani** [comment]
Yeah, I thought about that, but it doesn't work with the plugin because it somehow overwrites it.

**Comment by NEZNAMY** [comment]
There's no way a plugin can affect this in any form without adding fake players slots or anything.

**Comment by montlikadani** [comment]
Okay, thank you for your help! If there are 20 players on my server, maybe it will be visible.
