### ISSUE TITLE
Every time someone joins my console get spamed

### ISSUE THREAD

**Issue by SgtChrisCross** [montlikadani/TabList#100]
I'm using the newest version of both plugin and paper.
Warn only is spaming if a player joins the server and it stops after he leave.

```
[Do, 29. Aug 2019 22:00:21 MESZ WARN] Plugin TabList v4.5 generated an exception while executing task 66
[Do, 29. Aug 2019 22:00:21 MESZ WARN] Plugin TabList v4.5 generated an exception while executing task 14166
```

The 66 or 14166 is every time another number. If two people are online it spams another number. two at the same time.
The warning spamed my console 8.975 times.

**Comment by montlikadani** [comment]
Full console log please.

**Comment by SgtChrisCross** [comment]
![image](https://user-images.githubusercontent.com/53583350/64043919-e4aa1d00-cb65-11e9-8f18-b219f757d358.png)

**Comment by montlikadani** [comment]
But the log file in the logs folder.

**Comment by SgtChrisCross** [comment]
[latest.log](https://github.com/montlikadani/TabList/files/3561123/latest.log)
sry mb ^^

**Comment by montlikadani** [comment]
More info about your server, such as server version software (Bukkit/Paper other)...

**Comment by montlikadani** [comment]
Send me your server version and the tablist config file.

**Comment by SgtChrisCross** [comment]
Paper version git-paper-175 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

![image](https://user-images.githubusercontent.com/53583350/64044543-59ca2200-cb67-11e9-97e4-119e66094c85.png)

[config.zip](https://github.com/montlikadani/TabList/files/3561159/config.zip)

**Comment by montlikadani** [comment]
uhm.. Well this error does not occur for me, join to my discord server (link on the main page) and install the dev version from #dev-releases tab. If this can't help, just write to #help room and I will fix it.

**Comment by SgtChrisCross** [comment]
Seems fine with the dev version.

**Comment by SgtChrisCross** [comment]
Update: The problem is back :S (changed nothing) i guess this happens with some problem with the groups?

```
[Fr, 30. Aug 2019 22:42:43 MESZ INFO] UUID of player Hookari is 888354a3-c397-4767-8e6d-8d575b909660
[Fr, 30. Aug 2019 22:42:45 MESZ INFO] Hookari[/109.192.140.125:65093] logged in with entity id 1369 at ([Hauptwelt]2057.299999974668, 66.0000002, 4047.299999974668)
[Fr, 30. Aug 2019 22:42:45 MESZ WARN] Plugin TabList v4.5 generated an exception while executing task 106
[Fr, 30. Aug 2019 22:42:45 MESZ INFO] + Hookari
[Fr, 30. Aug 2019 22:42:45 MESZ WARN] Permissions lag notice with (GenericVaultHandler). Response took 37,358015ms. Summary: Getting group for Hookari
[Fr, 30. Aug 2019 22:42:45 MESZ WARN] Plugin TabList v4.5 generated an exception while executing task 66
[Fr, 30. Aug 2019 22:42:45 MESZ WARN] Plugin TabList v4.5 generated an exception while executing task 106
```

**Comment by SgtChrisCross** [comment]
My friend joined the server and the warning started to spam but after I joined too the warnings stopped!?

**Comment by montlikadani** [comment]
Send the animcreator.yml file and reset the messages file.

**Comment by SgtChrisCross** [comment]
[animcreator.zip](https://github.com/montlikadani/TabList/files/3562390/animcreator.zip)

**Comment by montlikadani** [comment]
Are you using the groups in tablist?

**Comment by SgtChrisCross** [comment]
As first I wanted to use them, but they were a bit buggy and removed them. Since the dev version I don't even have the groups.yml in the folder.

![image](https://user-images.githubusercontent.com/53583350/64063498-10c0af00-cbf5-11e9-97ed-d38b28167fe0.png)

**Comment by SgtChrisCross** [comment]
The only permission node i'm using atm is 'tablist.*'

![image](https://user-images.githubusercontent.com/53583350/64063527-7f9e0800-cbf5-11e9-9de4-c044e0c21824.png)

**Comment by montlikadani** [comment]
> As first I wanted to use them, but they were a bit buggy and removed them. Since the dev version I don't even have the groups.yml in the folder.

Yes, because you disabled that option in config file and not reloaded the plugin.

> The only permission node i'm using atm is 'tablist.*'
This permission is not contains the group permissions, so manually needs to be specified due to bad working.

**Comment by SgtChrisCross** [comment]
Now, I turned 'change-prefix-suffix-in-tablist' to 'true' and put the permissions to the right groups in LuckyPerms. I restarted the server.

I got a "new" warn after a player left the server.

```
[14:09:15 WARN]: [TabList] Plugin TabList v4.5 generated an exception while executing task 94
java.lang.NullPointerException: null
        at pw.javadebug.battlepass.collections.PlayersColl.getPlayer(PlayersColl.java:36) ~[?:?]
        at pw.javadebug.battlepass.hooks.hooks.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:35) ~[?:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:40) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:234) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:374) ~[?:?]
        at hu.montlikadani.tablist.TabList.setPlaceholders(TabList.java:1060) ~[?:?]
        at hu.montlikadani.tablist.Variables.replaceVariables(Variables.java:100) ~[?:?]
        at hu.montlikadani.tablist.TabList.sendTab(TabList.java:847) ~[?:?]
        at hu.montlikadani.tablist.TabList.lambda$9(TabList.java:748) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-175]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-175]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

**Comment by montlikadani** [comment]
Well, this seems in my code only replaces the PlaceholderAPI placeholders and no other, so this error should the "BattlePass" plugin.

**Comment by SgtChrisCross** [comment]
Okay, I remove the BattlePass part in the tablist footer.

**Comment by montlikadani** [comment]
> Edit: After removing the BattlePass part this warn didn't appear again after leaving.

And this fixed the issue?

**Comment by SgtChrisCross** [comment]
For now, yes. If it appears again I let you know. (Oh and I have a few questions about the prefix/suffix settings, is it alright to ask you on discord?)
