### ISSUE TITLE
Citizens NPC in tablist

### ISSUE THREAD

**Issue by fmohican** [montlikadani/TabList#102]
### Describe your problem to what is
I have citizens (NPC), when player are near NPC, they tried to appear in tablist but hidden in a second. They should not appear in tablist, cuz they aren't players.

### Details
Plugin version: v4.6
Software (Spigot/Bukkit etc.. `/version`) version: git-Paper-186

### Console error
There are no errors
### Configuration file(s)
Isn't config-related bug.

### Screenshots (optional)
Screenshot won't help, but a video will.
https://youtu.be/4rPCEzCstKY

**Comment by montlikadani** [comment]
There is an option in Citizens which can be disable the NPC names appearing on tablist. I'm not adding this as a new function, because I'm already removed, because it does not works. Also report this to Citizens.

**Comment by fmohican** [comment]
Okay i will link this issues to citizens
