### ISSUE TITLE
Cannot use the command /tl fp add <playername>

### ISSUE THREAD

**Issue by JamesMCL44** [montlikadani/TabList#104]
### Describe your problem to what is
Cannot use the command /tl fp add <playername>

### Details
Plugin version: 
Software (Spigot/Bukkit etc.. `/version`) version:
Paper version git-Paper-163 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Console error
```
[https://pastebin.com/KUQ0wBuk]
```

**Comment by montlikadani** [comment]
Thanks for your report! This error is thrown, because the fakeplayers list is not found in the file. So create it like or just copy here:
```
fakeplayers:
```

**Comment by JamesMCL44** [comment]
the server created the file itself now
i still got this error below every time a player joins or leave:
https://pastebin.com/XAicj1GY

**Comment by JamesMCL44** [comment]
Plz kindly help

**Comment by montlikadani** [comment]
Join our discord server and download the dev release.

**Comment by montlikadani** [comment]
Fixed in the latest version.
