### ISSUE TITLE
hearth life is only working after the player takes damage

### ISSUE THREAD

**Issue by arboriginal** [montlikadani/TabList#105]
I've only tested for now on a solo dev server (so, I was the only player online), I've started the server, it display an empty space instead of hearth, I take damage and then my life is displayed in the tablist.

### Details
Plugin version: TabList v4.6
Software (Spigot/Bukkit etc.. `/version`) version: paperMC 192 (1.14)

**Comment by montlikadani** [comment]
Not possible to fix in the plugin. Also this depends from Mojang on how want to fix this.

**Comment by arboriginal** [comment]
I used several tablist plugins, this feature work fine in it, so it's not a Mojang!

**Comment by montlikadani** [comment]
Because you re-joined and works.

**Comment by arboriginal** [comment]
???

In the same conditions, all plugins work except yours...

**Comment by montlikadani** [comment]
Can i see which plugins? I want to test it.

**Comment by arboriginal** [comment]
for example Tab reborn (the one I'm using actually), I don't have names in mind of other plugins I've tested before using this one, but never have this bug with any of them.

**Comment by montlikadani** [comment]
Yes, because that plugin is using hard-coded packets, which adds ability to show the hearth instantly, and also gets the client packages,which overwrites that.
