### ISSUE TITLE
Not Works

### ISSUE THREAD

**Issue by OigonRouge** [montlikadani/TabList#109]
### Describe your problem to what is
Understand what the problem is with the plugin.

The plugin does not start, it puts me an error in the console and in games the tablist does not work

### Details
Plugin version: 4.8
Software (Spigot/Bukkit etc.. `/version`) version: Latest

### Console error
```
[07:15:38] [Server thread/INFO]: [TabList] Enabling TabList v4.8
[07:15:38] [Server thread/INFO]: [TabList] Hooked PlaceholderAPI version: 2.10.4
[07:15:38] [Server thread/WARN]: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
[07:15:38] [Server thread/WARN]:        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96)
[07:15:38] [Server thread/WARN]:        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:679)
[07:15:38] [Server thread/WARN]:        at hu.montlikadani.tablist.TabList.updateTab(TabList.java:540)
[07:15:38] [Server thread/WARN]:        at hu.montlikadani.tablist.TabList.onEnable(TabList.java:137)
[07:15:38] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[07:15:38] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[07:15:38] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[07:15:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[07:15:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[07:15:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.reload(CraftServer.java:810)
[07:15:38] [Server thread/WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:576)
[07:15:38] [Server thread/WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[07:15:38] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[07:15:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710)
[07:15:38] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:695)
[07:15:38] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433)
[07:15:38] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397)
[07:15:38] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971)
[07:15:38] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816)
[07:15:38] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[07:15:38] [Server thread/WARN]: [TabList] There was an error. Please report it here:
https://github.com/montlikadani/TabList/issues
```

### Configuration file(s)
Send the configuration file(s).
# PlaceholderAPI use for the plugin.
placeholderapi: true

# Hook plugins
hook:
  # Hooking to my RageMode plugin. (https://www.spigotmc.org/resources/69169/)
  # If true, will disable the tablist, groups and the tablist objects, while
  # running a game.
  RageMode: false

# Different playerlist in different world.
per-world-player-list: false

# Fake players that are on the tab.
enable-fake-players: false

# Ignoring vanished players in %online-players% placeholder.
# true - does not count the vanished players to placeholder.
# Requires Essentials or SuperVanish plugin!
ignore-vanished-players-in-online-players: false

# Hides player from tab when afk status.
# Requires Essentials plugin!
hide-player-from-tab-when-afk: false

# Placeholder formatting
placeholder-format:
  # When the player changes the afk status, changes the tablist name format.
  afk-status:
    enable: false

    # Should show the afk format in right or left side?
    # true - displays in right side
    # false - displays in left side
    show-in-right-or-left-side: true

    format-yes: "&7 [AFK]&r "
    format-no: ""

  time:
    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    time-zone: "GMT0"

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Used for %server-time% placeholder.
    time-format:
      format: "mm:HH"
    # Used for %date% placeholder.
    date-format:
      format: "dd/MM/yyyy"

  # Ping color format for %ping% placeholder.
  ping:
    enable: true

    # Use color coding "&" for color.
    good-ping:
      color: "&a"
      amount: 200
    medium-ping:
      color: "&6"
      amount: 500
    bad-ping: "&c"

  # TPS color format for %tps% placeholder.
  tps:
    enable: true

    # Use color coding "&" for color.
    good-tps:
      color: "&a"
      amount: 18.0
    medium-tps:
      color: "&6"
      amount: 16.0
    bad-tps: "&c"

# Custom variables with unlimited variables.
# Use: <something>: "&6Message..."
custom-variables:
  <name>: "&5&o%player_name%"
  <lines>: "&5&m======================"

# Enables to change prefix & suffix in player tablist.
# WARNING! Overwrites the tabname function.
change-prefix-suffix-in-tablist:
  enable: false

  # Refresh interval in seconds, if using animation then counts in ticks.
  # Set to 0 if you don't want to refresh the groups.
  # If 0 you will required to execute the /tl rl command, to reload the groups.
  refresh-interval: 30

  # Do you want to use animation in groups?
  # This creates a new task scheduler when this enabled.
  # If this true, then you need to change the refresh interval such as 4, because counting in ticks.
  # If this false, then back to seconds interval.
  enable-animation: false

  # Disable groups in the given worlds.
  disabled-worlds:
    # Use the list as white list or not?
    # If true - Using the white list option and all worlds should be given to the list
    # to show in the specified worlds.
    # If false (default) - Using the disabled list option and if a world is given in the list
    # the groups will be disabled in that world.
    use-as-whitelist: false
    list:
    #- myWorld

  # By enabling this, you will be able to specify the correct Vault group name in groups file
  # and if correct, then it will grant the group to player.
  use-vault-group-names: true

  # Hide player group in tablist when the player is vanished?
  # Required Essentials plugin!
  hide-group-when-player-vanished: false

  # Hide player group in tablist when the player is afk?
  # Required Essentials plugin!
  hide-group-when-player-afk: false

  # Use the essentials nickname instead of player original name?
  # true - Using this format: "prefix playerNickName suffix"
  # false - Using this format: "prefix playerOriginalName suffix"
  use-essentials-nickname: false

  # Use the player displayname instead of groups?
  # This supports the player "prefix playerName suffix" format like on chat.
  # If the player has no any format on chat then display the player name.
  use-displayname: false

  # Scoreboard changing types (if you experience some problems by changing group).
  # scoreboard - Maximum character is 16 (if use 1.13+ version max. 64) in prefix & suffix.
  # namer - Max. character is unlimited.
  changing-type: scoreboard

# Tablist objective types
# Shows your current health (with life indicator), shows your current ping or a custom placeholder
# that shows number.
tablist-object-type:
  enable: false

  # Types:
  # ping - ping of player
  # health - health of player
  # custom - custom value
  type: ping

  # Objective settings
  object-settings:
    # The ping side next to the player's name indicates the right side.
    ping:
      # Ping update time interval in seconds.
      update-interval: 3

      # Which worlds do not show up in ping (world names)?
      disabled-worlds:
      #- testingWorld

    # The player health (life) the player's name indicates the right side.
    health:
      # Which worlds do not show the players health in tab?
      disabled-worlds:
      - world_the_end

      # Blacklisted players who do not show the health in tab.
      blacklisted-players:
      - exampleplayer
      - players

    # It only accepts number-ending placeholders, such as player levels (doubled numbers "2.1" do NOT work).
    custom:
      custom-value: "%player_level%"

      # Refresh interval in seconds.
      refresh-interval: 3

      # Which worlds do not show the custom value setting (world names)?
      disabled-worlds:
      #- worlds

# Changing player tablist name with unlimited characters.
tabname:
  # Allow to change player tab name.
  enable: false

  # Use the Essentials nickname instead of tab name?
  use-essentials-nickname: false

  # How many letters should be allowed?
  max-name-length: 200

  # When the player left the server, delete the tab name?
  clear-player-tabname-on-quit: false

  # Enables color coding for tab names. ("&")
  # false - disables all placeholders, symbols, and color codes.
  enable-color-code: true

  # Enable the default color. (If the player has not written a color code, this color will be given by default.)
  default-color:
    enable: false
    color: "&6"

  # Which worlds can not be change the tab name?
  disabled-worlds:
  #- myworld

  # Which names can not be used?
  blacklist-names:
  - tabname

#=========================================#
#             Plugin Settings             #
#=========================================#
# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Plugin enable/disable messages in console.
# Use %newline% placeholder.
plugin-enable: '&6&l[&5&lTab&c&lList&6&l]&7&l >&a The plugin successfully enabled&6 v4.8&a!'
plugin-disable: '&6&l[&5&lTab&c&lList&6&l]&7&l >&c The plugin successfully disabled!'

# DO NOT CHANGE THIS!
config-version: 14
configuration file
```

### Screenshots (optional)
Send a few pictures about the problem if you can.

**Comment by montlikadani** [comment]
> [07:15:38] [Server thread/WARN]: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
> [07:15:38] [Server thread/WARN]:        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96)
> [07:15:38] [Server thread/WARN]:        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:679)

This is not tablist problem, report to Vault.

**Comment by OigonRouge** [comment]
@montlikadani How to add permissions plungin ? And Which one to take?

**Comment by montlikadani** [comment]
I think you should learn the Minecraft server usage, installation, before posting any unnecessarry errors. Also im suggest you to use https://www.spigotmc.org/resources/28140/

**Comment by OigonRouge** [comment]
This is the first time this has happened to me, TabList never did that to me
Thanks you !
