### ISSUE TITLE
My tab is flickering rapidly and doesnt respond to the config

### ISSUE THREAD

**Issue by hypewsG** [montlikadani/TabList#115]
I have installed the Bukkit version of the plugin onto a Paper-1.12.2 server. Upon joining, the tab is rapidly flickering between one version of a TabList to another. However, when I turn the "Tab update time interval" to "0", the tab no longer flickers. The tab that is no longer flickering, has no correlation to any of the configs and when I change the "tablist.yml" default Footer and Header, the tab does not update, even after a restart and/or "/tablist reload"

![1](https://user-images.githubusercontent.com/60300483/73126493-32a73d80-3fab-11ea-94fc-ff5d9f9c76dd.png)
![2](https://user-images.githubusercontent.com/60300483/73126494-32a73d80-3fab-11ea-829c-de8b08cbe276.png)

Video link : https://youtu.be/9wRoNEB2k5Q

**Comment by montlikadani** [comment]
- Make sure you not using any other tablist plugin.
- Make sure you are not using the bungee &/or the bukkit version in one server.

**Comment by hypewsG** [comment]
omg, i found the issue. one of the devs added a tab plugin with an odd name!
Thanks for the help anyway!
