### ISSUE TITLE
Header & footer not working

### ISSUE THREAD

**Issue by davidsun211** [montlikadani/TabList#116]
### Problem

Header & footer not working
### Details
Plugin version:
 5.1

Software version: 
Spigot 1.14.4

Relevant plugins: 
Scoreboard
### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

config.yml: https://pastebin.com/F2isGF4a

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/60566265/73605439-f83f3100-45a6-11ea-8cf5-30a9a9fb006f.png)

**Comment by davidsun211** [comment]
Now I noticed it ..

02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at 
sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.lang.reflect.Method.invoke(Method.java:491)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at hu.montlikadani.tablist.bukkit.ReflectionUtils.sendPacket(ReflectionUtils.java:96)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at hu.montlikadani.tablist.bukkit.TabTitle.sendTabTitle(TabTitle.java:30)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at hu.montlikadani.tablist.bukkit.TabHandler.sendTab(TabHandler.java:611)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at hu.montlikadani.tablist.bukkit.TabHandler.lambda$0(TabHandler.java:298)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.lang.Thread.run(Thread.java:748)
02.02 09:56:25 [Server] Craft Scheduler Thread - 8/WARN java.lang.IllegalAccessException: Class hu.montlikadani.tablist.bukkit.ReflectionUtils can not access a member of class com.andavin.images.v1_14_R1.PlayerConnectionProxy with modifiers "public"

**Comment by montlikadani** [comment]
Send the current plugins what you're using.

**Comment by davidsun211** [comment]
![image](https://user-images.githubusercontent.com/60566265/73606863-b4085c80-45b7-11ea-8233-0e8751f65d92.png)

**Comment by montlikadani** [comment]
Can you send me the link of the Images plugin?

**Comment by davidsun211** [comment]
https://www.spigotmc.org/resources/custom-images.53036/

**Comment by montlikadani** [comment]
If you remove the Images plugin will work again.

**Comment by davidsun211** [comment]
Wow thanks that works !!

**Comment by montlikadani** [comment]
If you still want to use the Images plugin, then you should report this error to the plugin developer, to fix overwriting the packets.

**Comment by davidsun211** [comment]
What should I send him?
Sorry I just don't really understand it ..
Thank you!

**Comment by montlikadani** [comment]
You can send to him this console error, and write this for reason (Copy): `We have problems with Images plugin, when other plugins are not able to send packets, because of Images plugin are preventing to send. (This error catch by TabList), the discussion about error in this site: https://github.com/montlikadani/TabList/issues/116`

```
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.lang.reflect.Method.invoke(Method.java:491)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at hu.montlikadani.tablist.bukkit.ReflectionUtils.sendPacket(ReflectionUtils.java:96)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at hu.montlikadani.tablist.bukkit.TabTitle.sendTabTitle(TabTitle.java:30)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at hu.montlikadani.tablist.bukkit.TabHandler.sendTab(TabHandler.java:611)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at hu.montlikadani.tablist.bukkit.TabHandler.lambda$0(TabHandler.java:298)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02.02 09:56:25 [Server] Craft Scheduler Thread - 0/WARN at java.lang.Thread.run(Thread.java:748)
02.02 09:56:25 [Server] Craft Scheduler Thread - 8/WARN java.lang.IllegalAccessException: Class hu.montlikadani.tablist.bukkit.ReflectionUtils can not access a member of class com.andavin.images.v1_14_R1.PlayerConnectionProxy with modifiers "public"
```

**Comment by davidsun211** [comment]
Thank you very much
