### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by TwistedGaming** [montlikadani/TabList#119]
24.02 20:59:00 [Server] WARN java.lang.NullPointerException
24.02 20:59:00 [Server] WARN at hu.montlikadani.tablist.bukkit.TabHandler.saveToggledTabs(TabHandler.java:771)
24.02 20:59:00 [Server] WARN at hu.montlikadani.tablist.bukkit.TabList.onDisable(TabList.java:160)
24.02 20:59:00 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
24.02 20:59:00 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373)
24.02 20:59:00 [Server] WARN at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453)
24.02 20:59:00 [Server] WARN at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:439)
24.02 20:59:00 [Server] WARN at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:432)
24.02 20:59:00 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:401)
24.02 20:59:00 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:733)
24.02 20:59:00 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:739)
24.02 20:59:00 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:966)
24.02 20:59:00 [Server] WARN at java.lang.Thread.run(Thread.java:748)
24.02 20:59:00 [Server] WARN [TabList] There was an error. Please report it here:

**Comment by montlikadani** [comment]
You removed the tablist.yml file, which is required to work. Also, update the configurations what you have currently. https://github.com/montlikadani/TabList/issues/118
