### ISSUE TITLE
Tablist permissions tested every second

### ISSUE THREAD

**Issue by SlimeDog** [montlikadani/TabList#12]
Spigot 1.12.2
TabList 2.4.2

```
  # Tab update time interval.
  # Set 0 to disable.
  interval: 4
```
Hopefully, this is in seconds, not ticks.
```
[09:52:21] [luckperms-verbose/INFO]: [LP] rambeau - tablist.staff - true
[09:52:21] [luckperms-verbose/INFO]: [LP] rambeau - tablist.default - true
```
Permissions are tested every second, apparently for every player connected. That seems a bit excessive. The permissions don't change frequently. Checking once on startup or plugin configuration reload or player connection should be sufficient.

**Comment by montlikadani** [comment]
@SlimeDog 
It is always checked because if there is a staff player on the server, you should immediately update the tablist of the number of staff on the server.

**Comment by SlimeDog** [comment]
So why not check on connect/disconnect? That is much less intrusive than every second.

**Comment by montlikadani** [comment]
I'm doing this.

**Comment by montlikadani** [comment]
I can not be this kind of lame, or anyway?

**Comment by montlikadani** [comment]
The two permission are in a place where they can not be anywhere else.

**Comment by SlimeDog** [comment]
I'm not following. You would read the permission on connect/disconnect (or wherever), set a variable, and check it as often as you like (in the place where they cannot be anywhere else).

**Comment by montlikadani** [comment]
@SlimeDog 
### Thank you for reporting it!

This issue has been resolved and updated. https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=220232
