### ISSUE TITLE
Multiverse-Core soft dependency

### ISSUE THREAD

**Issue by SlimeDog** [montlikadani/TabList#120]
Spigot 1.15.2
TabList 1.5

### Problem
TabList sometimes loads before Multiverse-Core on my servers. When that occurs, TabList header and footer are not presented in most worlds.

**/tablist reload** fixes the issue _in situ_, but making Multiverse-Core a soft dependency would solve it universally. Probably MultiWorld as well, for the same reason.

**Comment by montlikadani** [comment]
I haven't encountered such a problem since I've been using Multiverse-Core. The reason for this is that the plugin is not developed so the performance of the plugin is degraded. Anyway, this will be added as a soft-dependency.

**Comment by SlimeDog** [comment]
I had not encountered it before, and I've been using TabList (and MV) since forever. But the cause is clear, and it's random depending (no pun intended) how things fall in the enable cycle. Nevertheless, the cure is clear. Thanks.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/39c49842d73e31c6297b108bba38352511c37f32#diff-5df3d3f42757c737a95531b868d1d2b9

**Comment by SlimeDog** [comment]
Thanks.

**Comment by montlikadani** [comment]
Fixed in the latest version.
