### ISSUE TITLE
Sort Priority only respects the first character of argument

### ISSUE THREAD

**Issue by TheRealEmissions** [montlikadani/TabList#123]
### Details
Plugin version: Latest

Software version: Spigot 1.8.8

### Configuration file(s)

groups.yml: https://pastebin.com/Zzj8ywdi

### Screenshots (optional)

Default (sort priority 10) appears above all over ranks (sort priority 1-9):
https://cdn.discordapp.com/attachments/689928922787217536/690871118319452200/NzKfzGD77jAksnGdvAoCKP.png
https://cdn.discordapp.com/attachments/689928922787217536/690277996787269712/unknown.png

My best guess is that the "sort_priority" argument only listens to the first character:

`sort_priority: 10`
runs as
`sort_priority: 1`

**Comment by montlikadani** [comment]
Is this still happens in latest version?

**Comment by Nety01** [comment]
Doesn't seem to be an issue in v5.2.1. The first pink number is a sort priority.
![image](https://user-images.githubusercontent.com/42073765/78364299-8347a200-75bd-11ea-8e66-73a993ee48b1.png)
