### ISSUE TITLE
Tablist prefix not working.

### ISSUE THREAD

**Issue by WolfyGamingWorld** [montlikadani/TabList#124]
### Problem
Everytime I join or change worlds the prefix is disabled, happens for everyone on the server and fixes when reloading the plugin. The reload would be everytime we change the world though.
Second problem: Priority groups don't work, it's prioritised by join time. Who joins later is at the top.

### Details
Plugin version: Last version, 5.1

Software version: CatServer-1.12.2-abc4d59 

Relevant plugins: Multiverse

### Console error
```
No console error.
```

### Configuration file(s)

config.yml: https://pastebin.com/vUQtLNBD
groups.yml: https://pastebin.com/1teRsQ30

**Comment by montlikadani** [comment]
You have 30 seconds refresh interval in config. If you wait, then it will updates the groups.

**Comment by WolfyGamingWorld** [comment]
I have changed the interval, but only the Owner prefix works in Tab, like it's purple bold as it should be, but it's at the bottom, depending on who joins later, as I said.

**Comment by Nety01** [comment]
The group disappearing on changing world will be fixed in next release, or you can use a dev release from our discord. And the sort priority is still being worked on.

**Comment by montlikadani** [comment]
With these commit should fix: https://github.com/montlikadani/TabList/commit/9c1bc542796c4ac454d187f21a1b3f527cb49b50

**Comment by WolfyGamingWorld** [comment]
I don't know if this reopens it, but I downloaded the last version at it's still the same problem, I can see only my own rank set in groups.yml, and others can see their own rank color in tablist, but not others' ranks. Priority still isn't working either.

**Comment by montlikadani** [comment]
Can you send your configurations like config.yml, groups.yml in tablist and some screenshots in-game where the groups not works?

**Comment by WolfyGamingWorld** [comment]
config.yml: https://pastebin.com/dH4gneBv
groups.yml: https://pastebin.com/qdLPMDN8
tablist.yml: https://pastebin.com/gQj1Fn0C

Screenshots:
My PoV: https://imgur.com/nXmavYy
My friends' PoV: https://imgur.com/X7Tmj9T

**Comment by montlikadani** [comment]
Disabling scoreboard will work again.
