### ISSUE TITLE
Bug Prefix

### ISSUE THREAD

**Issue by DGabriel13** [montlikadani/TabList#127]
Problem
Well I think this error is kind of silly but only the players see their prefix

Details
Plugin version: v5.2.1

Software
git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2)

Console error
No error

Configuration file
Config.yml: https://pastebin.com/GfTRQdC8

Screenshots
![image](https://user-images.githubusercontent.com/58773688/78416585-41216d80-765c-11ea-877d-ba6e71a23a68.png)

![image](https://user-images.githubusercontent.com/58773688/78416586-4b436c00-765c-11ea-9e76-e4ca662c9fd1.png)

**Comment by montlikadani** [comment]
Are you using any scoreboard plugin?

**Comment by DGabriel13** [comment]
yes, I use FabledSkyBlock's ScoreBoard

Em sáb., 4 de abr. de 2020 às 13:45, montlikadani <notifications@github.com>
escreveu:

**Comment by montlikadani** [comment]
You should disable that, because it breaks the prefix/suffix on tablist.

**Comment by DGabriel13** [comment]
ok

**Comment by DGabriel13** [comment]
thank you helped a lot, more before I closed the problem, is it possible that it works with scoreboard?

**Comment by DGabriel13** [comment]
hmm let me do something that works :3
