### ISSUE TITLE
Will not stay AFK

### ISSUE THREAD

**Issue by realalecmartin** [montlikadani/TabList#128]
### Problem

When a player goes AFK, the configurated [AFK] Shows up next to the username, but it removes not only the players LuckPerks prefix, but in a few seconds, the [AFK] disappears. I would assume this is because of the tab refreshing? I'm not sure, but I have checked to see if the essentials AFK detector messes with this, and it is not that.

### Details
Plugin version: 
Latest Download

Software version: 
Spigot Latest Downaod

Relevant plugins: 
LuckPerms

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

config.yml: 

https://pastebin.com/PNwNLVsS

**Comment by montlikadani** [comment]
Maybe because you have other tablist prefix plugin that overwrites that events.

**Comment by realalecmartin** [comment]
I'm not exactly sure what you mean/ how to fix this.

Thank you for the quick response though!

**Comment by montlikadani** [comment]
Send here all plugins what you using in your server.

**Comment by realalecmartin** [comment]
InventoryRollback, LuckPerms, Dynmap, WorldEdit, Votifier, ColoredSigns, CoordinatesHUD, PlaceHolderAPI, BuycraftX, Vault, WorldGuard, CoreProtect, VotingPlugin, Essentials, EssentialsGeoIP, EssentialsChat, EssentialsAntiBuild, ChatEx, SimplePets, EssentialSpawn, EssentialsXMPP, TabList, EssentialsProtect

**Comment by montlikadani** [comment]
Do you have /nickname set in essentials?

**Comment by realalecmartin** [comment]
personally, I have a nickname for myself, but no one else on the server has a nickname.

**Comment by montlikadani** [comment]
Can you make a gif or video about that issue?
