### ISSUE TITLE
Prefix bug

### ISSUE THREAD

**Issue by goldbocman** [montlikadani/TabList#129]
Please help me.  Prefix of other players is not displayed! But my prefix is displayed. I use a lucky perms. Please help

**Comment by montlikadani** [comment]
Send here screenshots

**Comment by goldbocman** [comment]
> Send here screenshots

![IMG_20200418_090731](https://user-images.githubusercontent.com/63879449/79630741-371b6680-8154-11ea-9df3-336bff89200a.jpg)

**Comment by montlikadani** [comment]
- Did you use a scoreboard plugin?
- What version of tablist are you using (number)?

**Comment by goldbocman** [comment]
> * Did you use a scoreboard plugin?
> * What version of tablist are you using (number)?

1.yes, i did.
2. v.5.2.1

**Comment by montlikadani** [comment]
You can try to remove the scoreboard plugin, it breaks the tablist groups.

**Comment by goldbocman** [comment]
> You can try to remove the scoreboard plugin, it breaks the tablist groups.

Thanks, im try
