### ISSUE TITLE
tablist groups not working.

### ISSUE THREAD

**Issue by ShaneBolenback** [montlikadani/TabList#13]
Spigot: CraftBukkit version git-Spigot-c3093ef-aa25568 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
TabList: TabList version 2.4.2

I have the default config setup, I haven't changed anything.
I set a group in PEX called staff, I gave it permission -tablist.staff

The group [STAFF] does not show up in the tablist, like the picture below, which is from the TabList spigot page.
![0fd7a179d0686328eecc937c00d8a954d7dcc679](https://user-images.githubusercontent.com/20008482/38354410-5b793b00-386e-11e8-9d20-231949e614d0.gif)

**Comment by montlikadani** [comment]
Write something else wrong with the console?
Try without the negative (-) mark.

**Comment by montlikadani** [comment]
@ShaneBolenback 
### Thank you for reporting it!
I have fixed this bug at the moment, but I found another bug that may not be up to date.

**Comment by montlikadani** [comment]
@ShaneBolenback 
### Thank you for reporting it!

This issue has been resolved and updated. https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=220232
