### ISSUE TITLE
Prefixes do not work with/without luckperms

### ISSUE THREAD

**Issue by Seamonster778778778788** [montlikadani/TabList#130]
### Problem
I have followed the directions [here](https://github.com/montlikadani/TabList/wiki/How-to-show-LuckPerms-prefix-in-Tablist%3F) and my tablist isn't updating to show prefixes. My server has two prefixes for players, one for staff and one for a custom rank, and it isn't displaying either of them. If I do the command to set a prefix, it shows for a few seconds for me, then reverts; but no one else can see it. 

### Details
Plugin version:  5.2.1

Software version: Spigot

Relevant plugins: Luckperms, PAPI, vault

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

config.yml: https://pastebin.com/A1unUJxk

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/34897864/79670265-51bb0300-8187-11ea-924f-66678be3de0f.png)
I set this prefix as a test, and it stayed for a few seconds before going away. No one else could see it.

**Comment by montlikadani** [comment]
So one player have more luckperms groups than 1?

**Comment by Seamonster778778778788** [comment]
Yes.

**Comment by montlikadani** [comment]
You have to remove a group from that players. It breaks

**Comment by Seamonster778778778788** [comment]
Is there a way to 'select' the rank/tag with priority? So if I wanted to
use the tag with priority 0, it would use that one instead of tag with
priority 1, which is the game rank tag. This can be worked around though,
if I redesign my chat plugin to make priority work backwards with tags so I
can have them in the order I want, but I still can't use prefixes in the
first place for some reason

**Comment by montlikadani** [comment]
No. We query the groups from a list that goes by Vault. If a group name is the same as the player's group, it changes to the set Vault group.

**Comment by montlikadani** [comment]
Fixed in [this commit](https://github.com/montlikadani/TabList/commit/866e00c4b34c776a0664e4e57e000c422e121a8d)
