### ISSUE TITLE
Tamed animals have player prefix

### ISSUE THREAD

**Issue by Seamonster778778778788** [montlikadani/TabList#132]
### Problem

After updating Tablist, I got my previous issue solved and now there are ranks above our heads ingame. Im assuming this is where the bug comes in, because tamed animals now have the same prefix I do.
### Details
Plugin version: 5.3.1

Software version: 
spigot
Relevant plugins: 
mcmmo(adds wolf related features), citizens(might mess with AI? had that problem before)
### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

config.yml: 

https://pastebin.com/KEaXqyyQ
### Screenshots (optional)

https://cdn.discordapp.com/attachments/415204546261024768/703124887807459338/unknown.png

**Comment by montlikadani** [comment]
I'm crying about this Bukkit scoreboard handlers.

I'm sure about not changed anything in the code that relates to the nametags. Maybe checking in that plugins configuration, AI, holograms and so on if there is a setting that handles the nametags between player and tamed animals. (mcmmo, citizens)

**Comment by Seamonster778778778788** [comment]
I will in the morning, thank you for being so attentive to the GitHub too.
I updated those before updating Tablist and I didn't notice this issue
after Tablist was updated.

**Comment by Seamonster778778778788** [comment]
There is nothing in mcMMO config or citizens config about name tags, nametags, prefix, or anything else that would possibly give animals prefix's

**Comment by Seamonster778778778788** [comment]
is there a way to disable prefix's appearing over peoples heads, btw?

**Comment by montlikadani** [comment]
> 
> 
> is there a way to disable prefix's appearing over peoples heads, btw?

With Bukkit API is impossible.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/f4491ffa2b888bdaec8b76dff72c7c6e8acce53d
