### ISSUE TITLE
Random player showing above me in tab, despite groups showing it should be below me

### ISSUE THREAD

**Issue by Seamonster778778778788** [montlikadani/TabList#134]
### Problem

He is group default, I am group admin. Everyone else without a tag is showing up in the correct spot but not him
### Details
Plugin version: 5,3,1

Software version: 
luckperms
Relevant plugins: 

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

config.yml: https://pastebin.com/KEaXqyyQ
groups.yml: https://pastebin.com/gR5UzGZg

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/34897864/80242914-cc729b00-862b-11ea-8db3-d8fd82934660.png)

**Comment by montlikadani** [comment]
Did you using any scoreboard plugin?

**Comment by Seamonster778778778788** [comment]
No

**Comment by montlikadani** [comment]
Is that player have group what set in permission plugin?

**Comment by Seamonster778778778788** [comment]
default, same as everyone else without a rank

**Comment by montlikadani** [comment]
Is this still reproduce in the latest version (v5.4.0)?
