### ISSUE TITLE
Scoreboard don't show for other players

### ISSUE THREAD

**Issue by Jowany** [montlikadani/TabList#135]
### Problem
If you use placeholder %objective_score_<obj-name>% with any kind of scoreboard, players can see only their own score, other players can see with zero. 
I was using DeathCount, once It showed only for me (with operator) deaths from one player, until relog.  

### Details
Plugin version: 5.3.1

Software : 
Spigot and Paper

**Comment by Nety01** [comment]
Can confirm with v5.4.1. How to reproduce:
1) Perform /scoreboard objectives add Deaths deathCount
2) Set custom tablist objective to %objective_score_Deaths%
3) Use a scoreboard plugin
4) Kill one of the players
Only the player who has died can see his death count as 1, others players see 0 at him and all other players.
