### ISSUE TITLE
Players can't join after adding fake player with > 16 characters

### ISSUE THREAD

**Issue by Eboleh** [montlikadani/TabList#136]
### Problem
If you add fake player with /tablist fakeplayers add and the length of name is longer than 16 it kicks all players and don't allow to join with this error:
### Details
Plugin version: 
Spigot
tabList 5.3.1

### Screenshots
https://user-images.githubusercontent.com/64601581/80730414-38fd0680-8b12-11ea-8697-fda1512b3586.png

**Comment by montlikadani** [comment]
Where is the console error?

**Comment by Eboleh** [comment]
> Where is the console error?
there nothing in console:)

**Comment by montlikadani** [comment]
Console error?

**Comment by montlikadani** [comment]
What mc version are you using?

**Comment by Eboleh** [comment]
1.15.2

**Comment by montlikadani** [comment]
Fixed https://github.com/montlikadani/TabList/commit/ad083e09e2bad75f323822503933f895f4b9ec0c

In the next version you have to remove the fake player from the file and re-create it. Do this now with only with fewer characters.
