### ISSUE TITLE
Per-group TabList showing for all groups

### ISSUE THREAD

**Issue by CCreativeCND** [montlikadani/TabList#137]
### Problem

There are multiple groups, and the TabList for 1 group is showing for everyone (people not in the group)

### Details
Plugin version: 5.1

Software version: 1.15.2 (built with BuildTools)

Relevant plugins: EssentialsX, LuckPerms, Vault

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

[config.yml](https://pastebin.com/eZaXEaCU)
[tablist.yml](https://pastebin.com/4DYePsYN)

### Screenshots (optional)

When there is 1 player on the server, everything works fine, but when another player joins the TabList shows the wrong group's TabList

**Comment by montlikadani** [comment]
You should update the plugin to the latest version. This has already been fixed.
