### ISSUE TITLE
Groups priority not works

### ISSUE THREAD

**Issue by Eboleh** [montlikadani/TabList#138]
### Problem

/tl setpriority *player* *group* *priority* just changes players priority in tab, but in groups.yml string "sort-priority: #" changes right.
### Details
Plugin version: 
tablist 5.3.1
Software version: 
Spigot 1.15.2

### Configuration file(s)

groups.yml: https://pastebin.com/MWp8EEzD
config.yml: https://pastebin.com/xG12L2LW

**Comment by montlikadani** [comment]
Yes, because the sort-priority not works with `namer` changing-type. This will be fixed in the next release.

**Comment by montlikadani** [comment]
Check the new release.
