### ISSUE TITLE
Tab group always default

### ISSUE THREAD

**Issue by Eboleh** [montlikadani/TabList#140]
### Problem

Tab list can't see LuckPerms groups after update to TabList 3.4.0. That always uses default group.
### Details
Plugin version: 
TabList 5.4.0
Software version: 
Last https://github.com/Spottedleaf/Tuinity
Relevant plugins: 
LuckPerms 5.0.146
Vault 1.7.2 - b107

### Configuration file(s)

config.yml: https://pastebin.com/miiqGBVD
groups.yml: https://pastebin.com/A9HfZBfU

### Screenshots (optional)
![photo_2020-05-06_01-40-46](https://user-images.githubusercontent.com/64601581/81122969-b7a2db00-8f3a-11ea-9315-3002d2a72e8b.jpg)
![photo_2020-05-06_01-40-59](https://user-images.githubusercontent.com/64601581/81122974-b8d40800-8f3a-11ea-9c74-a8e8bb1f3390.jpg)

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/95ca65fe6e9febc2e889ba267f80a998623ff77d

**Comment by montlikadani** [comment]
Also, you have to handle your inheritances in the permission plugin. So disable the tablist.default permission in admin group.

**Comment by Eboleh** [comment]
ok, sorry, if it possible, can i get version of tablist with this fix now?
