### ISSUE TITLE
Bug with hide players from tablist

### ISSUE THREAD

**Issue by schapick1** [montlikadani/TabList#147]
when I turn on the hide players in tab function, players become invisible if you move away from them and return back.

version:1.12.2

**Comment by montlikadani** [comment]
TabList version?

**Comment by schapick1** [comment]
> TabList version?

last

**Comment by schapick1** [comment]
> TabList version?

https://youtu.be/TkuoZU07z_E

**Comment by montlikadani** [comment]
Is that a fake player (NPC) or a real player?

**Comment by schapick1** [comment]
> Is that a fake player (NPC) or a real player?

real player

**Comment by montlikadani** [comment]
What server software are you using? (Spigot/Paper etc..)

**Comment by schapick1** [comment]
> What server software are you using? (Spigot/Paper etc..)

Paper 1.12.2

**Comment by montlikadani** [comment]
Is this still reproduce in latest v5.4.2 version?
