### ISSUE TITLE
Reload not working

### ISSUE THREAD

**Issue by WonderCraft005** [montlikadani/TabList#148]
### Problem

When i want to reload the plugin, says: You do not have permission to use this command
When i type /perms, the chat shows, i have the tablist.* and the tablist.reload permissions...
Not works any of tablist commands
### Details
Plugin version: 
Latest
Software version: 
Spigot, Bungee
Relevant plugins: 

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

config.yml:

**Comment by montlikadani** [comment]
Using another permission plugin, like LuckPerms will fixes.
