### ISSUE TITLE
For whatever reason, this plugin specifically is causing my server to disable PvP.

### ISSUE THREAD

**Issue by Vulant** [montlikadani/TabList#152]
### Problem

I have made sure that my server.properties and the sponge world config has pvp enabled. I also use UniverseGuard2, and made sure all the config has pvp enabled. When I have Tablist on my server, suddenly PvP is disabled for all players. Using Luckperms verbose command, I am getting spammed with the tablist.owner true and tablist.default false permission over and over. I do not know why this, out of all plugins, is causing this issue. 
### Details
Plugin version: 
 "modid": "tablist",
        "name": "TabList",
        "version": "1.0.0",
        "description": "An ultimate animated tablist",
        "authors": "montlikadani"
Software version: 
Sponge
Relevant plugins: 
Plugins (21): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Block Monitor, CoinPurse, DupeFixer, LuckPerms, MaintenanceSponge, NanoChat, Negativity, Nucleus, PacketGate, ProjectCore, RentableRegions, ServerListPlus, SimplyPortals, Slash Discord, Spotlin, Total Economy, Universe Guard 2
### Console error
N/A

### Configuration file(s)

Sponge config: https://hastebin.com/inojegamib.pl 
Groups config: https://hastebin.com/arijusopap.pl
### Screenshots (optional)

N/A

**Comment by montlikadani** [comment]
Try to disable `tablist-groups` in spongeConfig
