### ISSUE TITLE
Not able to show LuckPerms prefixes

### ISSUE THREAD

**Issue by arnekick** [montlikadani/TabList#153]
### Problem

I am trying to use luckperms prefixes following this guide: https://github.com/montlikadani/TabList/wiki/How-to-show-LuckPerms-prefix-in-Tablist%3F
But i am unable to do step 1 and 2.
Step 1 because placeholderapi of spongeforge has no ecloud only a config for expansions.

Instead i used Luckholders https://ore.spongepowered.org/Nurdism/LuckHolders this is the placeholderapi extension for sponge.

Step 2 I do not have a config.yml but instead a spongeConfig.conf and in here i do not have the 2 options i need to set to true

### Details
Plugin version: 
Tablist 1.0.0

Software: Sponge 
Version: 7.1.10

Relevant plugins:
-LuckHolders 1.0.0
-LuckPerms 5.0.39 

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

spongeConfig.conf: https://pastebin.com/7xzbtrWj
animations.conf: https://pastebin.com/wbSW9jHR
groups.conf: https://pastebin.com/n9jzZBG1

**Comment by montlikadani** [comment]
Yes because Bukkit != Sponge

Also I described in the main site of this plugin, the placeholderapi is not supported because its too old and there is no any new release that fixes most of issues about that plugin. If it been updated I will implement that plugin as a dependency.

**Comment by arnekick** [comment]
Ok then for now ill have to use another plugin that does support luckperms ty for the info.
