### ISSUE TITLE
Tab Bug

### ISSUE THREAD

**Issue by Heriptik** [montlikadani/TabList#155]
### Details
Plugin version: 1.0.0

Software version: Sponge

Relevant plugins: 

### Console error
https://hastebin.com/enejuhanit.rb

### Configuration file(s)

config.yml: https://hastebin.com/yujufopeho.bash

### Screenshots (optional)

Video : https://drive.google.com/file/d/1TJ-OS7k3F0AIVnAgpPKF0BGxsLlqtqHP/view?usp=sharing

It may be the fact that I use the parent system in Luckperms :

/lp group groupexemple1 parent set groupexemple2
/lp group groupexemple2 parent set groupeexemple3

And this product a dysfunction in permission for tablist.

**Comment by montlikadani** [comment]
> Video : https://drive.google.com/file/d/1TJ-OS7k3F0AIVnAgpPKF0BGxsLlqtqHP/view?usp=sharing
> 
> It may be the fact that I use the parent system in Luckperms :
> 
> /lp group groupexemple1 parent set groupexemple2
> /lp group groupexemple2 parent set groupeexemple3
> 
> And this product a dysfunction in permission for tablist.

This should be reported in another ticket.
