### ISSUE TITLE
Spectator mode not allowing players through walls

### ISSUE THREAD

**Issue by iGds** [montlikadani/TabList#156]
### Problem

Spectator mode not allowing some players through walls, enabling spectator mode, disconnecting and reconnecting allows it to work, coming out of spectator and going back in stops it working again, issues stop if TabList is removed.
### Details
Plugin version: 5.4.3

Software version: Paper build 88

Relevant plugins: 

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

config.yml: https://hastebin.com/ubujuyefuw.coffeescript

**Comment by iGds** [comment]
just tried 5.4.4 same issue

**Comment by montlikadani** [comment]
Is there any video/gif about this?

**Comment by 3xpl0itz** [comment]
Hi,
I've been running into this same issue @montlikadani .
Here's some video evidence from my server (first link is with tablist installed, second is without):
https://drive.google.com/file/d/1R0jUpfOYCdVstURvUri1hOg9Nhb8XIlt/view?usp=sharing
https://drive.google.com/file/d/19uMumgG-BHDZ-fqVx5fqeLK3bmmIXA3x/view?usp=sharing
Thank you!

**Comment by bitrot-alpha** [comment]
```
Plugins (50): AntiDisconnectSpam, BetterSleeping3, BlockLocker, Bookshelves, Cannons, ChatControl, ChestShop, ChestSort, 
ClearLag, CommandAlias, CommandHook, CoreProtect, Essentials, EssentialsSpawn, Factions, floodgate-bukkit, Geyser-Spigot, 
GHolo, GriefPrevention, GSit, ItemJoin, LagMonitor, LuckPerms, MCJukebox, MiniMOTD, Multiverse-Core, Multiverse-
NetherPortals, Multiverse-Portals, PerWorldInventory, PlaceholderAPI, Plan, PlotSquared, PlugMan, Ships, SilkSpawners, 
SkinsRestorer, TabList, TheNewEconomy, TradeSystem, UberEnchant, uSkyBlock, Vault, ViaBackwards, ViaRewind, ViaVersion, 
VoidGenerator, WarpSystem, WorldBorder, WorldEdit, WorldGuard
```
```
This server is running Paper version git-Paper-191 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
```
```
[TabList Info]
Version: 5.4.6
```
Tried disabling around half of my plugins, Spectator would only work when disabling Tablist and then cycling from any gamemode to spectator.

**Comment by Ativ3k** [comment]
https://www.youtube.com/watch?v=kVEVqvva6tY

**Comment by montlikadani** [comment]
Is this still reproduce in v5.4.7 version?

**Comment by 3xpl0itz** [comment]
> Is this still reproduce in v5.4.7 version?

Seems to have fixed the issue for me on each of my servers! Thank you so much

**Comment by Mobmaker55** [comment]
Just to ask, what in TabList caused this?

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/658ddd207da4e9819410ac3d4186f362e8e27561#diff-bc3b7c184fd9ff450ec6fbbe617af124L74

**Comment by Wekendd** [comment]
I'm not sure if necroposting is frowned upon in GitHub, so apologies if I shouldn't be doing this, but I've been encountering this issue on 5.6.8: https://youtu.be/6gf1rZfQSwY.

I can't move through blocks as one should be able to in spectator mode. It doesn't seem to happen 100% of the time, but once in a while,

**Comment by montlikadani** [comment]
Consider creating a new issue instead
