### ISSUE TITLE
TownyAdvanced Prefix in TabList

### ISSUE THREAD

**Issue by SiphMC** [montlikadani/TabList#157]
Hello, I would like to know if we can actually put our towns and nations name in the tablist of this plugin. I went throught the config file and it seems not to be present. 

If not, is there any other tablist plugin that offer this possibility?

**Comment by TheNety** [comment]
Hey, yes this is possible. Firstly create groups (https://github.com/montlikadani/TabList/wiki/How-to-create-a-group), install PlaceholderAPI plugin and use any of these placeholders as the prefix - https://github.com/TownyAdvanced/Towny/wiki/Placeholders

**Comment by SiphMC** [comment]
I will look into it, I'll get back here in a few days and keep you updated about it :)

thanks for your time!
