### ISSUE TITLE
Plugin Not Reading Config

### ISSUE THREAD

**Issue by Glident** [montlikadani/TabList#16]
Hi!

I have this plugin installed on a 1.12.2 Spigot server and when I edit something in the config, it doesn't recognize it and it will always go back to the original configuration. What could be causing this?

**Comment by montlikadani** [comment]
What do you mean by returning to the original? Do you mean to set the default configuration when you edited the configuration and reload the plugin?

**Comment by Glident** [comment]
The config has no effect. Yea it just appears the same before you configure

**Comment by montlikadani** [comment]
Hmmm... Such a mistake has not occurred to me or anyone else. **Thank you for reporting it!**

**Comment by Glident** [comment]
What can i do to try to fix?

**Comment by montlikadani** [comment]
Lists the plugins that are on the server.

**Comment by Glident** [comment]
PlaceholderAPI, Vault, GroupManager, TabList, Essentials, EssentialsSpawn, EssentialsChat, and DeluxeMenus

**Comment by montlikadani** [comment]
What application is used to edit configurations? Notepad++?

**Comment by Glident** [comment]
No, I do it within my panel.

**Comment by montlikadani** [comment]
Which panel? Do you use MCServerSoft?

**Comment by montlikadani** [comment]
Do the same thing with the messages.yml file?

**Comment by Glident** [comment]
Yes

**Comment by Glident** [comment]
The panel I use is called Obsidian

**Comment by Glident** [comment]
OGP*

**Comment by montlikadani** [comment]
Do the same thing with the messages.yml file?

**Comment by Glident** [comment]
It reads the groups file, should I still check messages?

**Comment by montlikadani** [comment]
I say that when you edit the messages.yml file, will it restore it to the default?

**Comment by Glident** [comment]
One sec

**Comment by Glident** [comment]
It uses what I configured im messages.yml.

**Comment by montlikadani** [comment]
So restore it to the original?

**Comment by Glident** [comment]
So change it back?

**Comment by montlikadani** [comment]
Yes.

**Comment by Glident** [comment]
Ok done

**Comment by montlikadani** [comment]
I did not think that way. I thought **that if you edited the messages.yml file, it will restore its original state** like config.yml?

**Comment by Glident** [comment]
Nono the config doesnt restore, it stays the way that I configured it but it doesn’t effect tab. For some reason its only the config that does it.

**Comment by montlikadani** [comment]
Reload the plugin? **/tl reload**

**Comment by Glident** [comment]
Did that hundreds of times

**Comment by montlikadani** [comment]
Is OGP dealing with editing file configurations?

**Comment by Glident** [comment]
It is a control panel that allows you to edit files within the panel

**Comment by montlikadani** [comment]
Yes, but maybe that program is wrong. Because such a mistake did not occur to any user, neither to me nor to anyone.

**Comment by Glident** [comment]
It works with everything else. Should I try editing via FileZilla?

**Comment by Glident** [comment]
Still not working.
`#=================================OOO====================================#
#                     TabList Configuration File                         #
#=================================OOO====================================#
# config.yml file. Plugin version: 2.4.6                                 #
# Author, created by: montlikadani                                       #
#=================================OOO====================================#
# [Default configurations]                                               #
# https://github.com/montlikadani/TabList/blob/master/config.yml         #
#                                                                        #
# [Placeholders]                                                         #
# https://www.spigotmc.org/wiki/placeholderapi-placeholders/             #
#                                                                        #
# [Other placeholders]                                                   #
# https://github.com/montlikadani/TabList/wiki/Placeholders              #
#                                                                        #
# [Tips]                                                                 #
# - Use color coding '&' character, on this page:                        #
# http://minecraft.gamepedia.com/Formatting_codes                        #
# - In case of an error, write here:                                     #
# https://github.com/montlikadani/TabList/issues                         #
# - Use symbols in messages, on this page:                               #
# https://github.com/montlikadani/TabList/wiki/Symbols                   #
#=================================OOO====================================#

# If these number mark (#) are in the way, you can safely remove it.

#=========================================#
#                Settings                 #
#=========================================#
# PlaceholderAPI use for the plugin.
placeholderapi: true

# Different playerlist in different world.
per-world-player-list: false

# Remove the NPC name from the tab?
# ATTENTION! This is currently under repair and testing...
remove-npc-name-from-tab: false

# Time format.
# Formats/examples: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
time-format: 'yyyy.MM.dd - HH:mm:ss'

# Custom variables.
# Unlimited variables.
# Use: <something>: '&6Message...'
custom-variables:
  <website>: 'example.com'
  <name>: '&r%player_name%'
  <pluginauthor>: '&amontlikadani'
  <rightarrow>: '-->'

# Enables to change prefix & suffix in player tablist.
change-prefix-suffix-in-tablist: true

# Groups refresh interval. (In ticks!)
groups-refresh-interval: 200

# This indicates the ping for the player's name.
# WARNING! First, you must disable the "health-tab" because it merges and causes a bug.
ping-tab:
  enable: false
  # Ping update time interval.
  interval: 3
  # Which worlds do not show up in ping (world names)? If you do not want to disable any of them, use this: disabled-worlds: []
  disabled-worlds: []

# Player tab name.
tabname:
  # Allow change player tab name.
  # Warning if this is false, the command will not be registered either. Requires server restart!
  enable: false
  # How many letters should be allowed?
  max-name-length: 200
  # When the player left the server, delete the tab name?
  clear-player-tabname-on-quit: false
  # Enables color coding for tab names. ("&")
  enable-color-code: true
  # Enable the default color. (If the player has not written a color code, this color will be given by default.)
  default-color:
    enable: false
    color: '&6'
  # Which worlds can not change a tab name?
  # If you do not want to disable it, use it as follows: disabled-worlds: []
  disabled-worlds: []
  # Which names can not be used?
  # If all the words are used, set it as follows: blacklist-names: []
  # WARNING! Color codes are NOT considered.
  blacklist-names:
  - tabname
  enable-other-changed-name-message: false
  # Use %name%, %sender%, %newline%, %prefix% placeholder.
  # >> NO supported the PlaceholderAPI! <<
  other-changed-name-message: '&3Your name is changed to&r %name%&3 by&e %sender%&3.'

# Allow the tab to set the level of life (health)?
# WARNING! This only appears in the server after reconnecting.
# WARNING! First, you must disable the "ping-tab" because it merges and causes a bug.
health-tab:
  enable: false
  # Which worlds show your health in tab?
  # If you do not want to disable any of the worlds, then write it as follows: disabled-worlds: []
  disabled-worlds:
  - world_the_end

# Tablist. Header & footer with animation.
# Use 
, %staff-online%, %ip-address%, %level%, %xp%, %mc-version%, %motd%, %ping%, %servername%, %online+1%,
# %max-players%, %online-players%, %server-time%, %server-ram-free%, %server-ram-max%, %server-ram-used% placeholders.
# Use placeholders: https://www.spigotmc.org/wiki/placeholderapi-placeholders/
# Use symbols: https://github.com/montlikadani/TabList/wiki/Symbols
tablist:
  # Enable the tab? (Header, footer)
  enable: true
  # In what world do you use the tab?
  # If you do not want to disable any of the worlds, then write it as follows: disabled-worlds: []
  disabled-worlds:
  - lobby
  - hub
  # Tab update time interval.
  # Set 0 to disable.
  interval: 0
  header:
    - '&8&m-&7&m+&8&m---------------&7&m+&8&m-'
  footer:
    - '&8&m-&7&m+&8&m---------------&7&m+&8&m-'
#=========================================#
#             Plugin Settings             #
#=========================================#
# The TabList plugin is disabled (false) or enabled (true).
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Log plugin messages into console.
logconsole: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %newline%, %prefix% placeholder.
# >> NO supported the PlaceholderAPI! <<
plugin-enable-message: true
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v2.4.6&a!'
plugin-disable-message: true
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# The default is allowed to see the plugin information.
# Permission: tablist.plugininfo
default-can-see-plugin-information: false

# Unknown-command - If more than one word/letter you write to it.
# Example: /tl reload something...
# Use %command% placeholder.
# This feature is NOT enter into the unknown command Minecraft, it's just your own.
# >> NO supported the PlaceholderAPI! <<
unknown-command-enable: true
unknown-command: '%prefix%&c Unknown command.&7 Type "&f/%command% help&7" for help.'`
