### ISSUE TITLE
Placeholders for the sponge version

### ISSUE THREAD

**Issue by avescarelo** [montlikadani/TabList#162]
### Description
Hello, please add these placeholders for the sponge version.
1. Dimension + replace name of the word for view. 
(You now in the DIM-1 -> You now in the nether)

2. Balance

3. TPS

**Comment by montlikadani** [comment]
Note: I'll add PlaceholderAPI support for this plugin after PAPI being started updating. I'm not going to add variables one by one into this plugin from user requests. Some variables had been added, but not all the known.

**Comment by VOrlando520** [comment]
Don't bother waiting on PAPI to be updated. The previous dev dropped support and is no longer active. So either use what they offer or drop support for it entirely.

**Comment by montlikadani** [comment]
#227
