### ISSUE TITLE
Console spam once player joins

### ISSUE THREAD

**Issue by xNathanPVP** [montlikadani/TabList#163]
### Problem
Console spam once playerj oins

### Details
Plugin version: 1.16.1

### Console error
```
https://mcpaste.io/733dac0f7a91e608
```

### Configuration file(s)
https://pastebin.com/CmTpJ5uj

### Screenshots (optional)
none

**Comment by montlikadani** [comment]
Send here the startup log. Seems that the plugin is not loaded correctly.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/9edaad2576d55213cb41714a8f88d0d50c8eaf80
