### ISSUE TITLE
Cannot read player name in config.

### ISSUE THREAD

**Issue by Lorm1** [montlikadani/TabList#17]
Hello, I am trying to use %player_name%, as well as %name%, %sender% and everything I could find, but none of them work in displaying the player's display name in the TAB. Everything else is working perfectly fine though, excellent plugin and great job!

**Comment by montlikadani** [comment]
@Lorm1 
%player_name% placeholder requires the PlaceholderAPI: _/papi ecloud download Player_ PAPI download: https://www.spigotmc.org/resources/placeholderapi.6245/
%name% and %sender% placeholder do not exist on the tablist.

**Comment by Lorm1** [comment]
Alright, thank you

**Comment by Lorm1** [comment]
It worked, thank you! :D
