### ISSUE TITLE
Player head in tab rapidly flickers between the skin's head and either black or steve head

### ISSUE THREAD

**Issue by cryinf** [montlikadani/TabList#171]
The recent update 5.4.6 has made the head icon in the tab flicker rapidly. This only happens on this version, reverting to the previous version fixes this, but other aspects of the previous version are broken on 1.16.2.
Another issue with version 5.4.6: The EssentialsX Hex Colors used to work on the Tablist. In this version the colors default to black on tablist, but show correctly otherwise. Hex colors work fine when reverting to 5.4.5.

**Comment by montlikadani** [comment]
> Another issue with version 5.4.6: The EssentialsX Hex Colors used to work on the Tablist. In this version the colors default to black on tablist, but show correctly otherwise. Hex colors work fine when reverting to 5.4.5.

EssentialsX hex colors is not supported since hex codes its been added. The correct hex colors should be `#ffffff`
