### ISSUE TITLE
Premium Vanish support

### ISSUE THREAD

**Issue by JoshA20** [montlikadani/TabList#172]
### Problem
Online Staff does not decrease when entering vanish using Premium Vanish, works fine using normal essentials vanish - Doesnt with PV. (premium version of SuperVanish)

### Details
Plugin version: 
LATEST MAIN BRANCH (5.4.6)

Software version: 
https://i.josha20.com/JkZAnDsTc.png

Paper - # 137

Relevant plugins: 
https://i.josha20.com/gOcZFZc6l.png

### Console error
n/a

### Configuration file(s)

configuration file: 
https://pastebin.com/2jzYq2jA

### Screenshots (optional)
Nothing really much to show - my i.josha20.com/x.png links are screenshots, but past that there isnt really much that needs to be posted

**Comment by montlikadani** [comment]
PremiumVanish is not a supported with this plugin. But I see that there are APIs that can access to the methods. So will add it

**Comment by montlikadani** [comment]
You can download dev-build [here](https://github.com/montlikadani/TabList/actions/runs/236405306) if the build process is done.
