### ISSUE TITLE
SkinsRestorer & TabList incompatibility 

### ISSUE THREAD

**Issue by xknat** [montlikadani/TabList#176]
### Problem
external plugin incompatibility.

### Details
Plugin version: v5.4.6

paper: 1.16.2

Relevant plugins: Skinsrestorer

### Console error
*none*

### Configuration file(s)

configuration file: *default*

### Screenshots (optional)
Skinsrestorer skin refresher wont work with tablist.
is it using some sort of refresher?

**Comment by montlikadani** [comment]
wat? Describe it more clearly.

**Comment by xknat** [comment]
Skinsrestorer stops working if you install tablist.
How is that unclear?

**Comment by montlikadani** [comment]
> How is that unclear?

Without providing understandable and clearly issue description, how would I get that this is an issue? But nvm, I think you think the skin will change to alex/steve when the tablist plugin is installed and tablist-groups is enabled. This has already been fixed, https://github.com/montlikadani/TabList/actions/runs/241617268

**Comment by xknat** [comment]
K ill compile and test again.
Any eta on release?

**Comment by xknat** [comment]
It indeed seems to be working from current code.
Make sure to release the update so we don't have to tell em to look for alternatives.
