### ISSUE TITLE
TabList  error

### ISSUE THREAD

**Issue by KasprTv** [montlikadani/TabList#179]
### Problem
Players without nametag, console errors

### Details
Plugin version: latest BungeeCord

### Console error
```
17:43:53 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@394a2528, id=114, owner=hu.montlikadani.tablist.bungee.TabList@4248ed58, task=hu.montlikadani.tablist.bungee.tablist.TabManager$$Lambda$263/2071486151@7b141b75, delay=10, period=180, running=true) encountered an exception
java.util.ConcurrentModificationException
at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1558)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
at hu.montlikadani.tablist.bungee.tablist.TabManager.lambda$2(TabManager.java:84)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
17:43:53 [WARNING] Error dispatching event PostLoginEvent(player=Happy366) to listener hu.montlikadani.tablist.bungee.TabList@4248ed58
java.lang.NullPointerException
```

### Configuration file(s)
https://paste.helpch.at/powufexema.coffeescript

**Comment by montlikadani** [comment]
How many players trying to connect to your server in 1 second?

**Comment by KasprTv** [comment]
Around 3 in 1 second, why?

**Comment by montlikadani** [comment]
Try [this](https://github.com/montlikadani/TabList/actions/runs/252613068) build in Artifacts after the build process is done.

**Comment by KasprTv** [comment]
Nope dident work
https://paste.helpch.at/joyekabowa.rb
https://ctrlv.cz/Jrru

**Comment by montlikadani** [comment]
This is another issue. Now try [this](https://github.com/montlikadani/TabList/actions/runs/252644914) build again.

**Comment by KasprTv** [comment]
Now without error https://ctrlv.cz/uKj9

**Comment by montlikadani** [comment]
And whats the problem? The error fixed already...

**Comment by KasprTv** [comment]
That they dont have their nametag...?

**Comment by montlikadani** [comment]
This tablist plugin is not nameTag editor. This is only for tablist features.

**Comment by KasprTv** [comment]
I know but bcs of yours TabList they dont have the NameTag thats the Issue that I was reporting including the errors.

**Comment by KasprTv** [comment]
Will you look into it please?

**Comment by montlikadani** [comment]
No, because this plugin still not modifies/remove the nametags from NPCs/players.

**Comment by KasprTv** [comment]
It started after I added your plugin. Can you test it before you throw away this issue please?

**Comment by montlikadani** [comment]
I already tested and the nametags are not modified by this plugin and nametags plugins can overwrite it of how the user want. Btw, I don't see any of players on your sent screenshots, I just see some NPCs that have nametags set.

You can see that I have nametag
![kép](https://user-images.githubusercontent.com/30026208/93248095-a6db5f00-f78f-11ea-998a-beaed3ccdfbb.png)

**Comment by KasprTv** [comment]
Did you test it with multiple players. Bcs is not happening allways. Only sometimes. And with plugin NameTagEdit?

**Comment by KasprTv** [comment]
# Groups list
# NOTE: If the permissions do not work correctly then you should use
# a permission manager plugin such as LuckPerms.
groups:

That couldnt be the Issue?

**Comment by montlikadani** [comment]
Did you see the commit? It has been already fixed and released a new version.

**Comment by KasprTv** [comment]
![image](https://ctrlv.cz/shots/2020/10/05/D6bK.png)
Still

**Comment by montlikadani** [comment]
Still wat? I don't see any of issue. Just a player does not have prefix, set her a group.

**Comment by KasprTv** [comment]
Okey, nvm I delete the plugin probably. I writed like 3 times that this happening bcs of your plugin and you are not willing to fix it. You told me that your plugin doesent modify NameTags thats not true. I give you idea what could be wrong and you told me that it is already fixed in latest version. What it really means is that only the error and only sometimes players are white.

**Comment by montlikadani** [comment]
Tablist names != nametag

**Comment by KasprTv** [comment]
What tablist names does?
