### ISSUE TITLE
Regarding tab names...

### ISSUE THREAD

**Issue by Lorm1** [montlikadani/TabList#18]
I was wondering if there is a way to display the player's level before or after his name in the TAB menu, using the placeholders.

**Comment by montlikadani** [comment]
Hmm... It's possible... I'll see what I can do.

**Comment by Lorm1** [comment]
Awesome thank you, let me know!

**Comment by montlikadani** [comment]
Do you tell me what level to display the tab?

**Comment by Lorm1** [comment]
Essentially, something where I can display %player_level% or any placeholder before/after his name in the TAB... Which would look like this: <placeholder> name <placeholder>

**Comment by montlikadani** [comment]
I'll see what I can do. It may be a little longer for a long time, but if I can do it.
**Thank you for notifying me!**

**Comment by Lorm1** [comment]
All good, make sure to check out my new issue! Thanks for your time :D

**Comment by montlikadani** [comment]
This feature is added in this version: https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=236423
