### ISSUE TITLE
How do I set up a different tablist for a player?

### ISSUE THREAD

**Issue by HackerSte** [montlikadani/TabList#182]
Problem:
With this function I can only set the first and last line of the tablist for the "testuser" player

![image](https://user-images.githubusercontent.com/68558172/95125778-bc6ff300-0755-11eb-838a-3510eb176b28.png)

but I want to set more lines for the header, as you can do here:

![image](https://user-images.githubusercontent.com/68558172/95126087-2d170f80-0756-11eb-9b86-c3732ce7028e.png)

Using the same syntax the tablist doesn't work. I tried a few tries but I couldn't figure out how to go to a new line and start a new line. Is there a way to do this or is it a feature that hasn't been added?

Plugin version: The latest (5.4.8).

Software: Paper 
Version: 1.15.2

Relevant plugins: 
EssentialsX
Placeholder API
LuckyPerms

**Comment by montlikadani** [comment]
Insert the list here to see how you used.

**Comment by HackerSte** [comment]
I made other attempts and I realized that to go to the end you have to write /n, Thanks all the same for your time!
