### ISSUE TITLE
Tablist General Bug

### ISSUE THREAD

**Issue by Remco9900** [montlikadani/TabList#183]
The tablist bugs on top with the names. And also the TPS is red while its high. This occured after the newest update 

https://www.youtube.com/watch?v=ETkpM3oh7Yc&feature=youtu.be&ab_channel=alco2723

**Comment by TheNety** [comment]
TabList version? Server version? Don't delete the bug report template, it's there for a reason. The tps colour can be configured in config.yml.

**Comment by Remco9900** [comment]
Sorry should've put it in there alreay...

Plugin version is newest (TabList-v5.4.8.jar)

Server version Spigot1.8,8

Im now using the Tablist-v5.4.7 which doesnt have the name bug.
I also noticed that it does players close to me, when alot players are close it cycles trough these players

**Comment by montlikadani** [comment]
You can download [here](https://github.com/montlikadani/TabList/actions/runs/297701954) the fix under Artifacts. Don't forget to login into your github account.
