### ISSUE TITLE
Spectator gray-color: true breaks spectator mode

### ISSUE THREAD

**Issue by OpalMoonstride** [montlikadani/TabList#184]
### Problem

If I set remove-gray-color-from-tab-in-spectator: true, I can no longer clip through blocks, and objects can be seen in my hand.

### Details
Plugin version: TabList version 5.4.8

Software version:  Paper version git-Paper-207 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

Relevant plugins: 
I'm using Essentials, not CMI. 
Also possible relevance: Multiverse-core, Multiverse-inventories, BentoBox, FAWE

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

configuration file: https://hastebin.com/iyoqaziruk.yaml

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/39387146/95643034-716a1e80-0a7a-11eb-80b1-212df226b7f6.png)
![image](https://user-images.githubusercontent.com/39387146/95643043-7cbd4a00-0a7a-11eb-97f5-d7ee6f750233.png)

**Comment by montlikadani** [comment]
Are you in vanish?

**Comment by OpalMoonstride** [comment]
No, I don't use vanish.

**Comment by montlikadani** [comment]
Do you have ProtocolLib?

**Comment by OpalMoonstride** [comment]
Yes, I need it to run ArtMap. 

ProtocolLib-4.5.1-dev

**Comment by montlikadani** [comment]
Seems that ProtocolLib only supports 1.16.2 (last dev commit), but we're on 1.16.3, so we have to wait for another build that supports 1.16.3. Literally this issue only occures when there are 2 or more players.

**Comment by OpalMoonstride** [comment]
Actually, since you mentioned protocollib I checked for new builds and tried the v4.6.0-SNAPSHOT for MC 1.16, and now spectator works, fine!

So, thanks :)
