### ISSUE TITLE
Ping showing 20k+ ping for all players AND PAPI support broken

### ISSUE THREAD

**Issue by okgabe** [montlikadani/TabList#189]
### Problem

Using the plugin's built-in %ping% placeholder results in an inaccurate ping that has around 20k added to the true ping value.
Using the PlaceholderAPI %player_ping% placeholder does not function properly, despite it being enabled and working with PAPI's parse command.

### Details
Plugin version: 5.4.9

Software version: Spigot 1.16.4-R0.1 Snapshot

Relevant plugins:  PlaceholderAPI 2.10.9

### Console error
```
N/A
```

### Configuration file(s)
https://hastebin.com/paqotogube.yaml
https://hastebin.com/okufiyuhik.yaml

### Screenshots (optional)
Trying %ping%: https://okgabe.com/i/lnbWNUXGMY.jpg - 20k+ ping
Trying %player_ping%: https://okgabe.com/i/bw8Lrejskj.jpg - not replacing valid PAPI placeholder
(Yes, I have installed the Player package in PAPI and reloaded it and tried it in a /papi parse command).

**Comment by TheNety** [comment]
Hello, it's because the config was changed a bit. In config.yml find ping section and replace formats with this:
```
    formats:
    - "&a%ping% <= 200"
    - "&6%ping% >= 200"
    - "&c%ping% > 500"
```
