### ISSUE TITLE
spam in console

### ISSUE THREAD

**Issue by PerchunPak** [montlikadani/TabList#191]
### Problem

spamming in console with errors

### Details
Plugin version: 5.4.9 (5.4.8 good work)

Software version: Paper 1.12.2 (build 1618)

### Console error
https://pastebin.com/q0gbksP3

### Configuration file(s)

configuration file: https://pastebin.com/VBwiHFfW

**Comment by montlikadani** [comment]
Use this fixed version under Artifacts: https://github.com/montlikadani/TabList/actions/runs/383435250

This issue already been fixed
