### ISSUE TITLE
Tablist keeps flashing rapidly.

### ISSUE THREAD

**Issue by Frowzy** [montlikadani/TabList#197]
### Problem
Whenever a player is holding down tab, the tablist flashes between the default vanilla tablist and the plugin's tablist.
It's very disruptive, and I have no clue what is triggering this, as I had just moved from 1.12 where this did not occur, but after performing a fresh install of all plugins and reconfiguring them, tablist just keeps flashing.

### Details
Plugin version: 5.5.0

Software version:  PaperMC 1.16.4 300

Relevant plugins: PlaceholderAPI, Tablist, EssentialsX

### Console error
```
Send the console error if you have it. No console error.
```

### Configuration file(s)

configuration file: 

config.yml - https://pastebin.com/z4iPFk1z
tablist.yml - https://pastebin.com/eC48FmYh
### Screenshots (optional)

frame 1 - https://imgur.com/a/oVOEzhq
frame 2 - https://imgur.com/a/EPy6l9A

**Comment by montlikadani** [comment]
Remove `permissions` from tablist.yml or deny `tablist.1` permission.

**Comment by Frowzy** [comment]
Ah, wonderful! that seemed to do the trick. Thank you!
