### ISSUE TITLE
Display Names

### ISSUE THREAD

**Issue by bjunited** [montlikadani/TabList#2]
Hello!

I am wondering why the names are displaying white in the tablist, and how I can have the ranks appear there?

Thank You
- Ben

**Comment by montlikadani** [comment]
@bjunited 
What do you mean by white? The nickname may not be set or there is no rank corresponding to the player.

**Required:**
- The version number of the TabList plugin (which you are currently using).
- The Minecraft version number.
- The Bukkit / Spigot version number.
- Send a TabList configuration (config.yml).

**Comment by bjunited** [comment]
Hello!

My apologies for not providing sufficient details,

Version Number of TabList: 1.4
Minecraft Version: 1.12.2
Spigot Version: https://imgur.com/a/GXVtr
TabList Configuration: https://pastebin.com/ZRskey9D

**Comment by montlikadani** [comment]
@bjunited 
I did not find any mistakes that would be a problem.

Did you set yourself a nickname (/nick)?

Send a plugin list (in screenshot). (Print Screen button)

**Comment by bjunited** [comment]
No, I did not set a nickname. I was just wanting anyone who connected to have their rank before their name in tab.

![image](https://user-images.githubusercontent.com/34009740/33796096-e96adfac-dce5-11e7-841b-ed7b3922289e.png)

**Comment by montlikadani** [comment]
@bjunited 
Why did not you say that before? You can do this with this plugin: https://www.spigotmc.org/resources/tabname.18819/ (I've tested good for other versions, but it does not update.)

**IMPORTANT! If you are using, disable all nickname settings in the TabList configuration.**

**Comment by bjunited** [comment]
Great, thank you. I will give that a try, my apoloies for the confusion!

**Comment by bjunited** [comment]
Hello,

That plugin doesn't put the name in tab when a player joins the server, it just keeps it white. I am wanting it so it is just there by default and users can't change it at all.

Thank You

**Comment by bjunited** [comment]
Found an alternative solution, thank you anyway :)

**Comment by montlikadani** [comment]
@bjunited 
The "clear-player-nick-on-quit" feature is enabled in the TabList configuration. Disable this.
