### ISSUE TITLE
Placeholder Not Working

### ISSUE THREAD

**Issue by Georgiee7** [montlikadani/TabList#20]
I have installed Heroes, and have also installed their placeholders (using /papi ecloud download Heroes), however, their placeholders are not appearing anywhere, I have tried restarting the server multiple times. Can you help? Thank you in advance,

**Comment by montlikadani** [comment]
Are you using the latest version of PAPI?
Is the placeholder at all in the TabList configuration?

**Comment by Lorm1** [comment]
I am indeed using the latest version of PAPI, in fact I did what you suggested a couple days ago (to download the player placeholders) and it worked just fine. I'm not sure if the placeholder is in the TabList configuration? If you mean if I have added the placeholder text (%<placeholder>%) then yes, I have. However I am not sure if it supports Heroes. I cannot use the %heroes_main_class_name% or %heroes_level% placeholders for example. If that's the case, would you be able to add support for that please? This is the best tablist plugin I have found and I would really like to stick with this!

**Comment by montlikadani** [comment]
If those placeholders do not work, I can not help it any more, because this is a problem with PAPI or Heroes. I think this bug is the first time you report to the Heroes plugin.

**Comment by montlikadani** [comment]
**Try updating to the latest version.**
