### ISSUE TITLE
Client Error Spam

### ISSUE THREAD

**Issue by ading2210** [montlikadani/TabList#202]
### Problem
Every time I join the server with this plugin enabled, I get a lot of lag and the error "java.lang.NullPointerException: null" is spammed in the client logs. I have confirmed this by disabling the plugin using PluginManager and joining the server, which produces no errors.

### Details
Plugin version: 5.4.9

Software version: Paper/202 (1.16.3)

### Console error
```
[14:54:07] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at dwm.a(SourceFile:2126) ~[1.16.3.jar:?]
	at ri.a(SourceFile:122) ~[1.16.3.jar:?]
	at ri.a(SourceFile:16) ~[1.16.3.jar:?]
	at ol.a(SourceFile:21) ~[1.16.3.jar:?]
	at ol$$Lambda$3439/1898660734.run(Unknown Source) ~[?:?]
	at any.c(SourceFile:144) [1.16.3.jar:?]
	at aoc.c(SourceFile:23) [1.16.3.jar:?]
	at any.y(SourceFile:118) [1.16.3.jar:?]
	at any.bk(SourceFile:103) [1.16.3.jar:?]
	at djw.e(SourceFile:990) [1.16.3.jar:?]
	at djw.e(SourceFile:656) [1.16.3.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:215) [1.16.3.jar:?]
```
Full client log: https://pastebin.com/hS4avL4F

### Configuration file(s)

config.yml: https://pastebin.com/wzE5PH7e
tablist.yml: https://pastebin.com/bZHXHe8m
all other config files left at default

**Comment by montlikadani** [comment]
What should I do with this? These errors not reproduces the path to my code. I guess, you launched a cracked/bought client with forge and with mods/resource packs which can't load on servers?

**Comment by ading2210** [comment]
> What should I do with this? These errors not reproduces the path to my code. I guess, you launched a cracked/bought client with forge and with mods/resource packs which can't load on servers?

I have a legit mojang account and the same issue occurs with vanilla, forge and fabric. If I use a different computer, the same issue occurs. My guess is that I configured the plugin wrong and somehow that causes the server to send the client invalid data, throwing errors. However I don't see anything wrong with my configuration files.

**Comment by montlikadani** [comment]
All of spigot plugins only works with vanilla environment, because forge is another thing. Make sure that you use the Mojang provided launcher, in order to not get any critical issue. Also, you could reset the tablist configuration (config.yml) by removing and let the plugin generate new.

**Comment by montlikadani** [comment]
> Plugin version: 5.4.9

Ah yeah, please update first

**Comment by ading2210** [comment]
Ok I will reset the config and update the plugin. Btw, I am using the official minecraft launcher so I doubt its something with the launcher.

**Comment by ading2210** [comment]
I have just reset the config and updated the plugin, but the issue does not go away. Maybe my version of paper is too old?

**Comment by ading2210** [comment]
When I tried hosting a server locally with no other plugins, the same issue occurs. I think there is something wrong with the plugin, so I'm gonna use a different tablist plugin now.

**Comment by montlikadani** [comment]
You literally uses very old server software version, which can cause issues like this. Duplicate with this: https://github.com/montlikadani/TabList/issues/205
