### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AquaParc-Minecraft** [montlikadani/TabList#203]
>.... [19:49:01 WARN]: java.io.FileNotFoundException: https://raw.githubusercontent.com/montlikadani/TabList/master/plugin.yml
>.... [19:49:01 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
>.... [19:49:01 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
>.... [19:49:01 WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
>.... [19:49:01 WARN]: at java.net.URL.openStream(URL.java:1068)
>.... [19:49:01 WARN]: at hu.montlikadani.tablist.bukkit.TabList.checkVersion(TabList.java:185)
>.... [19:49:01 WARN]: at hu.montlikadani.tablist.bukkit.Listeners.onPlJoin(Listeners.java:35)
>.... [19:49:01 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor305.execute(Unknown Source)
>.... [19:49:01 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [19:49:01 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [19:49:01 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [19:49:01 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
>.... [19:49:01 WARN]: at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191)
>.... [19:49:01 WARN]: at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174)
>.... [19:49:01 WARN]: at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65)
>.... [19:49:01 WARN]: at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256)
>.... [19:49:01 WARN]: at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139)
>.... [19:49:01 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1255)
>.... [19:49:01 WARN]: at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
>.... [19:49:01 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
>.... [19:49:01 WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
>.... [19:49:01 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [19:49:01 WARN]: [TabList] Failed to compare versions. java.io.FileNotFoundException: https://raw.githubusercontent.com/montlikadani/TabList/master/plugin.yml Please report it here:
https://github.com/montlikadani/TabList/issues

**Comment by montlikadani** [comment]
Update to the new version first time.

**Comment by AquaParc-Minecraft** [comment]
It's ok
