### ISSUE TITLE
Player ping Shows in the 20000's when in reality its in the 20's

### ISSUE THREAD

**Issue by rvark2002** [montlikadani/TabList#206]
### Problem
 The ping displayed when hitting tab is not correct

### Details
Plugin version: 5.51

Software version: Paper 1.16.4

Relevant plugins: 

### Console error
```
Insert here the console error if you have it. 
```

### Configuration file(s)

configuration file: 

Tablist.yml https://pastebin.com/rC3jnKa6

### Screenshots (optional)

![2021-01-08_21 54 59](https://user-images.githubusercontent.com/70348161/104081382-2dfb8980-51fc-11eb-8d5e-76f604d2601d.png)

**Comment by X12503181** [comment]
Same bug for me when I updated Tablist from 5.4.4 to 5.4.8 (and to newer versions). Reset the config and this bug disappeared. Perhaps a bug between configs in different versions?

**Comment by montlikadani** [comment]
You should update the config.yml ping section in order to get it working.
