### ISSUE TITLE
[Request] MVdW

### ISSUE THREAD

**Issue by Lorm1** [montlikadani/TabList#21]
Hello, I am not sure if this is already in place, but hooking into MVdW API would be a pretty nice idea since we would be able to utilize a ton of extra placeholders!

**Comment by montlikadani** [comment]
Unfortunately, I've been hooked to, but I did not succeed because it says it's just its own premium plugin.

**Comment by Lorm1** [comment]
Ah alright, no problem, let me know if anything changes in the future, good luck!
