### ISSUE TITLE
Fake player's skin is default

### ISSUE THREAD

**Issue by ShulkerShellMod** [montlikadani/TabList#213]
### Problem

The skins of the fake players are and will stay default no matter what
### Details
Plugin version: 
v5.5.2
Software version: 
Paper/1.16.5
Relevant plugins: 

### Console error
```
Insert here the console error if you have it or use paste server.
```

### Configuration file(s)

configuration file: 
config.yml: https://pastebin.com/tkwrVxZs
fakeplayers.yml: https://pastebin.com/JqgFZxFu
tablist.yml: 
https://pastebin.com/4qmFY2zm
### Screenshots (optional)

![2021-02-21_01 46 44](https://user-images.githubusercontent.com/79330786/108612210-a7cf8700-73e6-11eb-9cc4-c1e4a6d3a9fe.png)

**Comment by montlikadani** [comment]
In your `server.properties` the `online-mode` is enabled?
