### ISSUE TITLE
Health life indicator doesn't work anymore

### ISSUE THREAD

**Issue by MaximeSharp** [montlikadani/TabList#214]
### Problem
Health life indicator doesn't work anymore

### Details
Plugin version:  5.5.2

Software version:  Paper/481

Relevant plugins: 

> AdvancedHelp, AutoMessager, BattleTracker, DiscordSRV, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, FarmControl, Images, IridiumSkyblock, LocketteX, LoginStreak, LuckPerms, Multiverse-Core, Multiverse-Inventories, PlaceholderAPI, PlotSquared, ProtocolLib, Quests, Rankup, SilkSpawners, Skript, sleep-most, TabList, Vault, ViewDistanceTweaks, Votifier, VotingPlugin, WarpSystem, WitherAC, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Configuration file(s)

config.yml: https://pastebin.com/tmkpCeM8
tablist.yml: https://pastebin.com/88NAGPvV

### Screenshots (optional)

https://imgur.com/a/l0CbeJQ

**Comment by montlikadani** [comment]
Is it worked before Paper `#473`?

**Comment by MaximeSharp** [comment]
It used to work on Paper `#470` and stopped working when updating to Paper `#481`.

It does work again on Paper `#496` but doesn't support a `/tablist reload` and need a server restart to get it working again.

**Comment by montlikadani** [comment]
Yea, there was a new addition for Paper that some of it, breaks some things in plugins which uses String-based methods. I'll fix this after I've done with new thing that will be added to tablist.
