### ISSUE TITLE
Issues with hide-players-from-tablist?

### ISSUE THREAD

**Issue by LilRooks** [montlikadani/TabList#217]
### Problem
Skins show inconsistently when `hide-players-from-tablist: true`

### Details
Plugin version: 5.5.2

Software version: git-Paper-526 (MC: 1.16.5)

### Console error
None

### Configuration file(s)

configuration file: https://pastebin.com/JVQwrpnQ

**Comment by montlikadani** [comment]
Please show a screenshot

**Comment by LilRooks** [comment]
![image](https://user-images.githubusercontent.com/24774868/110342568-8a5f0780-7ff9-11eb-87af-bb34a80423f5.png)

**Comment by montlikadani** [comment]
There is currently no solution to this and no idea. I made a hacky solution, but it may not work. This will be included in the next version.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/025573dae3a135954c623d3547fecb36d1dc4b6f

You can test this with [this](https://github.com/montlikadani/TabList/actions/runs/636533075) build under Artifacts.

**Comment by LilRooks** [comment]
No change in the problem, seemingly.

**Comment by montlikadani** [comment]
Is this still reproducible with the new release (v5.5.3)?

**Comment by montlikadani** [comment]
Closing this issue for now. I you have this issue please create a new one with detailed description and reproduction.
