### ISSUE TITLE
Everything is not working

### ISSUE THREAD

**Issue by FinalBosses** [montlikadani/TabList#218]
First, the tab list header and footer weren't showing up. Then, one by one, our prefixes started dissapearing. After a little, our server crashed. before the server crashed, I kept toggling the tab list on and off to make sure that that wasn't the reason.

Plugin version: 5.5.2

I'm running bukkit 1.16.5, but the command /bukkit:version gives me this:
Paper version e4d8a6279 (minecraft 1.16.5)

Console error:
https://mcpaste.io/705a529f5c7212ad

[pebblehost-167823-mhc9kc.zip](https://github.com/montlikadani/TabList/files/6112768/pebblehost-167823-mhc9kc.zip)

**Comment by FinalBosses** [comment]
I asked my hosting network about the crash, and they said it was actually because of I ran out of RAM. The plugin was still having issues though, crashing just wasn't one of them.

**Comment by montlikadani** [comment]
You literally have misconfigured tablist.yml
```yml
- "&e&lPlayers:&6 %online-players%&7/&6%max-players%""
```
Remove `"` at the end of this string

Also, use [this](https://codebeautify.org/yaml-validator) for validating your files.

**Comment by FinalBosses** [comment]
Thanks, I didn't notice that. Also, thanks for the code validating website, I will start using that.
Sorry for using your time
