### ISSUE TITLE
Add a * permission

### ISSUE THREAD

**Issue by FinalBosses** [montlikadani/TabList#221]
### Description

Could you add a permission like `tablist.*` so that it is easier to grant all the tablist perms?
Also, maybe you could also use `*` as a permission, because a lot of other plugins use that, and that would let people use `*` in a permission plugin to simply grant all perms, including perms from your plugin.

**Comment by FinalBosses** [comment]
I'm still not completely sure if this already works.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/wiki/Commands-&-Permissions-Bukkit#another-permissions

**Comment by FinalBosses** [comment]
sorry again
