### ISSUE TITLE
I can't use ampersand character in tablist

### ISSUE THREAD

**Issue by MelonHell** [montlikadani/TabList#222]
I can't use ampersand character in tablist
![изображение](https://user-images.githubusercontent.com/53826469/110773621-fea1e100-826d-11eb-8107-f9b355b4ae97.png)

**Comment by montlikadani** [comment]
Show more informations please

**Comment by MelonHell** [comment]
TabList: v5.5.2
Server: Yatopia 1.16.5 build #36

ampersand substitution does not work properly

now: Test&&Test -> TestTest
should be: Test&&Test -> Test&Test

**Comment by montlikadani** [comment]
[This build](https://github.com/montlikadani/TabList/actions/runs/643581038) should fixes this issue. You can download this under Artifacts.
