### ISSUE TITLE
prefix error

### ISSUE THREAD

**Issue by Cube-Box-391** [montlikadani/TabList#225]
Problem

I was changing the colours of the prefixes of the groups and then when i did "/tablist reload" i got the error and the prefixes where not showing up.

Plugin version: 

currentVersion":"git-Paper-574 (MC: 1.16.5)"

tablist 5.5.2

Relevant plugins: 

Console error

https://paste.gg/p/anonymous/23c8cda24ab244158356daf9bce8097b

Configuration file(s)

https://paste.gg/p/anonymous/3bc5800ffda346a4a313fe82b11acd6d

**Comment by montlikadani** [comment]
Put `'` before the `Player` prefix.
```yml
Player:
   prefix: '&f[&2Player&f] -'
   tabname: '%player%'
```

**Comment by Cube-Box-391** [comment]
ok thanks that fixed it
