### ISSUE TITLE
Willingness to fix a bug.

### ISSUE THREAD

**Issue by Rollczi** [montlikadani/TabList#229]
I'd like to fix the sort bug on the tablist. Can you provide links to the classes where the sorting takes place or where they should be done. If I succeed, I will send a pull request.

**Comment by montlikadani** [comment]
There was no sort priorities in code since the recode time, groups implementations can be found in [this package](https://github.com/montlikadani/TabList/tree/master/bukkit/src/main/java/hu/montlikadani/tablist/bukkit/tablist/groups)

**Comment by montlikadani** [comment]
Also duplicate with https://github.com/montlikadani/TabList/issues/180
