### ISSUE TITLE
No AFK feature at all

### ISSUE THREAD

**Issue by AnimeDrache** [montlikadani/TabList#232]
### Problem

There is no AFK function at all. It says there are detailed functions to show AFK players but the plugin has nothing like that. Not in the config and also there is no way to open the plugin ingame (/tablist (or /tl doesnt work. no command like that). So I need a feature to show that people are afk in the list
### Details
Plugin version: 
Latest (v5.5.2)
Software version: 
Paper (latest)
Relevant plugins: 

### Console error
```
Insert here the console error if you have it or use paste server if the error is too long.
```

**Comment by montlikadani** [comment]
This is not an afk plugin. AFK is an additional feature in this plugin, which refers to check if a player is afk or not. If one of the player is AFK, they will get the afk format if enabled. [L40](https://github.com/montlikadani/TabList/blob/master/bukkit/src/main/resources/config.yml#L40)

**Comment by AnimeDrache** [comment]
Nevermind you know what? I've mixed up your plugin with the "★ TabListPro ★" Plugin. I was so confused, I am very very sorry! Will definitely test yours cause I am missing the AFK feature in the other one =).
