### ISSUE TITLE
Header / Footer not working properly

### ISSUE THREAD

**Issue by AnimeDrache** [montlikadani/TabList#233]
### Problem
Greetings,

as you can see on the screenshot this is how it looks to me without any changes in the config but afk feature. The other animations like the "Welcome player" or Website etc. do not appear. There is also no error in the console but why are they not showing?

Same to when I was trying to use a custom alias to be shown behind the players name. I wanted to show the world where they are in but the multiverse alias "%multiverse_world_alias%" doesnt work. Maybe I am doing something wrong there.

### Details
Plugin version: 
TabList-5.5.2
Software version: 
Paper
Relevant plugins: 

### Console error
```
Insert here the console error if you have it or use paste server if the error is too long.
```

### Screenshots (optional)
![Screenshot_7](https://user-images.githubusercontent.com/51856826/116786771-c6b25f80-aaa0-11eb-9487-162226821969.png)

**Comment by montlikadani** [comment]
> TabList-5.5.2

You were using old version of TL and you have permissions section defined in tablist file.

**Comment by AnimeDrache** [comment]
That fixed it. It wasn't up to date on the spigot website. Now it works.
