### ISSUE TITLE
No sorting for groups

### ISSUE THREAD

**Issue by AnimeDrache** [montlikadani/TabList#236]
### Problem
For some reason I can't sort groups. So groups that start with the letter "B" are sometimes above and sometimes under other letters (and no, I have the afk option to move them downwards disabled). Plus there is no tutorial somewhere or any kind of permission to sort groups even though it says here that there must be an option: https://dev.bukkit.org/projects/animated-tab-tablist

### Details
Plugin version: 
5.5.3
Software version: 
Paper (up to date)
Relevant plugins: 
-
### Console error
-
Insert here the console error if you have it or use paste server if the error is too long.
-

### Configuration file(s)
Hastebin doesnt allow me to save files.

**Comment by montlikadani** [comment]
Specify `sort-priority` under your one of the group and reload the plugin.
```yml
groups:
  Mod:
    prefix: "df"
    sort-priority: 2
```
