### ISSUE TITLE
No Prefix / Suffix when activated per world player list

### ISSUE THREAD

**Issue by PlaceblockHD** [montlikadani/TabList#237]
At first, thanks for your fast response to my last report! But however i have another problem and i dont think its because of me...

I have  a bungeecord server but TabList installed on a spigot server. And now i found the problem why i couldnt see the prefixes and suffixes. Every time i enable "per-world-player-list" there are no prefixes and suffixes...

Maybe its my mistake, but o couldnt find it...

But, whatever, nice Plugin!

Here is my config file (converted to txt):

[config.txt](https://github.com/montlikadani/TabList/files/6411788/config.txt)

**Comment by montlikadani** [comment]
Show screenshot for proof

**Comment by PlaceblockHD** [comment]
![grafik](https://user-images.githubusercontent.com/53298953/116820089-735d1180-ab73-11eb-8e32-bdd8037de1f3.png)

Here is my Groups-File:

`globalGroup:
  prefix: ''
  tabname: ''
  suffix: ''
groups:
  default:
    prefix: '&7Spieler - '
  owner:
    prefix: '&cOwner - '`
    
i am member of the group owner...

**Comment by montlikadani** [comment]
Why did you closed? Is your issue fixed?

**Comment by PlaceblockHD** [comment]
Yes, i decided to code my own system to implement my party system ... : ) but, again, nice plugin!
