### ISSUE TITLE
Cannot see ping, ram and players online when having * permissions in luckperms.

### ISSUE THREAD

**Issue by cryokesh34** [montlikadani/TabList#238]
### Problem
Hello, recently I noticed, that I as an admin I cannot see ram usage, my ping and players online. But when I demote myself in luckperms and relog, I can see this info.

### Details
Plugin version: Latest (5.5.4)
Main plugins (working with permissions, groups and tab): Vault, EssentialsX, Luckperms, SuperVanish, PlaceholderAPI

Paper, version 631
Implementing API version 1.16.5-R0.1-SNAPSHOT

### Console error
It wasn't showing any errors or warnings in the console.

### Configuration file(s)
https://pastebin.com/c0JuLAHk
(hastebin was having some problems with saving it so I used pastebin)

### Screenshots (optional)
![With lp permissions](https://user-images.githubusercontent.com/77076358/116824819-803a2f00-ab8c-11eb-8843-8924913bb8b9.png)
![Without lp permissions](https://user-images.githubusercontent.com/77076358/116824820-80d2c580-ab8c-11eb-908a-16bd2bd572df.png)

**Comment by montlikadani** [comment]
You have permissions section defined in tablist.yml file.

**Comment by cryokesh34** [comment]
> You have permissions section defined in tablist.yml file.

Thanks that fixed it right away! I'm just dumb and thought the tablist.yml was some code file or something like that...
