### ISSUE TITLE
Conflict with BetterTeams plugin

### ISSUE THREAD

**Issue by jahua50** [montlikadani/TabList#240]
### Problem
Betterteams have a function that a team name (tag) is shown in front of players' name on top their head. But after enabling tablist, the tag will disappear every time tablist refreshes. But I could not find any option in the config file related to players' tag.

### Details
Plugin version: 5.5.4

Software version: Paper 1.16.5

Relevant plugins:  BetterTeams

### Console error
No console error

### Configuration file(s)
![image](https://user-images.githubusercontent.com/35772634/119166773-99e6dc00-ba91-11eb-898c-e142afdaa4fb.png)
![image](https://user-images.githubusercontent.com/35772634/119166796-a10dea00-ba91-11eb-86ad-c03da73e2993.png)

### Screenshots (optional)
The tag will disappear after tablist refreshes.
![image](https://user-images.githubusercontent.com/35772634/119166831-aec36f80-ba91-11eb-81e7-6dcdb7fdbdaa.png)

**Comment by montlikadani** [comment]
The first build on [Actions](https://github.com/montlikadani/TabList/actions) page fixes this. You can try install
