### ISSUE TITLE
Group Ordering bugged

### ISSUE THREAD

**Issue by YashBattlebee** [montlikadani/TabList#241]
After I set the group order in the way I want them to appear, the players still appear randomly on the Tab List

**Comment by montlikadani** [comment]
Show screenshot, plugin version that you use, show how you configured groups ordering and configuration.

**Comment by YashBattlebee** [comment]
# Format of the displayed name: prefix - tabname - suffix
# This will be applied to all players without any other group assigned
groups:
  NORMIE:
    prefix: '&#e7ffe3[NORMIE] '
    tabname: '&f%player%'
  INTERN:
    prefix: '&e&l[INTERN] '
    tabname: '&f%player%'
  MOD:
   prefix: '&#f86eff&l[MOD] '
   tabname: '&f%player%'
  BOOSTER:
    prefix: '&#f066ff&l[BOOSTER] '
    tabname: '&f%player%'
  VIP:
    prefix: '&b&l[VIP] '
    tabname: '&f%player%'
  VIP+:
    prefix: '&a&l[VIP+] '
    tabname: '&f%player%'
  LEGEND:
    prefix: '&#2f1cff&l[LEGEND] '
    tabname: '&f%player%'
  FATHER:
    prefix: '&#ff1f35&l[FATHER]&r '
    tabname: '&f%player%'
  ADMIN:
    prefix: '&c&l[ADMIN] '
    tabname: '&f%player%'
  OWNER:
    prefix: '&6&l[OWNER] '
    tabname: '&f%player%'

Groups.yml file
![image](https://user-images.githubusercontent.com/39647748/119496596-44f0e180-bd81-11eb-9f62-d694cbe5bb27.png)

**Comment by YashBattlebee** [comment]
Bugged ordering, I am using the latest version!

**Comment by montlikadani** [comment]
> 
> 
> Bugged ordering, I am using the latest version!

`/version tablist` and show the output

**Comment by montlikadani** [comment]
You don't even have `sort-priority` specified in any of your group.

**Comment by YashBattlebee** [comment]
how do I do that?

**Comment by montlikadani** [comment]
Use this example in one of your group:
```yml
VIP:
  prefix: "vip"
  sort-priority: 3
```
and do the same with your others group

**Comment by YashBattlebee** [comment]
and the higher the priority the higher they appear?

**Comment by montlikadani** [comment]
Higher priority will appear at the top

**Comment by YashBattlebee** [comment]
okay thanks!

**Comment by YashBattlebee** [comment]
so priority 1 will always be at the bottom?

**Comment by montlikadani** [comment]
yes

**Comment by YashBattlebee** [comment]
# Format of the displayed name: prefix - tabname - suffix
# This will be applied to all players without any other group assigned
groups:
  NORMIE:
    prefix: '&#e7ffe3[NORMIE] '
    sort-priority: 1
    tabname: '&f%player%'
  INTERN:
    prefix: '&e&l[INTERN] '
    sort-priority: 2
    tabname: '&f%player%'
  MOD:
   prefix: '&#f86eff&l[MOD] '
   sort-priority: 3
   tabname: '&f%player%'
  BOOSTER:
    prefix: '&#f066ff&l[BOOSTER] '
    sort-priority: 4
    tabname: '&f%player%'
  VIP:
    prefix: '&b&l[VIP] '
    sort-priority: 5
    tabname: '&f%player%'
  VIP+:
    prefix: '&a&l[VIP+] '
    sort-priority: 6
    tabname: '&f%player%'
  LEGEND:
    prefix: '&#2f1cff&l[LEGEND] '
    sort-priority: 7
    tabname: '&f%player%'
  FATHER:
    prefix: '&#ff1f35&l[FATHER]&r '
    sort-priority: 8
    tabname: '&f%player%'
  ADMIN:
    prefix: '&c&l[ADMIN] '
    sort-priority: 9
    tabname: '&f%player%'
  OWNER:
    prefix: '&6&l[OWNER] '
    sort-priority: 10
    tabname: '&f%player%'

Still doesn't work

**Comment by montlikadani** [comment]
Show screenshot

**Comment by YashBattlebee** [comment]
![image](https://user-images.githubusercontent.com/39647748/119651548-c2c8f180-be42-11eb-9889-8409e99b520e.png)
![image](https://user-images.githubusercontent.com/39647748/119651590-cc525980-be42-11eb-87bd-708a10a5144b.png)

**Comment by denisdnu** [comment]
I have the same issue. What is the expected fix time?

**Comment by montlikadani** [comment]
Is this still reproducible with the newest releases (v5.5.5)?

**Comment by Bruneitor123** [comment]
Able to reproduce in v.5.5.5!
`groups:
  default:
    prefix: ' &7[&bMinion&7] '
    tabname: '%player%'
    sort-priority: 1
  bedrock:
    prefix: ' &3[&8Bed&7rock&3] '
    tabname: '%player%'
    sort-priority: 2
  taroleros:
    prefix: ' &7[&6Taroleros&7] &e'
    tabname: '%player%'
    sort-priority: 3
  mod:
    prefix: ' &d+&r &7[&aMod&7] &b'
    tabname: '%player%'
    sort-priority: 4
  Admin:
    prefix: ' &c+&r %anim:Admin%'
    tabname: '%player%'
    sort-priority: 5
`
![image](https://user-images.githubusercontent.com/32247565/124785088-8cd45e00-df14-11eb-8460-e5f02fa24725.png)

**Comment by Bruneitor123** [comment]
Able to reproduce in v.5.5.5!
![image](https://user-images.githubusercontent.com/32247565/124786812-06208080-df16-11eb-8478-2e9005a9c2f3.png)

![image](https://user-images.githubusercontent.com/32247565/124786775-fdc84580-df15-11eb-8304-29f467b1c73d.png)

**Comment by veploxmine123** [comment]
Same goes for me...
![image](https://user-images.githubusercontent.com/85697813/125416893-7f70fa35-e928-4192-8549-dee10e20458e.png)

**Comment by veploxmine123** [comment]
![image](https://user-images.githubusercontent.com/85697813/125494104-28fa4019-4ffc-40aa-9a56-cef8697b7e2a.png)

**Comment by Polyex** [comment]
I got this problem also

**Comment by TheNety** [comment]
Hey, we understand it's an issue, I'm also able to reproduce this. We're trying to fix it.

**Comment by PaDo90** [comment]
I have the same issue. sort-priority don't works, too.

**Comment by montlikadani** [comment]
The newest build from [Actions](https://github.com/montlikadani/TabList/actions) page fixes this issue, select the first one and find Artifacts. Please let us know if it works.

**Comment by PaDo90** [comment]
> The newest build from [Actions](https://github.com/montlikadani/TabList/actions) page fixes this issue, select the first one and find Artifacts. Please let us know if it works.

Sorry I don't know what to do :D

**Comment by denisdnu** [comment]
It works for me, thanks.
