### ISSUE TITLE
nullpointerexception throws after certain types of disconnections

### ISSUE THREAD

**Issue by nikawiwi** [montlikadani/TabList#243]
### Problem

After about 30 minutes of the server running just fine, the error: java null pointer exception starts to throw about 5 times a second, with nothing of note happening beforehand. In the server log it says nothing, just: Craft Scheduler Thread (number) - TabList/Warn: java.lang.NullPointerException
Doesn't seem to actually do anything, and the plugin continues to work, but it starts to 1 fill up the log and 2 lag the server

The above was my original post, but now there is another error that came up before the null pointer, and it stopped. see pastebin in console error. The pastebin happened just after someone left the game (they were kicked for being AFK if that changes anything) and they came back and it stopped

New update, it happens when someone leaves and stops if they come back - the more ppl leave, the more it happens.

### Details
Plugin version: 
v5.5.4
Software version: 
Paper v758
Relevant plugins: 
We have Geyser, luckperms, vault and essentials
### Console error
```
pastebin.com/QY83Js79
```

### Configuration file(s)

pastebin.com/N8f51t4B

**Comment by montlikadani** [comment]
You can try to use the new build from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts.

**Comment by nikawiwi** [comment]
Ok, will do.
