### ISSUE TITLE
Scoreboard Flickering Issue

### ISSUE THREAD

**Issue by Stampede2011** [montlikadani/TabList#247]
### Problem

While using the **Sponge** edition of Tablist, enabling the "tablist-groups" feature with "use-own-scoreboard" set to true will cause a flickering effect with the scoreboard. I am currently using the EasyScoreboards Sponge plugin to provide a Scoreboard to the player. Without the "use-own-scoreboard" setting enabled, the scoreboard just disappears entirely. It is ONLY while this "tablist-groups" feature is enabled that the flickering happens.

### Details
Plugin version: 1.0.3

Software version: SpongeForge 2838-7.3.0, Minecraft 1.12, and Forge 14.23.5.2847

Relevant plugins: EasyScoreboards by YottaFlops version 2.3

### Console error
No relevant console errors

### Configuration file(s)

https://hastebin.com/kapipafowa.pl

### Screenshots (optional)

GIF of the flickering effect: https://i.gyazo.com/6d74c996d74005224cac7e87ef987406.mp4

**Comment by montlikadani** [comment]
Fixed in v1.0.4
