### ISSUE TITLE
Hex nicknames don't work I used %essentials_nickname% papi

### ISSUE THREAD

**Issue by joshuacode751** [montlikadani/TabList#250]
### Problem
The hex color codes doesn't work on nicknames in TABS

### Details
Plugin version: 

Software version: 

Relevant plugins: 

### Console error
```
Insert here the console error if you have it or use paste server if the error is too long.
```

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/32216817/125208510-72f49b80-e2c5-11eb-8b0a-542281a2584a.png)

**Comment by joshuacode751** [comment]
notice the NAME in the scoreboard thats a %essentials_nickname% but in the RealScoreboard plugin

**Comment by montlikadani** [comment]
Fill out the issue template.

**Comment by joshuacode751** [comment]
Sorry im kinda new in Github I already put the issue

**Comment by montlikadani** [comment]
> Plugin version:
> Software version:

^

**Comment by montlikadani** [comment]
The newest build on [Actions](https://github.com/montlikadani/TabList/actions) page fixes that. You can install by clicking on the first one and find Artifacts.

**Comment by joshuacode751** [comment]
It works thank you
