### ISSUE TITLE
Hide players from tablist error spectator mode

### ISSUE THREAD

**Issue by ronifernando** [montlikadani/TabList#251]
### Problem
->Enable hide-players-from-tablist
->Server have more than 2 player
->2 player in spectator mode
->1 player change gamemode from spectator to survival => becoming a ghost player for other spectator player
->other spectator player change gamemode to survival => ghost player become invisible for them.
->manual fix => that ghost player needs to change their gamemode to spectator again and change back to survival. 

### Details
Plugin version: 5.5.5

Software version:  Paper 1.17.1

Relevant plugins:  ProtocolLib Latest

### Console error
```
no console log error
```

### Configuration file(s)

just change config hide-players-from-tablist  to true

### Screenshots (optional)

Soon

**Comment by montlikadani** [comment]
Is this not intentional behaviour?

**Comment by ronifernando** [comment]
I found that bug while trying to enable hide-player-from-tablist feature on my server

**Comment by ronifernando** [comment]
it only happens for spectator mode players

**Comment by veploxmine123** [comment]
same thing happened to me too It doesn't hide vanished players

**Comment by TheNety** [comment]
Can confirm. If hide-players-from-tablist is enabled and you switch to spectator mode and back to creative, you become invisible for other players.

**Comment by montlikadani** [comment]
Can someone test the above attached build if it works now? Currently it is only available for 1.19.3. https://github.com/montlikadani/TabList/actions/workflows/gradle.yml

**Comment by montlikadani** [comment]
I can not reproduce this anymore. I am going to close this.
