### ISSUE TITLE
Tablist not showing at the start, not showing hearts in tablist.

### ISSUE THREAD

**Issue by AnriGameS** [montlikadani/TabList#253]
### Type of bug

Error in console, Other

### TabList version

TabList version 5.5.5 
An ultimate animated tablist. 
Author: montlikadani

### Software version

This server is running Paper version git-Paper-625 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Relevant plugins

Plugins (69): AltDetector, AuthMe, AutoMessager, Banknotes*, Better-Enchantments, BetterSleeping3, BigDoors, BigDoorsOpener, BlockBall*, BlockLocker, Brewery, Cannons, ChestBoats, ChestShop, Citizens, CMILib, ColoredSigns*, CombatLogX, CrackShot, DeathCoordinates, DefensiveTurrets, DeluxeCoinflip, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, FancyBags, FastAsyncWorldEdit (WorldEdit), GSit, HideStream*, Images, Jobs, LevelledMobs, LightAPI, LuckPerms, Magic, MedievalFactions, MineableSpawners, Minepacks, MiniMOTD, MTVehicles, PacketListenerApi*, PlaceholderAPI, PluginConstructorAPI, PlugMan, ProtocolLib, QualityArmory, Quests, RealPing*, Sentinel, ServerSigns, Ships, SkBee, SkinsRestorer, Skript, skript-reflect*, skript-yaml, SmokingPipes, StaffPlus, TabList, ThatPacketAddon*, TradeSystem, Vault, Vehicles, VehiclesPlusPro, Vixio*, WorldEditSUI, WorldGuard, WorldGuardExtraFlags

_nice plugin number_

### Console error (if applicable)

https://paste.gg/p/anonymous/737893b6f9c54667a135db188c1fc6ba

### TabList configuration files

https://paste.gg/p/anonymous/40a5b7a6a05f4870ac0463b43c33883a

### Bug description

Whenever I start the server the Tablist doesn't show up until I hit /tablist reload. After that, the Tablist shows fine, except the hearts don't show up in the tablist.

**Comment by montlikadani** [comment]
Seems like it is caused by asynchronous scoreboard objective creation. The newest build from [Actions](https://github.com/montlikadani/TabList/actions) page will fixes it. You need to select the first one and find Artifacts, under this, install this build.
