### ISSUE TITLE
Hex-color error

### ISSUE THREAD

**Issue by wilddip** [montlikadani/TabList#255]
### Type of bug

Error in console

### TabList version

last, bungee didn't has this cmd (waterfall)

### Software version

-

### Console error (if applicable)

https://paste.gg/p/anonymous/2755888c347c49f9b2c20571ab9ae1d9

### TabList configuration files

https://paste.gg/p/anonymous/d20831c0702d4a71a3536d78ed2c2fd0

### Bug description

Can't use hex colors on bungee

**Comment by montlikadani** [comment]
Install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts.
