### ISSUE TITLE
sorting by permissions

### ISSUE THREAD

**Issue by EpicNB** [montlikadani/TabList#256]
### Type of bug

Other

### TabList version

TAB version 2.9.1
An all-in-one solution that works
website: https://www.spigotmc.org/resources/57806/
Auther: NEZNAMY

### Software version

Paper version git-Paper-119 (MC:1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git:f25facb)

### Relevant plugins

TAB plugin only

### TabList configuration files

https://paste.gg/p/anonymous/2c43d0c623424b0385a301a062e3c140/files/fd6763e5ea3f4cdc888370bbbfe5bd2a/raw

Or

https://paste.gg/p/anonymous/2c43d0c623424b0385a301a062e3c140

### Bug description

The issue is that the mod rank, show up at the bottom of the tablist. But i want them to be below admin and above helpers..
Any help would be nice! I managed to understand any other parts of the plugin, but for some reason i cant fix this.

**Comment by montlikadani** [comment]
Wrong plugin
