### ISSUE TITLE
Getting this error when server starts

### ISSUE THREAD

**Issue by akex06** [montlikadani/TabList#257]
### Type of bug

Error in console

### TabList version

![image](https://user-images.githubusercontent.com/67469268/128611109-8745d344-fb03-4f09-bc14-27016cdbd429.png)

### Software version

This server is running Purpur version git-Purpur-1316 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b9480ac on ver/1.17.1) You are 1 version(s) behind Previous version: git-Purpur-1163 (MC: 1.16.5)

### Console error (if applicable)

https://paste.gg/p/anonymous/662f59b5791746cbb38dbb781e48d73e

### TabList configuration files

[config.txt](https://github.com/montlikadani/TabList/files/6949605/config.txt)

### Bug description

It doesn't make anything it justs pops up that error

**Comment by montlikadani** [comment]
Your host does not allow for TL to check for updates through opening a stream to github.
