### ISSUE TITLE
TPS Bugging Out

### ISSUE THREAD

**Issue by charlie-works** [montlikadani/TabList#259]
### Type of bug

Other

### TabList version

11.08 13:02:12 [Server] INFO TabList version 5.5.5
11.08 13:02:12 [Server] INFO An ultimate animated tablist.
11.08 13:02:12 [Server] INFO Author: montlikadani

### Software version

11.08 13:02:22 [Server] INFO Checking version, please wait... 11.08 13:02:23 [Server] INFO This server is running Paper version git-Paper-"6e7f9aa" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6e7f9aa) 11.08 13:02:23 [Server] INFO You are 24 version(s) behind

### Relevant plugins

11.08 13:02:43 [Server] INFO Plugins (16): Chunky, CombatLogX, HeadDrops*, InventorySpy, LaggRemover, NoCheatPlus, PowerRanks, ProtocolLib, RealScoreboard, SimpleTpa*, SirBlobmanCore (SirBlobmanAPI, XSeries), Skript, sleep-most, SuperVanish, TabList, TCPShield

### TabList configuration files

[](https://paste.gg/p/anonymous/ae6b715b48634c0cbbc5ed874738fa17)

### Bug description

TPS bugging out and going too many digits after the decimal.

Link to tablist
[](https://i.imgur.com/yfFAbOD.png)

**Comment by charlie-works** [comment]
https://i.imgur.com/yfFAbOD.png

**Comment by montlikadani** [comment]
You can configure the tps size in config at [this line](https://github.com/montlikadani/TabList/blob/master/bukkit/src/main/resources/config.yml#L94-L97)

**Comment by charlie-works** [comment]
Thanks for the quick response, but it  says that it is already set to 2?

**Comment by montlikadani** [comment]
Can you show us your config file?

**Comment by charlie-works** [comment]
[](https://pastebin.com/b1he7jNp)

**Comment by montlikadani** [comment]
You need to enable the `enable` option under tps
```yml
  tps:
    enable: true
```

**Comment by charlie-works** [comment]
replaced %tps% with %ping%, for now but shouldn't make a difference

**Comment by charlie-works** [comment]
fixed! tysm <3
