### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by Specthra** [montlikadani/TabList#261]
### Type of bug

Other

### TabList version

![image](https://user-images.githubusercontent.com/77130187/129109786-11639fd3-be42-458e-a9dd-0677982ca112.png)

### Software version

[18:08:02 INFO]: This server is running Purpur version git-Purpur-1328 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c8befee on ver/1.17.1) [18:08:02 INFO]: You are 1 version(s) behind [18:08:02 INFO]: Previous version: git-Purpur-1316 (MC: 1.17.1)

### Relevant plugins

![image](https://user-images.githubusercontent.com/77130187/129109955-c0cf19e4-69a9-499c-a744-f0789795a513.png)

### TabList configuration files

https://paste.gg/p/anonymous/dd650e47794f44fc93b02eb60970a645

### Bug description

![image](https://user-images.githubusercontent.com/77130187/129110310-0dbbac88-0380-4f0b-bf99-91f02d6afbf2.png)

- The groups don't work well for me, in the configuration I have a prefix for each one and it comes out as shown in the image
- I can't remove the ping from users
- Header and Footer don't work

![image](https://user-images.githubusercontent.com/77130187/129110421-3abbec16-dbf3-43bf-b669-ce394dc4d1e2.png)

I hope you can help me if it is my mistake

**Comment by montlikadani** [comment]
1. Those players primary group is different and that is why it displays other group prefixes.
2. You can disable tablist objectives in config
3. Probably you misconfigured something in tablist file
