### ISSUE TITLE
Objective PingTab already exists in this scoreboard 

### ISSUE THREAD

**Issue by vlaetansky** [montlikadani/TabList#262]
### Type of bug

Other

### TabList version

TabList version 5.5.5                                                                                     
An ultimate animated tablist.                                                                             
Author: montlikadani

### Software version

This server is running Paper version git-Paper-780 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAP| SHOT) | You are 6 version(s) behind Previous version: git-Yatopia-ver/1.16.5-42 (MC: 1.16.5)

### Relevant plugins

AuthMe, ChatEx*, Citizens, CommandNPC*, DiscordSRV, EarthQuake*, eBackup, Essentials, Essent
ialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), HolographicDisplays, Hol
ographicExtension, KeepChunks, LuckPerms, PlaceholderAPI, ProtocolLib, RandomTeleport, ReActions, SkinsRestorer, TabList, 
ViaVersion, VoidTeleport, Vulcan, WorldGuard 

### Console error (if applicable)

https://paste.gg/p/anonymous/a793588abea347bda00a52434e00f305

### TabList configuration files

https://paste.gg/p/anonymous/0121a7b963db403c9625f21fb2264666

### Bug description

Heyo! We are using Tab list in our lobby server which connects several servers behind bungee, sometimes after one of the server restart and players being transferred to the lobby they are kicked with the provided exception.

**Comment by montlikadani** [comment]
Show the entire console error not just the half

**Comment by vlaetansky** [comment]
https://paste.gg/p/anonymous/cf439f31374a4609ad8ed5802c601196 
here it is

**Comment by montlikadani** [comment]
Did you installed tablist on bungee and bukkit too?

**Comment by vlaetansky** [comment]
no, it is only installed on the bukkit server

**Comment by vlaetansky** [comment]
it is 15 mb
https://drive.google.com/file/d/1iBpnJ5RcaxvG2i1OI-wEjNCmjC6BsCiU/view?usp=sharing

**Comment by montlikadani** [comment]
The bukkit log not the bungee

**Comment by vlaetansky** [comment]
https://drive.google.com/file/d/1TgOH7tF52BqqLXBP5EnCrO_VobjhvLUp/view?usp=sharing
Tablist does not fire any exceptions

**Comment by vlaetansky** [comment]
There is no plugins on bungee network that modify Tab list in any way. I will try to update the plugin thou, thanks!

**Comment by montlikadani** [comment]
Any result? This issue will be closed otherwise

**Comment by vlaetansky** [comment]
Looks like the issue is resolved. Thank you!
