### ISSUE TITLE
Weird formatting of tablist

### ISSUE THREAD

**Issue by Kanin** [montlikadani/TabList#263]
### Type of bug

Other

### TabList version

Most recent from Actions. 

### Software version

This server is running Purpur version git-Purpur-1308 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4afd4e on ver/1.17.1)

### Relevant plugins

BetterRTP, BetterSleeping4, BlueBridgeCore, BlueBridgeWG, BlueMap, BlueMap-Essentials, BuycraftX, CommandBlockPermissions, CompatNoCheatPlus*, CoreProtect, DeluxeChat, DeluxeChatHex, DeluxeTags*, DiscordSRV, EpicRename, Essentials, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, GoldenCrates, GSit, HolographicDisplays, JustOneMore*, LuckPerms, Maintenance, mcMMO, NexEngine, NoCheatPlus, Orebfuscator, PlaceholderAPI, PlayTime*, ProtocolLib, RightClickHarvest, ServerListPlus, SuperVanish, TabList, Towny, TownyBlue, TownyChat, WorldBorder, WorldGuard, WorldGuard-Towny*

### Console error (if applicable)

N/A

### TabList configuration files

https://paste.gg/p/anonymous/ab4a1aea77874721859cc1c26c732d1c

### Bug description

As shown in this [video](https://kanin.cannot.date/2021/08/13/FObR.mp4), tablist won't show my nick/group unless I am AFK. This happens at random.

**Comment by montlikadani** [comment]
Its not weird, this is normal behaviour, getting out from afk status will restores the entire player list name, and returns to the appropriate group with prefixes after the given refresh interval.

**Comment by Kanin** [comment]
> Its not weird, this is normal behaviour, getting out from afk status will restores the entire player list name, and returns to the appropriate group with prefixes after the given refresh interval. Unless you have some plugin which removes and tries to hide player from tab or restores the name entirely.

You can see my plugin list and my config, you say "after the refresh interval" but it didn't go back for hours. Are any of the plugins I have known incompatibilities?

**Comment by Kanin** [comment]
It is also VERY random when it happens and to which players

**Comment by montlikadani** [comment]
You would rather try to remove all plugins one by one and see what will be the result.

**Comment by Kanin** [comment]
> You would rather try to remove all plugins one by one and see what will be the result.

This isnt really possible being how inconsistent it happens to begin with.

**Comment by montlikadani** [comment]
In this case can not be fixed, I can not reproduce.
