### ISSUE TITLE
remove-gray-color-from-tab-in-spectator does not work

### ISSUE THREAD

**Issue by TimonH-98** [montlikadani/TabList#264]
### Type of bug

Other

### TabList version

16.08 11:55:10 [Server] Server thread/INFO TabList version 5.5.5
16.08 11:55:10 [Server] Server thread/INFO An ultimate animated tablist.
16.08 11:55:10 [Server] Server thread/INFO Author: montlikadani

### Software version

This server is running CraftBukkit version 3203-Spigot-18c71bf-aa69d1c (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### Relevant plugins

 WartungsSystem, SH-Timber, LuckPerms, ChatColor2, noGrief, NoHackedClients, ClearLag, BetterReload, WorldBorder, FarmProtect, ProtocolLib, FastLeafDecay, RHSignItem, Vault, MyCommand, WorldEdit, Essentials, MarriageMaster, Towny, HolographicDisplays, WorldGuard, DiscordSRV, TabList, EssentialsChat, EssentialsSpawn, Harbor, XrayDetection, UltimateChairs, PvPToggle

### TabList configuration files

https://paste.gg/p/anonymous/6893f3d46497475086320303bbe98362

### Bug description

I see no effekt with the setting "remove-gray-color-from-tab-in-spectator: true".
I installed the latest version of Protocollib (4.7.0) but Mods in GM 3 (Spectator) are still grey in the playerslist.
Also the Players in GM3 are sortet to the Bottom of the Playerlist.

Thanks for having a look

**Comment by montlikadani** [comment]
Yea, it was temporarily disabled as there was an issue with it. But in the newest build/release you'll be able to use again. You can try from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts.

**Comment by TimonH-98** [comment]
Perfekt! That worked. Thanks man
