### ISSUE TITLE
Priority Not Work Correctly

### ISSUE THREAD

**Issue by IranMine123** [montlikadani/TabList#265]
### Type of bug

Compatibility issue, Other

### TabList version

5.5.5

### Software version

1.16.4 R0.1 bukkit spigot

### Relevant plugins

 AntiCreeper, PlaceholderAPI, HolographicDisplays, NPCLibPlugin, Core, SkinsRestorer, MuteChat, Mentions, NoteBlockAPI, ViaVersion, LuckPerms, LoginSecurity, ClearLag, SetSpawn, ServersNPC, SimpleTpa, MVdWPlaceholderAPI, StaffChat, Vault, SimpleSit, MoneyPrinters, Scoreboard-revision, AuctionHouse, MysqlEconomyBank, MyCommand, WorldEdit, Essentials, CommandPanels, Multiverse-Core, DeluxeMenus, EssentialsChat, Multiverse-Portals, SuperVanish, WorldGuard, EssentialsXMPP, TabList, EssentialsProtect, Multiverse-Inventories, EssentialsGeoIP, EssentialsAntiBuild, EssentialsSpawn, GadgetsMenu, CommandSigns, SilkSpawners, ItemEdit, EconomyShopGUI, GriefPrevention, Randomtp, PWarp

**I dont think there is a problem with plugins...**

### Console error (if applicable)

nothing

### TabList configuration files

https://pastebin.com/Mwzpezyu     config
https://pastebin.com/qL1Vjeh7       groups

### Bug description

Hello... priority for groups not work correctly...
![Screenshot 2021-08-18 222755](https://user-images.githubusercontent.com/74745380/129948563-54716cab-0224-481f-aef0-85312f1f0177.png)
*Picture* that 3 Default players should go below of helper...
i checked wiki
I changed config and groups and set luckperms weight of groups
Please fix that thx...

**Comment by IranMine123** [comment]
I also reloaded and restarted Server but still didn't fix

**Comment by montlikadani** [comment]
Install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page and select the first one.

**Comment by IranMine123** [comment]
I running plugin at Aternos can you put in Spigotmc.org new Update?

**Comment by montlikadani** [comment]
v5.5.6 is out

**Comment by IranMine123** [comment]
thank you so much :D
