### ISSUE TITLE
Luckperms and Tablist hex colour clash

### ISSUE THREAD

**Issue by TeskTesk** [montlikadani/TabList#266]
### Type of bug

Compatibility issue

### TabList version

Version 5.5.5

### Software version

This server is running Paper version git-Paper-196 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 59d449d) You are 17 version(s) behind

### Relevant plugins

LuckPerms - version: Bukkit-5.3.47
Essentials - version: 2.19.0-dev+252-c746a1c
EssentialsXchat - version: 2.19.0-dev+252-c746a1c

### TabList configuration files

https://paste.gg/p/anonymous/52449489acc4431487423e0ee63c5c0a

### Bug description

The issue is quite simple.

When wanting to display hex code to customise colours, LuckPerms and Tablist both allow it.

However, LuckPerms requires you to put the "&" before the "#", whereas Tablist does not. So inside LuckPerms, you find this line here <prefix.18.&#00d1d1[&#00ffffSeraphim&#00d1d1] &f>.

When using the placeholder %luckperms_prefix% it displays this inside MC, <&[&Seraphim&] with the correct colour.

![d1f54e308c3b3785e1cf85844e9c0540](https://user-images.githubusercontent.com/89501266/130723762-d7b6eb0b-6f46-4b1f-aac2-9e144a2a69bd.png)
![Untitled](https://user-images.githubusercontent.com/89501266/130723764-4613f82e-649e-455a-9736-f19c02123982.png)

Anyway to allow Tablist to include the use of "&" when using hex codes? Otherwise this is not compatible with LuckPerms hex codes.

**Comment by montlikadani** [comment]
Try the newest build from [Actions](https://github.com/montlikadani/TabList/actions) and select the first one.

**Comment by TheNety** [comment]
Rest moved to discord ticket.
