### ISSUE TITLE
Broken ranks on TAB

### ISSUE THREAD

**Issue by xR4Z3R** [montlikadani/TabList#267]
### Type of bug

Other

### TabList version

TabList version 5.5.5
An ultimate animated tablist.
Author: montlikadani

### Software version

 This server is running Tuinity version git-Tuinity-"935b901" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) You are running the latest version

### Relevant plugins

Plugins (15): Chunky, Essentials, EssentialsChat, EssentialsSpawn, eZProtector, FastAsyncWorldEdit (WorldEdit), InfoBoardReborn*, LuckPerms, PlaceholderAPI, ProtocolLib, SkinsRestorer, spark, TabList, Vault, WorldGuard

### Console error (if applicable)

No error

### TabList configuration files

https://paste.gg/p/anonymous/152b2652f0504caf98d09f15e05b060b   <-config.yml
https://paste.gg/p/anonymous/bca062f74ac24f39b9d777a7fbe21d22    <-groups.yml

### Bug description

When any player have any rank set it shows correct prefix on tablist. But it only works if I use **/lp user user group set <group>**. But if I use **"add"** instead of **set**, so that the player have default rank + additional (for example vip) it still shows the default rank on tab instead of vip. What is wrong?

**Comment by montlikadani** [comment]
You need to disable `prefer-primary-vault-group` in config to search for multiple groups not just for primary group.

**Comment by xR4Z3R** [comment]
Works, thank you for quick, helpful response 👍 :)
