### ISSUE TITLE
[1.16.5] Exception while executing task

### ISSUE THREAD

**Issue by bouchbi** [montlikadani/TabList#269]
### Type of bug

Error in console

### TabList version

Tablist version 5.5.5

### Software version

mohist-1.16.5-164

### Console error (if applicable)

https://paste.gg/p/anonymous/ad5bb3b84ec64ac3a545da039c4e5f82

### TabList configuration files

config.yml -> [https://paste.gg/p/anonymous/a26bd4b46cc0473abce9eb75b435a508](url)

### Bug description

So basically I have several errors per second in the console, and the Tab seems not to work at all, I can't describe more, however I made sure that there is no formatting errors in the config files

**Comment by montlikadani** [comment]
Install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page select the first one and find Artifacts.

**Comment by bouchbi** [comment]
Still the same

**Comment by montlikadani** [comment]
No, send the new output

**Comment by bouchbi** [comment]
https://paste.gg/p/anonymous/21f4bbed70b6404483a0cdfca4fa05e9

**Comment by montlikadani** [comment]
Install again the newest build

**Comment by bouchbi** [comment]
alright, worked, thanks
