### ISSUE TITLE
Cannot display nickname of ESS in tablist

### ISSUE THREAD

**Issue by BearLeon** [montlikadani/TabList#27]
Please hope you can increase nicknames can be displayed in the list

**Comment by montlikadani** [comment]
Please send me Essentials and TabList config.yml file.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/f0389af405d1a1641a9c6dc8e2b7092dcbf7aa6e#diff-0f1be8eec416e71c28b41efb0544df26R79

**Comment by BearLeon** [comment]
0.0
