### ISSUE TITLE
Not actualizating groups

### ISSUE THREAD

**Issue by Ondras4620** [montlikadani/TabList#270]
### Type of bug

Compatibility issue

### TabList version

5.5.5

An ultimate animated tablist.
[13:45:48 INFO]: Author: montlikadani

is the console output

### Software version

This server is running Paper version git-Paper-249 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6fa1983) You are running the latest version Previous version: git-Paper-245 (MC: 1.17.1)

### Relevant plugins

Plugins (21): AdvancedBan, AuthMe, CMILib, CoreProtect, dynmap, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, FakaHedaMinequery*, LuckPerms, MyCommand, ProtocolLib, Residence, SkinsRestorer, SuperbVote, TabList, TreeAssist, Vault, Votifier, WorldEdit

issue is most probably LuckPerms but isasue is in tablist

### Console error (if applicable)

none

### TabList configuration files

https://paste.gg/p/anonymous/6e362d91144b4bbb9d87a2bc699e1052

here is a config and groups .ymls

### Bug description

When a player votes/buys vip and luckpers temp. adds group.vip the tab wont reload it until rejoin i solved by kicking them but thats kind of not ideal so is there way of updating that one ? thanks

**Comment by montlikadani** [comment]
You need to disable `prefer-primary-vault-group` as the players gets a new group added as a new parent and this group is not primary.

**Comment by Ondras4620** [comment]
Thanks it worked for me

**Comment by zediious** [comment]
What is the solution to this with Sponge? The suggested configuration option above doesn't appear to be in `spongeConfig.conf`. 

All my groups need to inherit default so I can't get around this currently.

**Comment by montlikadani** [comment]
Sponge is a different software and differenet API that is not the same with bukkit. In Sponge you can only use the permissions.
