### ISSUE TITLE
Groups.

### ISSUE THREAD

**Issue by Aadi-mone** [montlikadani/TabList#271]
### Type of bug

Other

### TabList version

Latest Ver

### Software version

Paper/Craft-Bukkit 1.16

### Relevant plugins

TABLIST AND MULITIVERSE 

### Console error (if applicable)

N/A

### TabList configuration files

**##Config**
hook:

  # Hook to PlaceholderAPI to use custom placeholders.
  placeholderapi: true

# Different player list in different world.
per-world-player-list: true

# Fake players that can be added to the player list.
enable-fake-players: true

# If enabled, the gray color will not appear to other players when the player's game mode is spectator.
# The gray color will only show for the spectator player.
# Requires ProtocolLib!
remove-gray-color-from-tab-in-spectator: false

# true - does not count vanished players in %online-players% placeholder.
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
ignore-vanished-players-in-online-players: false

# true - count vanished staff in %staff-online% placeholder,
# but they need to have "tablist.onlinestaff" permission set.
# false - does not count vanished staff in the %staff-online% placeholder
# Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
count-vanished-staffs: true

# Hide player from player list when a player is AFK?
# Requires Essentials or CMI plugin!
hide-player-from-tab-when-afk: false

# Hide all players from the player list?
# This removes all players from the player list, but the player that has the
# group set is retained as it is not changed during removal, so your group
# will be restored if this option is disabled.
# Requires ProtocolLib to fix view distance issue! (https://github.com/montlikadani/TabList/issues/147)
hide-players-from-tablist: false

# Placeholders formatting
placeholder-format:

  # When the player changes the AFK status, change his tablist name format?
  afk-status:
    enable: false

    # Should the AFK format display in right or left side?
    # true - displays in right side
    # false - displays in left side
    show-in-right-or-left-side: true

    # Show player's group if the player is AFK?
    show-player-group: true

    # Sort AFK players to the bottom of the player list?
    sort-last: false

    # Format when the player is AFK.
    format-yes: '&7 [AFK]&r '

    # Format when the player is not AFK.
    format-no: ''
  time:

    # Use system default time zone instead of searching for that?
    use-system-zone: false

    # Time zones: https://www.mkyong.com/java/java-display-list-of-timezone-with-gmt/
    # Or google it: "what is my time zone"
    time-zone: GMT0

    # Formats/examples: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
    # Format of %server-time% placeholder.
    time-format:
      format: mm:HH

    # Format of %date% placeholder.
    date-format:
      format: dd/MM/yyyy

  # Ping color format for %ping% placeholder.
  ping:
    enable: true

    # Operators usage: https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%ping% <= 200'
    - '&6%ping% >= 200'
    - '&c%ping% > 500'

  # TPS color format for %tps% placeholder.
  tps:

    # Adds ability to the tps value can be highest than default 20.0
    value-can-be-higher: false
    enable: true

    # Operators usage: https://github.com/montlikadani/TabList/wiki/Ping-or-tps-formatting
    formats:
    - '&a%tps% > 18.0'
    - '&6%tps% == 16.0'
    - '&c%tps% < 16.0'

    # How many numbers do you want to display after "." in %tps% placeholder?
    # The number should be higher than 0.
    # Example: 3 = 20.14
    size: 2

  # Memory bar settings for %memory_bar% variable
  memory-bar:
    char: '|'
    colors:
      used: '&c'
      free: '&a'

      # When the server memory less than 80
      allocation: '&e'

      # When the server memory is on critical level (less than 40) and some resource need memory to run.
      released: '&6'
    size: 80

# Enable changing of prefix & suffix in player list?
change-prefix-suffix-in-tablist:
  enable: true

  # Disable groups in these worlds.
  disabled-worlds:

    # Use the list as whitelist?
    use-as-whitelist: false
    list:
    - myWorldWithUpper

  # Automatically add groups from another plugins to the tablist groups.yml on every reload?
  # If a plugin does not support Vault, it will not be added.
  sync-plugins-groups-with-tablist: true

  # Hide player's group in player list when the player is vanished?
  # Requires Essentials, SuperVanish, PremiumVanish or CMI plugin!
  hide-group-when-player-vanished: false

  # Hide player's group in player list when the player is AFK?
  # Requires Essentials or CMI plugin!
  hide-group-when-player-afk: false

  # Do you want to assign global group to normal groups?
  # true - "globalGroupPrefix + normalGroupPrefix"
  # false - "normalGroupPrefix"
  assign-global-group-to-normal: false

  # Prefer player's primary Vault group when assigning tablist group from groups.yml?
  # true - player will be assigned their primary vault group where possible
  # false - applies the group that has the higher priority in the permission plugin
  prefer-primary-vault-group: true

  # Refresh interval in server ticks.
  # Set to 0 if you don't want to refresh the groups.
  # If 0, then you will need to execute the /tl reload command to refresh the groups.
  refresh-interval: 4

# Tablist objective types
# Shows your current health (with life indicator), your current ping or any NUMBER placeholder
# after the player's name (before the ping indicator).
tablist-object-type:
  enable: true

  # Objective settings
  object-settings:

    # Custom placeholder - accepts only number-ending placeholders, like %level%.
    custom:
      value: '%level%'

    # The player's health - displayed after the player's name.
    health:

      # For these players the health will not be displayed
      restricted-players:
      - exampleplayer
      - players

  # Types:
  # ping - player's ping
  # health - player's health
  # custom - custom placeholder
  type: ping

  # In these worlds the objects will not be displayed
  disabled-worlds:
  - testingWorld

  # Interval for objects refreshing. In seconds.
  # Note: The health is not updating auto due to display issues.
  refresh-interval: 3

# Check for updates?
check-update: true

# Download new releases to "releases" folder?
# This only works if the "check-update" is true.
download-updates: false

# Log plugin messages to console?
logconsole: true

**##Groups**
# Format of the displayed name: prefix - tabname - suffix
# This will be applied to all players without any other group assigned
globalGroup:
  prefix: ""
  tabname: ""
  suffix: ""

groups:
  # Vault group name OR player name OR custom group name (custom is assigned via permission)
  exampleGroup:
    prefix: "&a[&cStaff&a]&6 "
    tabname: "%player-displayname%"
    suffix: "&7 <12>"
    #permission: tablist.staff

  Default:
    prefix: "&f"
    tabname: "%player%"
    suffix: ""

  Admin:
    prefix: "&7<62>&r %anim:Admin%"
    tabname: "%player%"
    suffix: "&7 <62>"

  PlayerName:
    prefix: "&a[MyGroup]&7"
    tabname: "%player%"
    suffix: ""

**##Tablist Config**
# Tablist header & footer with animations.

# Available placeholders: https://github.com/montlikadani/TabList/wiki/Placeholders
# Available symbols: https://github.com/montlikadani/TabList/wiki/Symbols

# Use %anim:animationName% placeholder to make an animation. Must be firstly created in animcreator.yml file!

# How do I use this tab section? Take a look at this page: https://github.com/montlikadani/TabList/wiki/TabList-Usage

# Enable the tab to show for all players? (Header & footer)
enabled: true

# Save the toggled tablists to a file and load them after server restart.
# If this false, if the file is exists, it will be deleted automatically at server restart.
remember-toggled-tablist-to-file: true

# Hide tab when the player is vanished?
# Requires Essentials, CMI or SuperVanish plugin!
hide-tab-when-player-vanished: false

# In these worlds tab will NOT be displayed
disabled-worlds:
#- "world1"

# For these players tab will NOT be displayed
blacklisted-players:
#- myname

# Tab update time interval. (In ticks!)
# Set to 0 to disable tab refreshing.
interval: 4

# Define if the header & footer should be randomized.
# Animation placeholders won't be affected.
random: false

header:
- "---------------"
- "&f&lSami Logam" 
- "---------------"
- ""
- "&aOnline: %server_online_MainLobby% §7| &aTPS: %tps% §7| &aPing: %ping% "
- "---------------"

footer:
- "---------------"
- "&e&lServer Status \n \n &fSurvival: &7%playerlist_online,world,yes,amount,public_survival+public_survival_nether+public_survival_the_end% &fSkyblock: &7%playerlist_online,world,yes,amount,Skyblock+Skyblock_nether+Skyblock_the_end% &fKitPvP: &7%playerlist_online,world,yes,amount,PVP% &fBedwars: &7%playerlist_online,world,yes,amount,bedwars_arena+bedwars+bedwars_5+bedwars_2+bedwars_3+bedwars_4+% \n \n &7&l>>&b&ladarshofficial.aternos.me&7&l<<"
- "---------------"

# Defines per world tablist for different worlds
# You can separate worlds with ", " to show tablist in that worlds
# You can create as many worlds you want
per-world:
  saf : # you can add multiple worlds here
    header: "&fYou Are Now Playing Survival in &e&lSami Logam."
    footer: "&eOnline Players: &fOverWorld: &a%server_online_public_survival% &fNether: &a%server_online_public_survival_nether% &fEND: &a%server_online_public_survival_the_end% \n &aTotal Server Online: %server_online%"
    
  justWorld:
    header: "%anim:perWorld%"
    footer: "&6World:&7 %world%"

    # Defines per player tablist in this world
    per-player:
      playerName:
        header: "&3This is a per player plugin %anim:tablist%&3."
        footer:
        - "&6World:&7 %world%"
        - "&aPlayer:&8 %player%"

  public_survival, public_survival_nether public_survival_the_end :
    # Defines per group tablist only in the above world
    # Requires Vault plugin!
    per-group:
      groupName:
        header: "&3This is a per group plugin %anim:tablist%&3."
        footer:
        - "&6World:&7 %world%"
        - "&aGroup:&8 %vault_rank%"

# Defines per-permission tablist
# Any player/group have tablist.name permission node will use the set of tab header/footer.
#permissions:

# Defines per player handled tablist
per-player:
  testplayer:
    header: "%anim:perPlayer%"
    footer: "&5&m======================"

# Defines per-grouped tablist for players.
# Requires Vault plugin!
per-group:
  vaultGroup:
    header: "%anim:perGroupHead%"
    footer: "%anim:perGroupFoot%"

### Bug description

I want to some worlds Tablist to be same and to show their names like merging some worlds players together, but I tried per-world with "," for more worlds but it didn't work, then I saw the per-group option but its also doesn't seems to work.

please help me.

**Comment by montlikadani** [comment]
Support should be on discord.

**Comment by Aadi-mone** [comment]
@montlikadani 
In our state/region for some legal reasons we can't use Discord till a time, so please provide support here.
