### ISSUE TITLE
Incompatibility with mod ?

### ISSUE THREAD

**Issue by bouchbi** [montlikadani/TabList#273]
### Type of bug

Compatibility issue

### TabList version

TabList version 5.5.5

### Software version

running Mohist version 1.16.5-764 (MC: 1.16.5)

### Console error (if applicable)

https://paste.gg/p/anonymous/b6acf19d61f64b4a9721bd398b0dabd5

### TabList configuration files

https://paste.gg/p/anonymous/a9376f86e7b6401ea38340ee78cab622

### Bug description

The plugin works perfectly fine, except when I add a mod that I made myself, maybe an incompatibility issue since the error links to your plugin, idk, maybe you can enlighten me ? (Btw, I already had a bug that you fixed, so my TabList version may not be the official one)

**Comment by montlikadani** [comment]
What is the issue?

**Comment by bouchbi** [comment]
Oh yeah sorry I forgot the most important, it's when someone try to join the server, it connects but when trying to join the world it says "UTFDataFormatException: malformed input around byte"

**Comment by montlikadani** [comment]
Try the newest newest build from [Action](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts.

> Oh yeah sorry I forgot the most important, it's when someone try to join the server, it connects but when trying to join the world it says "UTFDataFormatException: malformed input around byte"

Doesn't seem to caused by TL plugin

**Comment by bouchbi** [comment]
Ok, so I will try to look on my mod to see what can causes it, but the error is weird
