### ISSUE TITLE
After entering command the server crashes

### ISSUE THREAD

**Issue by tvhee-dev** [montlikadani/TabList#274]
### Type of bug

Error in console

### TabList version

TabList version 5.5.5

### Software version

This server is running Paper version git-Paper-259 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 810d200)

### Console error (if applicable)

https://paste.gg/p/anonymous/56077e55711c45a0947df96dd3ced501

### TabList configuration files

https://paste.gg/p/anonymous/2d9940c9f0eb47baa541dfd632ae083c

### Bug description

You have to fix your null error. This occurs if I type "/tablist player tvhee prefix "Test ".

**Comment by tvhee-dev** [comment]
public static boolean hasPermission(Player player, String perm) {
		if(perm == null)
                     return false;
		
		if (PLUGIN.isPluginEnabled("PermissionsEx")) {
			try {
				return ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager().has(player, perm);
			} catch (Throwable e) {
				// Pex2 supports bukkit provided "hasPermission" check
			}
		}

		return player.hasPermission(perm);
	}
	
Just null check the perm, if null return false.

**Comment by montlikadani** [comment]
Better fix will be to change the `permission` variable

https://github.com/montlikadani/TabList/blob/a31aa8c59161339d0109c1a770ae5d648f3bdb28/bukkit/src/main/java/hu/montlikadani/tablist/bukkit/tablist/groups/TeamHandler.java#L5

and it will be initialized with a default `""` (empty) string.

**Comment by tvhee-dev** [comment]
Yes good idea, I am also a programmer that is why I tried helping you

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/d763a69073e8cc70b60774d0ba46118a05e9419f

This commit contains the fix for this exception, you can install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts.
