### ISSUE TITLE
Hex codes support

### ISSUE THREAD

**Issue by OugiFormula** [montlikadani/TabList#275]
### Description
I got a plugin named HexNicks which allow users to get hex color in their usernames
![image](https://user-images.githubusercontent.com/25551010/133093186-32bcef33-8272-4e63-b093-5d4857503853.png)
this is what happened when I use the nickname placeholder in tablist
instead of looking like this
![image](https://user-images.githubusercontent.com/25551010/133093312-41593b12-4e50-4d5e-ade8-ac514d1bb388.png)

I assume it's because there's no hex code support for the plugin and I hope you can add it.
thanks!

**Comment by montlikadani** [comment]
You probably uses an old version of TL
