### ISSUE TITLE
4 Rows Tablist

### ISSUE THREAD

**Issue by LiannOM** [montlikadani/TabList#277]
### Description

Add a way to create tablist like this

![Screenshot_6 png db87f0a840e876d7ddbe7020d0928c94](https://user-images.githubusercontent.com/82086199/133925867-b25d9e96-291a-4937-a5ae-48a3d4d52126.png)

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/pull/226 already in progress

**Comment by Kenyy11** [comment]
When there will be update So everyone Can use it?

niedz., 19 wrz 2021, 13:35 użytkownik montlikadani ***@***.***>
napisał:

**Comment by montlikadani** [comment]
Reason of why I closed this issue: https://github.com/montlikadani/TabList/pull/226#issuecomment-1015734048
