### ISSUE TITLE
TabList and plugin of "no nametag"

### ISSUE THREAD

**Issue by Frithy0** [montlikadani/TabList#278]
### Type of bug

Compatibility issue

### TabList version

[16:57:50] [Server thread/INFO]: TabList version 5.5.6
[16:57:50] [Server thread/INFO]: An ultimate animated tablist.
[16:57:50] [Server thread/INFO]: Author: montlikadani

### Software version

[16:58:27] [Thread-55/INFO]: This server is running Airplane version git-Airplane-82 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8207533 on HEAD) Unknown version Previous version: git-Paper-196 (MC: 1.17.1)

### Relevant plugins

https://github.com/AuracleTech/NoNameTag/releases

### TabList configuration files

https://paste.gg/p/anonymous/86f7f48cbf7f43aa9559fb5200459896

### Bug description

When i activated the option "change-prefix-suffix-in-tablist" the plugin of no nametag don't work... 

I want hide the nanetag of the players but i want see my differents ranks in my tablist. 
Can you help me please ?  

illustrations : 
change-prefix-suffix-in-tablist : false
![image](https://user-images.githubusercontent.com/56309938/134698493-c3e7b2ce-bcbd-4b67-868f-a7afba3b3667.png)

change-prefix-suffix-in-tablist : true
![image](https://user-images.githubusercontent.com/56309938/134698797-ea12535b-cee1-4ee6-931c-866d7dc5ec67.png)

**Comment by montlikadani** [comment]
Can you perform a `/team list` command in game and send the output in screenshot here.

**Comment by Frithy0** [comment]
![image](https://user-images.githubusercontent.com/56309938/134701484-d09308c3-66d0-4002-a05a-875861cb1a71.png)

**Comment by montlikadani** [comment]
Try the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page select the first one and find Artifacts. It may be fixes this issue

**Comment by Frithy0** [comment]
Hmm no don't work, i have try with an other plugin and it's good ! 
Thank's !
