### ISSUE TITLE
[1.16.5] Error while using Mohist

### ISSUE THREAD

**Issue by bouchbi** [montlikadani/TabList#279]
### Type of bug

Error in console

### TabList version

Tablist v-5.5.5

### Software version

running Mohist version 1.16.5-764 (MC: 1.16.5)

### Relevant plugins

Plugins (19): LuckPerms, PlaceholderAPI, NametagEdit, Vault, ProtocolLib, WorldEdit, Essentials, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, EssentialsSpawn, WorldGuard, WorldEditSelectionVisualizer, Citizens, AuthMe, Jobs, SuperVanish, dtlTraders, TabList

### Console error (if applicable)

https://paste.gg/p/anonymous/e6364ff0cb6e4cec97e8c84ccce15c5b

### TabList configuration files

https://paste.gg/p/anonymous/1966f7244a3f4fcc96c44550e159982d

### Bug description

There is no real "bug", however I was wondering why the prefix was not displaying in the tab and I think this may come from this little error. But you should know better than me

**Comment by montlikadani** [comment]
> Tablist v-5.5.5

Please update to v5.5.6, you can also get the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page.

**Comment by bouchbi** [comment]
I still got the error

**Comment by montlikadani** [comment]
Send the new console error

**Comment by bouchbi** [comment]
https://paste.gg/p/anonymous/0b884407d76f41caac963485d019259a

**Comment by montlikadani** [comment]
Mohist is a trash software, please consider to use Purpur at least. Mohist making many breaking changes.

**Comment by bouchbi** [comment]
Yeah, and that’s why we are usint mohist, because it’s the only software I know that uses both mods and plugins

**Comment by TheNety** [comment]
Go to Mohist about adding support for this plugin.
As said on their website:
`"Mohist is compatible with almost every forge mod, and bukkit/spigot plugin. If you find a mod or plugin with issues, let us know it by joining our Discord server or opening a GitHub issue, and we can add support for it !"`

**Comment by montlikadani** [comment]
The only issue with Mohist that is described before, it has a breaking change that there is no `ScoreboardTeam` constructor defined in Mohist patches or it has been removed accidentally.

This is the constructor what I've talking about:
https://github.com/montlikadani/TabList/blob/d34d032310c82658b73de72231057a52ba8d45e2/bukkit/src/main/java/hu/montlikadani/tablist/bukkit/utils/reflection/ClazzContainer.java#L115

**Comment by bouchbi** [comment]
Okay, thanks for the explanation, that makes sense about why the grades are not displaying on the tablist at all.
I’m gonna let mohist know about this, unless you already did

**Comment by SirSamurai** [comment]
thanks montlikadani, i will see what happens

**Comment by montlikadani** [comment]
The above commit will fixes this issue.
