### ISSUE TITLE
A player name is displayed with a black "0" instead of "600"

### ISSUE THREAD

**Issue by Hanarion** [montlikadani/TabList#28]
Like the title said, i've a player who have the name "Mateoxx600" and his name is displayed "Mateoxx0" with the 0 black
A screen :
[http://cloud.hanarion.fr/screen/09-59-10_2018-05-20.png](http://cloud.hanarion.fr/screen/09-59-10_2018-05-20.png)

**Comment by Hanarion** [comment]
That's LuckPerms, i haven't any group.yml just a database :/

**Comment by Hanarion** [comment]
That's my config.yml :

**Comment by Hanarion** [comment]
`# Tablist v1.3.2.9 by sn1cko
# Time is set in milliseconds which means every 20 = 1 second
# for example: 6000 = 5 minuntes OR 300 = 15 seconds
# 
# The announcer will never stop if the time is set to 0
# Else it will stop after the amount of milliseconds you wish
# 
# There are currently 15 variables available which can be built in
# for example %player% - will display the playername or %health% - will give out the health
# all other variables can be found on the website
# https://dev.bukkit.org/projects/tablist/pages/variables
# You can also add PlaceholderAPI to your server to get way more variables
# Download-Link (with instructions):
# https://www.spigotmc.org/resources/placeholderapi.6245/
Tablist:
  Settings:
    Staff:
      Permission: tablist.staff
    ShowVanishedPlayerOnVariable:
      Toggle: false
      ChangeText:
        Toggle: false
        UsersSeeOnlineText: '%online%'
        StaffsSeeOnlineText: '%online% | %vanished%'
    CustomPrefix:
      Toggle: true
      Format: '%prefix%%player%'
    Toggle: true
    Time: 20
    Messages:
      Header:
      - |-
        &2play.evolucube.fr
        &7===================
      - |-
        &3play.evolucube.fr
        &7===================
      - |-
        &6play.evolucube.fr
        &7===================
      Footer:
      - "&7===================\n&2evolucube.fr \n&2discord.gg/QnExtpq"
      - |-
        &7===================
        &3evolucube.fr
        &3discord.gg/QnExtpq
      - |-
        &7===================
        &6evolucube.fr
        &6discord.gg/QnExtpq
`

**Comment by Hanarion** [comment]
Oh shit i'm a crap, that's not your plugin i'm using, that's another plugin named tablist, sorry for that :/

**Comment by Hanarion** [comment]
Why are 2 plugins named TabList xD

**Comment by montlikadani** [comment]
Closed, this invalid
