### ISSUE TITLE
Players jumping on tablist when having more than one group

### ISSUE THREAD

**Issue by xR4Z3R** [montlikadani/TabList#281]
### Type of bug

Other

### TabList version

TabList version 5.5.6
An ultimate animated tablist.
Author: montlikadani

### Software version

This server is running Tuinity version git-Tuinity-"935b901" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) You are running the latest version

### Console error (if applicable)

none

### TabList configuration files

config.yml -> https://paste.gg/p/anonymous/8d640f70582b4acba72442610efa0075
groups.yml -> https://paste.gg/p/anonymous/057f0f0b9a994c10a21cda25ab4d70f1

### Bug description

I would like to just record gif and paste it here but unluckily i can't do it for now, so i will try to describe it.
When I give any player second group (for example VIP but could be literally anything) whole tab is just jumping really quickly. I think it just tries to show both groups, because when player have only one then everything is okay. I don't know if that description is sufficient, if not then ask me anything :P

**Comment by montlikadani** [comment]
Try the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts. Make sure to install the jar file. Hopefully this will fixes your issue.

**Comment by xR4Z3R** [comment]
Now I have something like that (broken sorting, it appears that those who joined recently are higher on tablist):
![tab](https://user-images.githubusercontent.com/89855119/135755857-4e70b87a-2033-4bbd-97e4-1a98cd9a568b.png)

**Comment by TheNety** [comment]
Can't reproduce none of these 2 issues with v5.5.7
