### ISSUE TITLE
 Hide FakePlayers OPTION

### ISSUE THREAD

**Issue by MarkinhosMLP** [montlikadani/TabList#287]
Hide FakePlayers OPTION
Would be cool to have an option to hide fake players... but you may be wondering "why hiding fakeplayers? When using TAB, the autocomplete suggest the fakeplayer/bot name and it can be used for custom words and other things, and this is really cool
![image](https://user-images.githubusercontent.com/47507632/139508523-303d3707-2e96-4d56-aec4-50b60de08f3b.png)
 but when they appear in TAB
![image](https://user-images.githubusercontent.com/47507632/139508545-d60e9d2f-9112-493f-a609-2a6c33b56b40.png) is really annoying... so... idk if its possible but it would be awesome

**Comment by montlikadani** [comment]
If you created those fake players with other resource like Citizens then you can't with this plugin, you may want to find the option in Citizens config.

**Comment by MarkinhosMLP** [comment]
well... even with or without citizens, apparently i cant do it...
like, i want to hide them from tablist but i want to make possible to "mention" them when using tab in the chat, without /command <tab>, just <tab> (like in the first screenshot)
