### ISSUE TITLE
Rank weight isn't used properly

### ISSUE THREAD

**Issue by Elric02** [montlikadani/TabList#290]
### Type of bug

Other

### TabList version

5.5.6

### Software version

git-Paper-718 (MC: 1.16.5)

### Relevant plugins

Essentials, CMILib, LuckPerms, NametagEdit

### TabList configuration files

https://pastebin.com/3YwF6Sfr

### Bug description

As you can see, my prefer-primary-vault-group is set to false. But it seems it doesn't work.
For example, my moderators who are also VIPs are shown as VIP in the TAB, even with moderator having a weight of 605 and VIP having a weight of 205.
I don't think that's a compatibility problem, as when I modify the VIP display in TabList it works (so TabList has the priority).
Could you do something ? (or explain me if I'm wrong)
Thanks by advance :)

**Comment by montlikadani** [comment]
> 5.5.6

Update to 5.5.7

**Comment by Elric02** [comment]
> > 5.5.6
> 
> Update to 5.5.7

Didn't solve the issue unfortunately

**Comment by montlikadani** [comment]
Show us your groups file

**Comment by Elric02** [comment]
https://pastebin.com/NJ9d5MGf

**Comment by montlikadani** [comment]
Try to move your moderator group under the Owner group and see what happens.

```yml
  Owner:
    prefix: '&7[&cFonda&7] &4'
    suffix: '&c'
  Modo:
    prefix: '&b[&3Modo&b] &3'
    suffix: '&f'
```

**Comment by Elric02** [comment]
Oh wow that actually worked ! Thanks :)

**Comment by montlikadani** [comment]
Yep, as I thought, I literally forgot to document this, that the order of the groups list is matter a lot especially when a user have multiple groups added.
