### ISSUE TITLE
Sponge placeholders

### ISSUE THREAD

**Issue by GewoonJoey** [montlikadani/TabList#293]
Is it possible to use placeholders from sponge plugins/mods in the tablist. I got a Pixelmon server in which I am trying to make the pokedex percentage added in the tablist. The placeholders I need for this are made in a pixelmon placeholders extension: https://github.com/happyzleaf/PixelmonPlaceholders

Unfortunatly these do not work on the [Animated Tab] - TabList plugin. Is there any way for me to make this work? or is it posable to add some way to make this work in the future?

- Joey

**Comment by montlikadani** [comment]
Its describes what PixelmonPlaceholders for: https://github.com/happyzleaf/PixelmonPlaceholders#pixelmonplaceholders
It is an expansion of placeholderapi which is outdated.
