### ISSUE TITLE
1.18 Support

### ISSUE THREAD

**Issue by Spiderjockey02** [montlikadani/TabList#294]
### Type of bug

Error in console

### TabList version

5.5.7

### Software version

git-Paper-18 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 13a445c)

### Relevant plugins

 Plugins (4): Essentials, EssentialsProtect, EssentialsSpawn, TabList

### Console error (if applicable)

https://paste.gg/p/anonymous/4bf18b14b746465bbeaf02fee14039d2

### TabList configuration files

Just downloaded so all default values.

### Bug description

Loaded up the server and joined and then an error occurred causing the plugin not work properly (Tablist is the Minecraft default style)

**Comment by TheNety** [comment]
Hello, 1.18 support is currently in progress. We'll inform you once stable dev build/release is available.

**Comment by montlikadani** [comment]
v5.5.8 of TabList is released.
