### ISSUE TITLE
Symbols not showing in 1.18

### ISSUE THREAD

**Issue by Roky67** [montlikadani/TabList#297]
### Type of bug

Other

### TabList version

5.5.9

### Software version

Paper version git-Paper-27 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 2f31569)

### Relevant plugins

Plugins (17): Chunky, CommandPanels, dynmap, EconomyShopGUI, Essentials, EssentialsChat, EssentialsSpawn, Hat, HeadsPlus, ItemEdit, LocationSetter*, MyCommand, PlaceholderAPI, TabList, UltimateShops, Vault, WorldBorder

### TabList configuration files

https://paste.gg/p/anonymous/58aef2fd40194e2aa8a75f0620a69453

### Bug description

In 1.18 symbols don’t show as they should. When I tried it in 1.17 it worked without any issue.

![image](https://user-images.githubusercontent.com/19331474/144707423-5328822d-6820-402b-a1b3-0402f7169e64.png)

**Comment by montlikadani** [comment]
Show your tablist.yml file

**Comment by Roky67** [comment]
> Show your tablist.yml file

https://paste.gg/p/anonymous/17ff769b58304195a0c6eef78d862eab

**Comment by montlikadani** [comment]
```yml
- "&a? &a&lPeníze: &e$%vault_eco_balance_formatted%"
- "&2&lServer &2&l>"
- "&a? &a&lTps: &e%tps%"
```
Change the tablist file encoding to another code which supports your language phrases.

**Comment by Roky67** [comment]
> ```yaml
> - "&a? &a&lPeníze: &e$%vault_eco_balance_formatted%"
> - "&2&lServer &2&l>"
> - "&a? &a&lTps: &e%tps%"
> ```
> 
> Change the tablist file encoding to another code which supports your language phrases.
> 
> Also you can use the symbols provided in tablist from [wiki](https://github.com/montlikadani/TabList/wiki/Symbols), starts with `<number>`

And how to do that?

**Comment by montlikadani** [comment]
```yml
- "&a<15> &a&lPeníze: &e$%vault_eco_balance_formatted%"
- "&2&lServer &2&l>"
- "&a<75> &a&lTps: &e%tps%"
```

**Comment by Roky67** [comment]
I mean how to change file encoding.

> ```yaml
> - "&a<15> &a&lPeníze: &e$%vault_eco_balance_formatted%"
> - "&2&lServer &2&l>"
> - "&a<75> &a&lTps: &e%tps%"
> ```
> 
> Google is everyone's friend

I mean how to change file encoding.

**Comment by montlikadani** [comment]
<https://community.notepad-plus-plus.org/topic/17226/wrong-encoding>

**Comment by Roky67** [comment]
> https://community.notepad-plus-plus.org/topic/17226/wrong-encoding

It didn’t fix it. I found out more plugins have the same issue in 1.18 although it worked in 1.17. Can it be an issue in Paper?

**Comment by montlikadani** [comment]
Probably not, maybe a client or display issue, try to change your client language.

**Comment by Roky67** [comment]
> Probably not, maybe a client or display issue, try to change your client language.

It still doesn’t work.

**Comment by montlikadani** [comment]
![image](https://user-images.githubusercontent.com/30026208/144709535-76af359c-6906-4da1-b90f-2caa6f0dbf66.png)
Literally works for me every single character including symbols and your characters too.

**Comment by Roky67** [comment]
> ![image](https://user-images.githubusercontent.com/30026208/144709535-76af359c-6906-4da1-b90f-2caa6f0dbf66.png) Literally works for me every single character including symbols and your characters too.

What Mc version do you use?

**Comment by montlikadani** [comment]
The same version as you use, but I installed the newest Paper build 32, but there is no commit to this issue in Paper repository.

**Comment by Roky67** [comment]
I found out what is causing it. It is opened in coding 1250 and there are normally written. For some reason, I cannot switch to UTF-8 which supports it but I can paste codes for it there.
