### ISSUE TITLE
%server-time% does not show the correct time.

### ISSUE THREAD

**Issue by MarioFinale** [montlikadani/TabList#302]
### Type of bug

Other

### TabList version

5.6.0

### Software version

This server is running Paper version git-Paper-77 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5ad1d9a) You are running the latest version Previous version: git-Paper-68 (MC: 1.18.1)
(OpenJDK 17.0.1 Under Windows 10 21H2)

### Relevant plugins

Plugins (19): AuthMe, CoreProtect, F3Name, FarmControl, FastLogin, floodgate, Geyser-Spigot, LibsDisguises, PekoSrvFun, PermissionsEx*, ProtocolLib, ServerListPlus*, SkinsRestorer, spark, TabList, Vault, VillagerSaver, WorldEdit, WorldGuard.

### TabList configuration files

https://paste.gg/p/anonymous/5b4949be32e64cc9985409e8a9fc29d1

### Bug description

%server-time% displays the UTC time, not the local time and the hour and minutes are backwards:
![image](https://user-images.githubusercontent.com/15223565/146493143-777e5ce8-e8f8-494b-b4c6-dc80d6caf276.png)
UTC Time was 05:19, Local time was 02:19.

**Comment by montlikadani** [comment]
You can change it in config
