### ISSUE TITLE
How to remove specific player's prefix?

### ISSUE THREAD

**Issue by ImPeCo** [montlikadani/TabList#303]
### Type of bug

Other

### TabList version

5.6.0

### Software version

This server is running CraftBukkit version 3363-Spigot-f65de01-e36f759 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)

### Relevant plugins

PlaceholderAPI, Vault, GroupManager, Essentials

### Console error (if applicable)

None

### TabList configuration files

https://paste.gg/p/anonymous/c6f2c5f2e573427f89ccf63ec07b07d1
No need but ok

### Bug description

I just dont know how to remove specific player's prefix

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/wiki/Commands-&-Permissions-Bukkit#groupplayer-meta-formatting
