### ISSUE TITLE
Tablist can't start and clean entire config

### ISSUE THREAD

**Issue by KartoniarzEssa** [montlikadani/TabList#314]
### Type of bug

Error in console

### TabList version

TabList-bukkit-5.6.0

### Software version

Paper version git-Paper-121 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 4bf2aef)

### Console error (if applicable)

![Uploading Screenshot_20220101_211956.png…]()

### TabList configuration files

Entire config has been cleared

### Bug description

Plugin can't start it was working normal until paper update

**Comment by KartoniarzEssa** [comment]
![Screenshot_20220101_211956](https://user-images.githubusercontent.com/81422890/147859898-bf929598-810c-4929-93af-10d02b71ac27.png)

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/issues/312
