### ISSUE TITLE
ping not showing, issue with fakeplayer ping + skin

### ISSUE THREAD

**Issue by blau-png** [montlikadani/TabList#316]
### Type of bug

Other

### TabList version

v5.6.1

### Software version

This server is running Paper version git-Paper-"c3d812d" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: c3d812d)

### Relevant plugins

Plugins (32): AutomaticBroadcast, BetterCommandSpy, Brewery, ChestCommands, ChestSort, CoreProtect, CrucialAPI, DeluxeHub, Essentials, EssentialsChat, EssentialsGeoIP, HolographicDisplays, ImageMaps, LuckPerms, Multiverse-Core, Multiverse-Portals, Orebfuscator, PL-Hide, PlaceholderAPI, Playtimes*, ProtocolLib, RedProtect, ServerListPlus*, Shopkeepers, SuperChairs, SuperVanish, TabList, TicketManager, Vault, VoidGen, WorldEdit, ZombieApocalypse

### Console error (if applicable)

none

### TabList configuration files

config: https://paste.gg/p/anonymous/017a879a46c449dda43b16b768c23451

fakeplayers: https://paste.gg/p/anonymous/095de41c5d7741c2a1545cf692cc9138

groups: https://paste.gg/p/anonymous/127a0edfa54842d99ceae2fdf3cfba64

tablist: https://paste.gg/p/anonymous/998cc86b119f43c6b6aaffaa28a577f9

### Bug description

there's several bugs/issues i've encountered until now that have been a problem for some months now (at least for me), so i decided to report the bugs now (i've used the plugin for 1.17 and 1.18)

the fakeplayer's skin only shows up right after the tablist has been reloaded, but it disappears again when a player joins the server or changes the world, it will not reappear again unless you manually reload the tablist
the fakeplayer's ping does not work at all, it is set in the config file and i've also tried to do it via command, it does not show up and always stays at 0

sometimes the afk messages don't show up in chat, only in the tablist, there's no specific reason when they disappear suddenly and come back again i believe, it just happens randomly (?), used to be a minor inconvenience but happens more frequently now then before

the last issue is something rather current that only happened after i updated the plugin to version 5.6.1: the pings don't show up for all players anymore, randomly a few players will not see their + others pings anymore while others still can, then after some time it works for said players again and then others can't see it anymore

i think it also has some troubles updating (when players go afk, the name, prefix etc disappears shortly and the name becomes completely white before it updates to the [AFK] thing and prefix + colours come back) not sure if it's related to the plugin itself though or just the connection, i still included it just in case

thanks in advance though, i hope it can be fixed, really like the plugin!

**Comment by montlikadani** [comment]
> the fakeplayer's ping does not work at all, it is set in the config file and i've also tried to do it via command, it does not show up and always stays at 0

There is no option for fake players to display "random" ping values, those players are not valid existing just an "object". You need to set their ping manually with the proper command.

> sometimes the afk messages don't show up in chat, only in the tablist, there's no specific reason when they disappear suddenly and come back again i believe, it just happens randomly (?), used to be a minor inconvenience but happens more frequently now then before

This is not tablist issue, TL is not a "chat-handling" plugin to send any messages to chat related to players. It is handled by one of the AFK plugin like essentials.

> i think it also has some troubles updating (when players go afk, the name, prefix etc disappears shortly and the name becomes completely white before it updates to the [AFK] thing and prefix + colours come back) not sure if it's related to the plugin itself though or just the connection, i still included it just in case

This can be the source of many of the problems, I mention the ones that are common. The first is that a remove option is enabled in the TL config file that removes the player prefix from the tablist. The second common is that the AFK plugin resets the name of the AFK players on the tablist to the default, so the name of the white player, so the TL plugin has to query the prefixes again. If I saw it correctly in your configuration, the refresh interval is set to 30 seconds, which will not immediately display the players prefixes.

> Performance loss or memory leak

If it is then send the timings and spark reports.

**Comment by blau-png** [comment]
thanks a lot for helping and explaining!
though, i think there was a little misunderstanding with the fakeplayer's ping: it doesn't seem to work at all, even with the command. 

also, do you have any ideas of why the ping on the tablist does not show up for everyone anymore after the update? any way to fix this?

**Comment by montlikadani** [comment]
> though, i think there was a little misunderstanding with the fakeplayer's ping: it doesn't seem to work at all, even with the command. the fakeplayer's skin does not seem to work properly either.

Both are working for me.

**Comment by montlikadani** [comment]
I made some refactoring for fake players so you can install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page.

**Comment by blau-png** [comment]
hey, im very grateful for your efforts but it still doesn't seem to work, i downloaded the version from the link and switched the files but im still having the same problems. do you know of anything else that could be the issue? it seems nobody else is having these problems either...

**Comment by montlikadani** [comment]
Please update the issue title and list again the issues, those which still does not work with the newest build as I can not keep up what is the current issue(s) here.

**Comment by blau-png** [comment]
the issues for now are:
- player ping not showing for everyone, sometimes it shows, sometimes not
- fakeplayer ping not working, (via command or changing in the file itself) always stays at 0
- custom fakeplayer skin changing back to the regular alex/steve skin constantly, only works again when manually reloading the 
  plugin

**Comment by montlikadani** [comment]
> * fakeplayer ping not working, (via command or changing in the file itself) always stays at 0

Fake players is not valid players, after a fake player is created and the tablist objectives is enabled, it will displays 0 each time, because they're not valid ones. Setting ping is works for fake players, it is only changes the ping bar next to the objective.
