### ISSUE TITLE
GlobalGroup doesn't apply if player isn't in a group listed under groups:

### ISSUE THREAD

**Issue by bdagenais2** [montlikadani/TabList#317]
### Type of bug

Other

### TabList version

5.6.1

### Software version

This server is running Paper version git-Paper-143 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 2be9beb) You are 1 version(s) behind Download the new version at: https://papermc.io/downloads Previous version: git-Paper-140 (MC: 1.18.1)

### Relevant plugins

Vault
Luckperms

### TabList configuration files

https://paste.gg/p/anonymous/b786b0327b514cddaca1f46b1b479d71

### Bug description

When setting global group to always apply in config.yml, I am expecting those settings to apply to every player even if they don't have their group under "groups". Instead, the settings in global group only apply if the player's group is also listed under "groups"

**Comment by montlikadani** [comment]
That is how the `assign-global-group-to-normal` works in this case. Other groups must have specified under that section in order to display normal and global group attached to each other.

**Comment by bdagenais2** [comment]
How do I set a suffix to apply to every player, then? I do not want to have to keep modifying the group file every time I add/remove a group from LuckPerms.

**Comment by montlikadani** [comment]
With the above attached commit you will be able to display the global group without any other group specified.
