### ISSUE TITLE
Ability to sort AFK players by priority individually

### ISSUE THREAD

**Issue by HotProtato** [montlikadani/TabList#318]
### Type of bug

Other

### TabList version

5.6.1

### Software version

git-Paper-142 (MC: 1.18.1) (Git: a73c1a)

### Relevant plugins

There's no conflicting plugins, Essentials has the AFK function set to "none" so it shouldn't do anything.

### TabList configuration files

groups:
  Owner:
    prefix: '&b&l[Owner] &7'
    tabname: '%player%'
    suffix: ''
    sort-priority: 3
  
  Admin:
    prefix: '&l&c[Admin] &7'
    tabname: '%player%'
    suffix: ''
    sort-priority: 2
  
  Default:
    prefix: '&7'
    tabname: '%player%'
    suffix: ''
    sort-priority: 1

### Bug description

sort-priority works, however it stops working correctly when AFK sorting is enabled, whether it's to the top or the bottom. Perhaps you should have a configurable "afk-sort-priority" value?

**Comment by montlikadani** [comment]
AFK status will override the groups sorting and it will moves those AFK players to the bottom of the player list. It is intended behaviour.

**Comment by HotProtato** [comment]
In that case, can I change this to a feature request and ask that AFK players have their own configurable weight?

**Comment by montlikadani** [comment]
So you want to sort the AFK players back together? Does this make any sense? Isn't it right to sort them in the last row on the player list?

**Comment by HotProtato** [comment]
It makes perfect sense to do that, however by doing that, you no longer have staff ranks or owner ranks on the top of the tab list.

**Comment by montlikadani** [comment]
> however by doing that, you no longer have staff ranks or owner ranks on the top of the tab list.

You can already do that by disabling `show-player-group`
