### ISSUE TITLE
Integrate Bungee and Bukkit plugin together

### ISSUE THREAD

**Issue by nrbxyz** [montlikadani/TabList#319]
Basically, i want to be able to use tablist on a bukkit server connected to a bungee server without any issues. at the current moment, both try to show up at the same time and it glitches out. If i disable the world in the bungee config, it glitches between no custom tab elements, and the tab elements on the bukkit config

**Comment by montlikadani** [comment]
Makes no sense. Bungee tablist will override bukkit tablist or vice versa. Both have tablist header and footer, there are plenty of limited features in bungee which is possible in bukkit it is usually not possible in other side like in Bungee.

**Comment by nrbxyz** [comment]
What i mean is that the bungee plugin should detect the bukkit plugin and should not put a tablist there. The tablist should instead come from the bukkit config. this could be some option in the bungee config, or it hooks in automatically

**Comment by montlikadani** [comment]
Then why you need bungee version of TL? What feature will you use on bungee if every option coming from bukkit side?

**Comment by nrbxyz** [comment]
for convenience purposes. I have a lot of different servers, and only need the bukkit features on some of them not all of them
If this isnt possible i will just install it sep on each server instead of using the bungee version and defining header and footer for each server
