### ISSUE TITLE
Suggestion: Statistic Placeholder

### ISSUE THREAD

**Issue by Lorm1** [montlikadani/TabList#32]
I am currently trying to use placeholders from the Statistic expansion, however it appears that they are not included. Would it be possible to implement this feature?

**Comment by montlikadani** [comment]
Do you think that? https://www.spigotmc.org/wiki/placeholderapi-placeholders/#statistic-placeholders

**Comment by Lorm1** [comment]
Yep!

**Comment by montlikadani** [comment]
Then use PlaceholderAPI and type this command: _/papi ecloud download Statistic_

**Comment by Lorm1** [comment]
never mind, it works

**Comment by montlikadani** [comment]
Is the Statistic plugin installed?
