### ISSUE TITLE
player name glitched

### ISSUE THREAD

**Issue by maurice1503** [montlikadani/TabList#321]
### Type of bug

Other

### TabList version

tablist version 5.6.1

### Software version

This server is running Purpur version git-Purpur-1468 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 3607ed4 on HEAD)

### Relevant plugins

AdvancedEnchantments, AuctionHouse, BetterRTP, ChestShop, ChestTerminal, Chunky, ColoredEnderChests, CraftingStore, DiscordSRV, DyedBackpacks, EcoPower, ElectricSpawners, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, ExoticGarden, ExtraGear, ExtraHeads, GriefPrevention, GuiRedeemMCMMO*, Harbor, HeadDatabase, HolographicDisplays, HotbarPets, InventoryRollbackPlus, LiteXpansion, LuckPerms, Marriage, Matrix, mcMMO, MobCapturer, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, NexEngine, PL-Hide, PlaceholderAPI, PlayerVaults, PlayerWarps, PluginManager, PlugManX (PlugMan), PrivateStorage, ProtocolLib, ProVotes, Sellwand, ShopGUIPlus, ShowItem, SilkSpawners, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimyTreeTaps, SoulJars, SurvivalTop, TabList, UltimateTimber, Vault, ViaVersion, Votifier, WorldBorder, WorldEdit, WorldGuard

### TabList configuration files

https://paste.gg/p/anonymous/7149260f6b3547af91cb7a8e0be49082

### Bug description

whenever i look in tab i see a member his name glitching https://cdn.discordapp.com/attachments/932268758360264715/932269054163550218/javaw_2022-01-16_11-54-49.gif

**Comment by montlikadani** [comment]
> Relevant plugins

More information needed ^

**Comment by maurice1503** [comment]
> > Relevant plugins
> 
> More information needed ^

added

**Comment by montlikadani** [comment]
Please try to install the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, select first one and find Artifacts. If this problem persists, we'll try to fix it, but first time install the newest build.
