### ISSUE TITLE
Groups Not Working

### ISSUE THREAD

**Issue by charlie-works** [montlikadani/TabList#322]
### Type of bug

Other

### TabList version

18.01 18:51:42 [Server] INFO TabList version 5.6.1 18.01 18:51:42 [Server] INFO An ultimate animated tablist 18.01 18:51:42 [Server] INFO Author: montlikadani

### Software version

18.01 18:51:59 [Server] INFO Checking version, please wait... 18.01 18:52:00 [Server] INFO This server is running Paper version git-Paper-"f1db23e" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: f1db23e) 18.01 18:52:00 [Server] INFO You are 2 version(s) behind 18.01 18:52:00 [Server] INFO Download the new version at: https://papermc.io/downloads 18.01 18:52:00 [Server] INFO Previous version: git-Paper-"6d67504" (MC: 1.18.1)

### Relevant plugins

18.01 18:52:18 [Server] INFO Plugins (31): AdvancedBan, AutoMessage, BanItem, ChatSentinel, ColoredAnvils, DiscordSRV, EnderPearlCoolDown*, Essentials, FarmControl, FirstJoinPlus*, floodgate, HeadDrops, LaggRemover, LuckPerms, MCSF, ProtocolLib, PvPManager, RealScoreboard, SetHomes, SimpleTpa*, Spartan, TabList, TCPShield, UltraBar, Vault, VaultChatFormatter*, ViaBackwards, ViaRewind, ViaVersion, WelcomeMessage*, xSuicide*

### TabList configuration files

Config: https://mcpaste.io/2bda34552c2f5946

Groups: https://mcpaste.io/ca88e1d976841d64

### Bug description

Group colors and text not showing anymore on tablist. Using luckperms and was working fine before. Colors and text in chat work correctly.

![unknown](https://user-images.githubusercontent.com/18120920/150037748-6b4f860d-a42b-40f0-a547-e3f436401e8a.png)

**Comment by montlikadani** [comment]
```
change-prefix-suffix-in-tablist:
  enable: false
```
literally disabled
