### ISSUE TITLE
[ERROR] .... Cannot load plugins/TabList/tablist.yml

### ISSUE THREAD

**Issue by NimaWood** [montlikadani/TabList#324]
### Type of bug

Error in console

### TabList version

5.6.1

### Software version

This server is running Paper version git-Paper-173 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: f6c7d53) You are running the latest version Previous version: git-Paper-169 (MC: 1.18.1)

### Console error (if applicable)

[ERROR] .... Cannot load plugins/TabList/tablist.yml

### TabList configuration files

https://paste.gg/p/anonymous/344ce439e41349c9a3359fbe8592d313

### Bug description

dont load

**Comment by montlikadani** [comment]
More info, show the actual tablist file and console error.

**Comment by NimaWood** [comment]
Thats the Console error there isn't more

montlikadani ***@***.***> schrieb am So., 23. Jan. 2022,
19:45:

**Comment by montlikadani** [comment]
Then what is the issue now?
