### ISSUE TITLE
Tablist groups does not shows after enabling `per-world-player-list`

### ISSUE THREAD

**Issue by Szybkimp3** [montlikadani/TabList#328]
### Type of bug

Other

### TabList version

5.6.1

### Software version

1.17.1

### TabList configuration files

[ok.zip](https://github.com/montlikadani/TabList/files/8033977/ok.zip)

### Bug description

per-world-player-list:
  enabled: false - grups show

per-world-player-list:
  enabled: true - grups not show

**Comment by Szybkimp3** [comment]
yes wait moment

**Comment by Szybkimp3** [comment]
![2022-02-09_16 47 23](https://user-images.githubusercontent.com/99347281/153237415-d1c8b33c-2092-4883-9e3a-27183db9d97c.png)

per-world-player-list:
enabled: false

grups show:)

**Comment by Szybkimp3** [comment]
> 

how to fix this problem?

**Comment by Szybkimp3** [comment]
???

**Comment by Szybkimp3** [comment]
ok i found other plugin thanks

**Comment by KanCi001** [comment]
> được rồi, tôi đã tìm thấy plugin khác, cảm ơn

I have the same problem as you! so what is your alternative plugin?
