### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by WhyNotMrt** [montlikadani/TabList#33]
Hi,

Is it possible to add placeholder in group.yml file?

**Comment by montlikadani** [comment]
Which placeholders are you thinking?

**Comment by WhyNotMrt** [comment]
Prefix placeholder, because I have animated names wich change the Tablist and I don't want that. But when we create group, the name stay the good one (not modified by animated names). So, to avoid to create 40 group for each ranks, only one with prefix will enough for basics players.

I don't know if my explanation were clear, I don't speak english perfectly.

**Comment by montlikadani** [comment]
If you use a different chaing name (tablist), it will not work.

**Comment by montlikadani** [comment]
Added, new version: https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=253730
