### ISSUE TITLE
Vanished players

### ISSUE THREAD

**Issue by Myk4Las** [montlikadani/TabList#334]
Add feature in config. Make a feature that if player is vanished no one can see him in scoreboard.

**Comment by montlikadani** [comment]
This is not a scoreboard plugin

**Comment by Myk4Las** [comment]
I mean tab

**Comment by Myk4Las** [comment]
Add function like this: hide-player-from-tab-when-vanished: true/false

**Comment by montlikadani** [comment]
In player list? The player is invisible to others if vanished, this is how vanish plugins works like Essentials. This feature is useless here, the vanish plugin must do this ability.

**Comment by Myk4Las** [comment]
Im using EssentialsX /vanish while using it im not removed from tab

**Comment by montlikadani** [comment]
Make sure the `hide-displayname-in-vanish` option in Essentials's config is enabled
https://github.com/EssentialsX/Essentials/blob/e12f1b50229037197f9b406ae2af3d172e8fb9dc/Essentials/src/main/resources/config.yml#L45-L47

**Comment by Myk4Las** [comment]
Yep, It's enabled

**Comment by montlikadani** [comment]
Now send the TabList's config file to pastebin.com

**Comment by Myk4Las** [comment]
https://pastebin.com/PsY6zC4J

**Comment by Myk4Las** [comment]
Nvm it's working. I just found out that i was opped in other account :D Thank you! Very good job!
