### ISSUE TITLE
[Question] How to display player's hearts in TabList?

### ISSUE THREAD

**Issue by RT5Phantom** [montlikadani/TabList#340]
### Type of bug

Other

### TabList version

5.6.2

### Software version

Paper 283

### TabList configuration files

NA

### Bug description

_This repository does not seem to let me change this issue's label to the question tag_
Hello there,

I'm trying to get Tab List to display a player's hearts. I saw it done on the plugin's spigot page and see parts of a possible solution in the default configuration files, however I cannot find any way to get it working on the wiki.

Thank you for your help!

**Comment by montlikadani** [comment]
You can by changing this option in config
https://github.com/montlikadani/TabList/blob/master/bukkit/src/main/resources/config.yml#L170

> This repository does not seem to let me change this issue's label to the question tag

Questions are usually asked in our discord server. Github is not the place for basic questions. It is for bugs and features

**Comment by RT5Phantom** [comment]
Alright, sorry about that, thanks for your time!
