### ISSUE TITLE
Add the ability to use raw JSON in a tab to be able to use graphics and more.

### ISSUE THREAD

**Issue by sasha066** [montlikadani/TabList#341]
### Description

Hello. You are apparently the only one who has created a plugin that can display a custom font in a tab. This is very cool, and I am very grateful to you for this.

I'm creating a resource pack for my server, with which I want to display custom graphic elements in TAB, (like prefixes on the Origin Realms server). But I don't want to force my players to install my resource pack. Therefore, I want to make it so that those players who have not installed the resource pack will display normal text prefixes and vice versa - for those who have installed, "graphic" prefixes will be displayed. This can be achieved with vanilla raw JSON, which can be used in the /tellraw command for example. This is done in a combination of using a custom font and the "translate" function https://minecraft.fandom.com/wiki/Raw_JSON_text_format#Translate

It would be cool if you made it possible to use raw minecraft JSON in prefixes, header and footer. This will open up new possibilities for TAB design, for example, it will allow you to automatically translate text, allow you to use images through a resource pack, add interactivity and much more.

If you have added the ability to use a custom font, then your plugin most likely already has a base for processing JSON. So it probably shouldn't be very difficult to add this.

Here is an example of what can be done with json in combination with a resource pack, custom font and translate: https://i.imgur.com/u5pugxz.png
https://i.imgur.com/ukz2UDt.jpeg

**Comment by montlikadani** [comment]
I like this idea.

Basically, you want to be able to specify the TranslatedText format like `{"translate":"chat.type.advancement.task","with":["Replacement"]}`, so in this case the `%s` selector will be the `Replacement` and the result will be `Replacement has made the advancement`? Or do you want to use a full JSON format?

**Comment by shnakm** [comment]
> I like this idea.
> 
> Basically, you want to be able to specify the TranslatedText format like `{"translate":"chat.type.advancement.task","with":["Replacement"]}`, so in this case the `%s` selector will be the `Replacement` and the result will be `Replacement has made the advancement`? Or do you want to use a full JSON format?

It would be nice if full json formatting could be used. ☺️

**Comment by sasha066** [comment]
> I like this idea.
> 
> Basically, you want to be able to specify the TranslatedText format like `{"translate":"chat.type.advancement.task","with":["Replacement"]}`, so in this case the `%s` selector will be the `Replacement` and the result will be `Replacement has made the advancement`? Or do you want to use a full JSON format?

yes, maybe that would be enough, but still, it would be even cooler if you could use full-fledged json :D

**Comment by 4EPBRK6RK6RK** [comment]
Wow! If such functionality appears in the plugin, I will definitely put it on my server!

**Comment by montlikadani** [comment]
The above commit implements this feature. You will be able to use in the next release of TL. Remember that you can only append JSON texts in header/footer. Will create a small documentation for this how to use.

**Comment by montlikadani** [comment]
> But... Why won't JSON work in player prefixes? :( Is this not possible due to the limitations of Minecraft itself or some other reason?

It is possible, but I only worked firstly on header/footer to implement this.

**Comment by shnakm** [comment]
> > But... Why won't JSON work in player prefixes? :( Is this not possible due to the limitations of Minecraft itself or some other reason?
> 
> It is possible, but I only worked firstly on header/footer to implement this. I will add this ability to groups too later.

Wow.  Can't wait for prefixes. 🤤

**Comment by montlikadani** [comment]
The commit attached above includes json support for groups. Currently only tested on 1.18.2 clients, it may not work on versions below this.

If you want to test, you can install the new build from [Actions](https://github.com/montlikadani/TabList/actions) tab, select the first one and look for Artifacts.

**Comment by montlikadani** [comment]
JSON texts should begin with `["",` and ends with `]` to properly parse.

**Comment by montlikadani** [comment]
Remove the extra space before `{` -> `["",{"text":"test123 ","color":"red"}]`

**Comment by montlikadani** [comment]
Thanks for your report, I managed to fix this problem, you can install again the newest build from Actions page.

**Comment by montlikadani** [comment]
Did you tried to move `color` property before `with`? `["",{"translate":"SomeTextToReplace","color":"green","with":[{"text":"test123","color":"red"}]}] `
