### ISSUE TITLE
Very big lag spikes when using PlaceholderAPI on the latest build from Artifacts or source code

### ISSUE THREAD

**Issue by sasha066** [montlikadani/TabList#345]
### Type of bug

Performance loss or memory leak

### TabList version

5.6.2 (latest artifact with JSON support)

### Software version

Purpur-1614 (MC: 1.18.2)

### Relevant plugins

PlaceholderAPI

### Console error (if applicable)

There are no errors in the console.

### TabList configuration files

It does not matter, the problem is present even with default configs.

### Bug description

I started testing the plugin after you added JSON support to it and noticed that when 8 or more players join the server, very strange problems begin. TAB starts flickering as if the sorting is completely broken, players' nicknames randomly move through the list every tick. But besides this, very strong lags begin, TPS starts to drop up to 1-2, and sometimes the ping rises very much (despite the fact that I tested this on a local server, the ping rose to 7000 and above. :D). I went through all my plugins and found that the problem only appears when using the PlaceholderAPI. If you remove PAPI or disable its hook in config.yml, then the problem disappears.

(To replicate this issue without using live people, you can set online-mode to false and use the Minecraft Console Client to add the required number of players to the server https://github.com/MCCTeam/Minecraft-Console-Client)

**Comment by montlikadani** [comment]
Please include Spark and timings reports.

**Comment by montlikadani** [comment]
Sorting of groups is still not works, https://github.com/montlikadani/TabList/issues/339 (I don't have any idea how to fix it)

**Comment by montlikadani** [comment]
Both tab plugins use the same procedure similarly, it only works there, not here at TL and I haven't been able to figure it out since.

The above commit you confirmed now works, so this issue closed
