### ISSUE TITLE
rank demote does not update tablist

### ISSUE THREAD

**Issue by Cruwzky** [montlikadani/TabList#347]
### Type of bug

Other

### TabList version

5.6.2

### Software version

This server is running Paper version git-Paper-340 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: ed4e916) You are 10 version(s) behind Download the new version at: https://papermc.io/downloads Previous version: git-Paper-333 (MC: 1.18.2)

### Relevant plugins

Luckyperms
Essentials
EssentialsChat

### Console error (if applicable)

No console error

### TabList configuration files

Config: https://paste.gg/p/anonymous/84e20f8ec0684f03bceecb9b5982cd3b
Groups: https://paste.gg/p/anonymous/479d45a59ad94cae92911620978e066d
tablist: https://paste.gg/p/anonymous/7faa53fec2c3445fa47561b2877b5eea

### Bug description

If I do "/lp user playername promote trackname" with LuckyPerms it promotes the user to the next rank in that track. This works and the user is promoted to the new rank. The tablist updates immediately, so this is fine.

If I however do the opposite with "/lp user playername demote trackname" again the user is deranked and this works fine, but the tablist does not update. The only way to get the tablist updated is doing a "/tablist reload" or making the user relog.

Is this a bug or am I doing something wrong?

**Comment by montlikadani** [comment]
Try with the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page. Select the first one and find Artifacts

**Comment by Cruwzky** [comment]
> Try with the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page. Select the first one and find Artifacts

This build does solve the issue. Thanks!
