### ISSUE TITLE
Per world tablist does not show per player placeholders

### ISSUE THREAD

**Issue by Cruwzky** [montlikadani/TabList#348]
### Type of bug

Other

### TabList version

TabList version 5.6.2

### Software version

Current: git-Purpur-1628 (MC: 1.18.2)* Previous: git-Paper-350 (MC: 1.18.2) * You are 3 version(s) behind Download the new version at: https://purpurmc.org/downloads

### Console error (if applicable)

There is no console error

### TabList configuration files

https://paste.gg/p/anonymous/dedcbcbd8a1e44959e5997b5ebc00ddd

### Bug description

If you use example the following placerholders in a per world tablist %autorank_total_time_of_player_formatted% or
%statistic_time_played% it shows the time played for the first person that join that world. If that first person leaves that world, it shows the next person in lines playtime.

If you use these placeholders in a not per world tablist it works as intended.

**Comment by montlikadani** [comment]
Any screenshot?

**Comment by Cruwzky** [comment]
I have created a short video showing it, also here is my tablist.yml file: 

https://www.youtube.com/watch?v=Nv0VuRpo3ww
https://paste.gg/p/anonymous/acfc4153edb14c89b166628e1652d8c3

**Comment by montlikadani** [comment]
This doesn't seem tablist's issue, most likely that 2 different plugin, if I saw correctly `playtime` command coming from essentials and that placeholder from autorank or statistic. I can't do anything as those placeholders coming from PlaceholderAPI.

**Comment by Cruwzky** [comment]
I'm pretty sure this has nothing to do with the PAPI placeholders.

If I for example use the built-in placerholder %player% on a per world tablist the same issue is present. It shows the value from the first player in the world. Which means all the rest are seeing the playername for that first player and not their own.

It is only in a per world tablist this happens. I have tried with a clean papermc 1.18.2 server and a clean default tablist configuration with no other plugin than TabList version 5.6.2 and it's the same issue. So I believe there is a bug with this feature.

![2022-06-05_14 17 13](https://user-images.githubusercontent.com/20445289/172050003-0a5b6ccf-c672-4dba-a9d6-82e95b9aa774.png)

![2022-06-05_14 17 08](https://user-images.githubusercontent.com/20445289/172050009-65b37ef8-61fc-495e-911d-f4cd9812fe6b.png)

`per-world:
  world:
    header: "%anim:perWorld%"
    footer:
    - "&6World:&7 %world%"
    - "%player%"`

**Comment by montlikadani** [comment]
The above attached commit will fixes this issue. You can test it by installing the newest build from [Actions](https://github.com/montlikadani/TabList/actions) page, select the first one and find Artifacts.
