### ISSUE TITLE
Unhandled exception occurred in onPacketSending(PacketEvent) for TabList

### ISSUE THREAD

**Issue by Madscience763** [montlikadani/TabList#349]
### Type of bug

Error in console

### TabList version

5.6.2

### Software version

MultiPaper-1.18.2-70

### Relevant plugins

Protocollib
PlaceholderApi
Playtimes-1.4.6

### Console error (if applicable)

https://pastebin.com/gEgBNTB0

### TabList configuration files

[TabList.zip](https://github.com/montlikadani/TabList/files/8883787/TabList.zip)

### Bug description

Tablist breaks when using the latest release dev of protocollib

**Comment by montlikadani** [comment]
Doesn't seem like TabList's issue, TL's code does not contain any `world.entity.player.ProfilePublicKey` or at least I don't think I can do anything with this.

**Comment by Madscience763** [comment]
It worked fine before. It seems to be an issue with the dev protocollib
