### ISSUE TITLE
Player groups no longer displayed as of v1.19

### ISSUE THREAD

**Issue by MihaiChirculete** [montlikadani/TabList#350]
### Type of bug

Compatibility issue

### TabList version

5.6.2

### Software version

1.19-R0.1-SNAPSHOT

### Relevant plugins

Relevant plugins: 
- Vault
- EssentialsX-Core
- LuckPerms

### Console error (if applicable)

https://paste.gg/p/anonymous/f384eb60db644ad5881d1e7f605f09aa/files/a26c5aefa5f940cf8d91f6529756d77e/raw

### TabList configuration files

[tablist_configs.zip](https://github.com/montlikadani/TabList/files/8884125/tablist_configs.zip)

### Bug description

Previously, in v1.18.2 I used this plugin to display player names right next to the group that the player belonged to. As of version 1.19 this is no longer working.

The player list contains all the player names and all the other data except the player groups. It also spams the console with the error attached.

**Comment by montlikadani** [comment]
Install newest version from [Actions](https://github.com/montlikadani/TabList/actions) page, select first one and find Artifacts.

**Comment by MihaiChirculete** [comment]
That seems to have fixed it. Thank you for your quick reply!

I'll close this issue since it doesn't reproduce anymore on the latest dev build.

**Comment by montlikadani** [comment]
Official release of TabList is out.
