### ISSUE TITLE
sort not work well

### ISSUE THREAD

**Issue by Ofek270704** [montlikadani/TabList#354]
### Type of bug

Other

### TabList version

5.6.3

### Software version

This server is running Paper version git-Paper-"87e11bf" (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 87e11bf) You are 272 version(s) behind Download the new version at: https://papermc.io/downloads

### TabList configuration files

groups.yml
https://paste.gg/p/anonymous/8a94ac022c7d4aaf877f799b9be4d827

### Bug description

tab sort does not work when I sort the groups.yml after reloading its works great but after a few minutes, all the groups and names are randomized. (I am using luckperms)

![image](https://user-images.githubusercontent.com/67981835/174607483-c13fa759-e8fd-4698-b874-7f03ee9bc401.png)

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/issues/339
