### ISSUE TITLE
 Could not load 'plugins/TabList-bukkit-5.6.3.jar' in folder 'plugins

### ISSUE THREAD

**Issue by mohsinalam91** [montlikadani/TabList#357]
### Type of bug

Error in console

### TabList version

5.6.3

### Software version

v1_19_R1

### Console error (if applicable)

[17:13:34 ERROR]: Could not load 'plugins/TabList-bukkit-5.6.3.jar' in folder 'plugins'

### TabList configuration files

[config.zip](https://github.com/montlikadani/TabList/files/9094424/config.zip)

### Bug description

not working

**Comment by montlikadani** [comment]
You literally replaced one of the other tablist plugin's config with this one.
