### ISSUE TITLE
Prefix version name with v 

### ISSUE THREAD

**Issue by ghost** [montlikadani/TabList#361]
### Description

I have a plugin to remind me to update plugins which checks the EXACT version string.
Since the version is not prefixed with v it reminds me even though it is up-to-date.
![image](https://user-images.githubusercontent.com/97077949/185736207-286ce55b-6953-439d-a408-5c64818a559f.png)

**Comment by montlikadani** [comment]
You're probably using the version string from plugin.yml which does not contain the v prefix before version. If you have owning that discord bot then you can change the returning value. I am not going to break the version checking with this change.

**Comment by montlikadani** [comment]
Why should I change that? If you own your discord bot then why?
