### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by lun4rr** [montlikadani/TabList#362]
### Type of bug

Other

### TabList version

TabList version 5.6.4 An ultimate animated tablist Author: monthlikadani

### Software version

This server is running Mohist version 1.18.2 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.73)

### TabList configuration files

they are normal settings

### Bug description

I mean the settings Are normal i havent changed anything and it doesnt work on mohist 1.18,2

**Comment by montlikadani** [comment]
Forge/Modified server is not supported.
