### ISSUE TITLE
Bukkit, Players Skins Disappear when using Hide Players in Tablist

### ISSUE THREAD

**Issue by B10nd1e** [montlikadani/TabList#363]
### Type of bug

Other

### TabList version

5.6.4-Bukkit

### Software version

git-Paper-"df630a2" (MC: 1.18.2)

### Relevant plugins

Chairs, ChatColor2*, CheckPoints, Citizens, DiscordSRV, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, LuckPerms, MiniBlocks, MobHeads, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, PlaceholderAPI, ProtocolLib, ProtocolSupport, RealScoreboard, SitEverywhere, TabList, Vault, WorldEdit

### TabList configuration files

https://paste.gg/p/anonymous/7e7433f3cd7a47e889aeb4c655227ac0

### Bug description

Whenever I try to remove players from Tablist, `hide-players-from-tablist: true` whenever a player goes into a different world, there skin Disappears, as well as sometimes the players disappear as well. I do have ProtocolLib installed, I was wondering if there was a fix for this, something that I have to change in code/another plugin I need, or if there is a bug for this version.

I am trying to find a plugin that is supported in 1.18.2, to remove players from Tablist. I am trying to create my own TabList using headers and footers, only, as I think it is more visually appealing. It is for a multiplayer event, in which the version, and I cant use the Bungee version

**Comment by montlikadani** [comment]
Which of the ProtocolLib version are you using?

**Comment by B10nd1e** [comment]
> Which of the ProtocolLib version are you using?

v4.8.0

**Comment by B10nd1e** [comment]
Bump

**Comment by montlikadani** [comment]
After some investigation and refactoring I think I managed to fix this issue, you can test with the newest build from [Actions](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml) page, select the first one and find artifacts. In this archive you can install the bukkit version of tablist.

**Comment by montlikadani** [comment]
Is this still reproducible with the newest v5.6.7 version of tablist?

**Comment by montlikadani** [comment]
Closing due to lack of response
