### ISSUE TITLE
CONSOLE ERROR

### ISSUE THREAD

**Issue by Xosmuits** [montlikadani/TabList#38]
My console is full of with these:
https://hastebin.com/wazaqobame.vbs

**Comment by montlikadani** [comment]
**Thank you for the reporting it!**
Can you tell me that when the footer was still text, did this bug throw in the console?

**Comment by montlikadani** [comment]
Please test this version, this bug has been fixed and I tested it: http://www.mediafire.com/file/pnb20nrdxkd014s/TabList+Test.jar

**Comment by Xosmuits** [comment]
Thank you, it seems fixed rn. I'll let you know for further errors.

**Comment by montlikadani** [comment]
Wow.. Unfortunately, one or two errors are still in it, but it's already fixed, so it's up to date.

**Comment by montlikadani** [comment]
**_This bug has been fixed in this version:_** https://www.mc-market.org/resources/6127/update?update=16137
