### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by NopeProsOnly** [montlikadani/TabList#380]
### Type of bug

Console Error

### TabList version

TabList version 5.6.8

### Software version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### Relevant plugins

`AltDetector`, `AntiHealthIndicator`, `AutoMessage`, `BedWars`, `BetterRTP`, `BetterTeams`, `BlueSlimeCore (SirBlobmanAPI, SirBlobmanCore, XSeries)`, `BotSentry`, `Citizens`, `CombatLogX`, `CommandNPC*`, `ConnectFour`, `DiscordSRV`, `DiSky`, `Duels`, `EasterEggs`, `EconomyShopGUI`, `FastAsyncWorldEdit (WorldEdit)`, `FlyPlus`, `Frozen*`, `GSit`, `HideAndSeek`, `ImageFrame`, `InvSeePlusPlus`, `JoinProtection`, `LANBroadcaster`, `LibsDisguises`, `LuckPerms`, `Multiverse-Core`, `Multiverse-Inventories`, `Multiverse-NetherPortals`, `Multiverse-Portals`, `Negativity`, `Oneblock`, `OpeNLogin`, `Orebfuscator`, `Panilla`, `PhysicsControl`, `PlaceholderAPI`, `PlotSquared`, `ProtocolLib`, `RedstoneClockDetector*`, `SBA`, `SetHomes`, `SimpleTpa*`, `SkBee`, `SkinsRestorer`, `SkQuery`, `Skript`, `skript-fishing`, `skript-gui`, `skript-reflect`, `spark`, `SpawnTeleport`, `StackMob`, `Sudo*`, `SuperVanish`, `TabList`, `TNTRun_reloaded`, `UltimateAutoRestart`, `Vault`, `ViaBackwards`, `ViaVersion`, `ViaVersionStatus`, `VoidGen`, `WorldGuard`, `XConomy`

### Console error (if applicable)

https://paste.gg/p/anonymous/6632558ac60842d3b52ac4e9922a8cb7

### TabList configuration files

https://paste.gg/p/anonymous/7428a3f7d2c34ab2bc70c8efac6cde8d

### Bug description

Player legit just changed world, it made this error...

**Comment by NopeProsOnly** [comment]
Why is this closed?

**Comment by NopeProsOnly** [comment]
Ah you made a new commit. Ok. When is the next release?

**Comment by montlikadani** [comment]
Look at the attached commit. It is fixed, you can test it by downloading the newest build from [Actions](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml) page, select the first one and find Artifacts.

**Comment by NopeProsOnly** [comment]
My bad. I checked the closed issues then realized I had already made one.
