### ISSUE TITLE
Adding Bungeecord Premium Vanish support

### ISSUE THREAD

**Issue by Novasky-Guy** [montlikadani/TabList#392]
### Description

Premium Vanish recently added Bungeecord support to their plugin, this includes hiding players from the tablist. 
it would be awesome if its possible for Tablist to also support this so that you can hide players from the tablist globally.

**Comment by montlikadani** [comment]
You specifically want to hide vanished players from online players count not from the server globally. Vanish plugin should hide players globally, which is not done through the tablist plugin.

**Comment by Novasky-Guy** [comment]
Apologies, i did mean from the server globally, just realized i phrased it wrong.
