### ISSUE TITLE
'Chat message validation failure' with hidden tablist players on 1.19.1+

### ISSUE THREAD

**Issue by GoracioNewport** [montlikadani/TabList#394]
### Type of bug

Compatibility issue

### TabList version

5.6.8

### Software version

This server is running Paper version git-Paper-446 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4e99466)

### Relevant plugins

LuckPerms, PlaceholderAPI

### TabList configuration files

https://paste.gg/p/anonymous/9b422b4e3cf74d42a1ecc75b299e9759

### Bug description

**How to reproduce:** 

1. Set `hide-players-from-tablist` option to true.
2. Login to server. Your player skin will be set to default like it's an offline mode server (but it's not).
3. Type any message to chat. You will get kicked instantly with this message: 'Chat message validation failure'

This issue is probably somehow related to new chat reporting feature introduced in 1.19.1, I tested the same plugin version and configuration on 1.18.2 and expierenced no issues.

**Comment by AlexOberfranc** [comment]
i am getting an issue with 1.19.4 as well

**Comment by montlikadani** [comment]
The above attached commit fixes this issue

**Comment by montlikadani** [comment]
> When I hide players from tablist, I can't see my skin anymore. Even with SkinsRestorer, even in offline mode.
> It just reverts to default Alex skin.

Please make a new issue for this
