### ISSUE TITLE
Issue with seeing other players prefixes

### ISSUE THREAD

**Issue by CD123XD** [montlikadani/TabList#40]
Hi there! I installed this plugin about a month ago on my spigot server a month ago and everything was fine. I upgraded to bungee a week later and it still was working fine. Then a week later the prefixes were acting funny. Other players could see their own prefixes next to their name in the tab, but they couldn't see other players prefixes. I have included an attachment of my prefix in the game, but all the others have none. However, when you get an advancement, the prefix pops up next to your name.
[image](https://user-images.githubusercontent.com/37460813/43209621-02635096-9025-11e8-8ed6-7c4debaa8cfc.png)
 I have configured the permissions correctly and I will include all the plugins I have installed if nessessary. Thanks for looking at this!

**Comment by montlikadani** [comment]
Are you using a scoreboard plugin?

**Comment by CD123XD** [comment]
Yes I am. I'm using the [animated scoreboard plugin](https://www.spigotmc.org/resources/animatedscoreboard.20848/) by JasperJH.

**Comment by montlikadani** [comment]
Did you try without AnimatedScoreboard?

**Comment by CD123XD** [comment]
Yep. Just tried that but now we have no prefixes. Just blank names now.

**Comment by montlikadani** [comment]
Are you using the latest version?

**Comment by CD123XD** [comment]
Yeah, I updated a couple of hours ago

**Comment by montlikadani** [comment]
Now I ask such basic questions.
Try to run the _/tl reload_ command.

**Comment by CD123XD** [comment]
Tried it. Didn't work

**Comment by montlikadani** [comment]
Soon an update will come and then testing whether it works or not because I've made some minor fixes in the plugin.

**Comment by montlikadani** [comment]
**Try updating to the latest version.**

**Comment by CD123XD** [comment]
Sorry for the slow reply! I have updated to the latest version (3.0) and configured it again. It has seemed to fix the issue when I removed the scoreboard, but other players still cannot see your rank in the tablist. The user Wirelli should have a member prefix, which he does on his screen. If you need anymore information, I'll be glad to provide it! 
![onpaste 20180802-224023](https://user-images.githubusercontent.com/37460813/43612741-2aac8000-96a5-11e8-84e3-d3697cc69b7c.png)

**Comment by montlikadani** [comment]
I can not help much more.
Try to change them, which are in the comments in types or other:
https://github.com/montlikadani/TabList/blob/master/config.yml#L61
https://github.com/montlikadani/TabList/blob/master/config.yml#L63
https://github.com/montlikadani/TabList/blob/master/config.yml#L68

**Comment by CD123XD** [comment]
That's okay! I'll experiment with the plugin on a test server. I'll add each one of my plugins one by one to find which one is breaking the Tablist. Thanks for trying to help me out!

**Comment by montlikadani** [comment]
You're welcome, but it works for me and other users, but not for you. And I do not know what the problem is. Test it calmly.

**Comment by CD123XD** [comment]
Hello again! I experimented for a bit and used different plugins. It turns out, the prefix data was a little scattered across all plugins as they all use it. So I used a different permissions plugin and redid the configuration a bit. It now works, but thank you for trying to help me out!
