### ISSUE TITLE
Issues w/ showing health and showing vanished players

### ISSUE THREAD

**Issue by PacketL0st** [montlikadani/TabList#401]
### Type of bug

Other

### TabList version

5.6.8

### Software version

[01:35:20 INFO]: This server is running Paper version git-Paper-388 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 57f1157)

### TabList configuration files

https://paste.gg/p/anonymous/6546e541139f47a2853f3602a2191575

### Bug description

I cannot get my player to disappear from the tablist even with supervanish and enabling the right perms. Also, health only updates when you die. I am trying to make it update more often as I'm trying to make it update as people withdraw hearts, etc. Is there any way to do this?

**Comment by montlikadani** [comment]
Player health should be updated every time the hearth changes. Also to hide vanished player the vanish plugin should do/handle that by default.

**Comment by PacketL0st** [comment]
Shows 0 players online but my name is still there: https://i.imgur.com/1TO6Fjn.png
I tried configuring it in the tablist settings, not sure if I'm doing something wrong?

**Comment by montlikadani** [comment]
If you have enabled `ignore-vanished-players-in-online-players` in config then its inteded behaviour

**Comment by PacketL0st** [comment]
Okay, thank you
