### ISSUE TITLE
No skins with hidden tablist players

### ISSUE THREAD

**Issue by GoracioNewport** [montlikadani/TabList#402]
### Type of bug

Compatibility issue

### TabList version

5.7.0

### Software version

This server is running Paper version git-Paper-446 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4e99466)

### Relevant plugins

LuckPerms, PlaceholderAPI

### TabList configuration files

https://paste.gg/p/anonymous/9b422b4e3cf74d42a1ecc75b299e9759

### Bug description

**How to reproduce:**

1) Set `hide-players-from-tablist` option to true.
2) Login to server. Your player skin will be set to default like it's an offline mode server (but it's not).

SkinsRestorer doesn't work, if you try to apply some skin you'll get a success message but nothing will happen.

**Comment by GoracioNewport** [comment]
I have just made an intersting discovery.
You get your skin back, if you change your gamemode.

**Comment by montlikadani** [comment]
I made an attempt to fix this but I am unsure this will work, you try with this build from [Actions](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml)
