### ISSUE TITLE
Tablist still counts vanished players in the %staff-online% placeholder

### ISSUE THREAD

**Issue by HailyAdi** [montlikadani/TabList#406]
### Type of bug

Other

### TabList version

5.7.0

### Software version

Papeer 1.19.4

### Relevant plugins

![image](https://user-images.githubusercontent.com/57846332/233774963-2bbcd432-b8e5-4ed5-8667-934c9286e679.png)

### Console error (if applicable)

Nope

### TabList configuration files

https://paste.gg/p/anonymous/8109697f11454accaef4d6dc08bbc681

### Bug description

I'm using stafffacilities and after someone uses /vanish or /staffvanish they will dissapear from tab but the api still counts them.

**Comment by montlikadani** [comment]
Its probably an issue with StaffFacilities API, because it works from Essentials
