### ISSUE TITLE
Players in spectator are still grayed/italic 

### ISSUE THREAD

**Issue by QarthO** [montlikadani/TabList#407]
### Type of bug

Performance loss or memory leak

### TabList version

5.7.0

### Software version

This server is running Paper version git-Paper-514 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: dd216c1) You are 4 version(s) behind Download the new version at: https://papermc.io/downloads/paper Previous version: git-Paper-499 (MC: 1.19.4)

### TabList configuration files

https://paste.gg/p/anonymous/5e9685ff807541b69722d76e750c92ee

### Bug description

Even with ``remove-gray-color-from-tab-in-spectator: true`` people in the spectator gamemode are still grayed out.

Yes I understand this only affects other players' tablists not the player who is in spectator.

The following screenshot is from the player SebastianQM. He is not OP, nor has any tablist permissions.
![image](https://user-images.githubusercontent.com/10179096/233827186-7dab0006-db2a-4766-834e-18cb062e8f9a.png)

**Comment by PokeDerg** [comment]
Same problem

**Comment by montlikadani** [comment]
The above attached commit hopefully fixes this issue.
