### ISSUE TITLE
Players may not appear on the screen if they are hidden in the tab list

### ISSUE THREAD

**Issue by GoracioNewport** [montlikadani/TabList#408]
### Type of bug

Compatibility issue

### TabList version

5.7.0

### Software version

This server is running Paper version git-Paper-446 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4e99466)

### Relevant plugins

LuckPerms, PlaceholderAPI

### TabList configuration files

https://paste.gg/p/anonymous/9b422b4e3cf74d42a1ecc75b299e9759

### Bug description

How to reproduce:

* Set `hide-players-from-tablist` option to true.
* Login to server from accout A. 
* Login to server from accout B, somewhere away from A, so you won't see their nametag
* Approach accout A from accout B. There will be no player and you wouldn't be able to see player A. However, players A sees you clearly

`hide-players-from-tablist` is quite a buggy feature, I see... :)

**Comment by montlikadani** [comment]
Above attached commit fixes it, hopefully, download build [here](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml)
