### ISSUE TITLE
Scoreboard Team color resets when using TabList plugin

### ISSUE THREAD

**Issue by GoracioNewport** [montlikadani/TabList#409]
### Type of bug

Other

### TabList version

5.7.0

### Software version

This server is running Paper version git-Paper-446 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4e99466)

### Relevant plugins

LuckPerms, PlaceholderAPI

### TabList configuration files

https://paste.gg/p/anonymous/9b422b4e3cf74d42a1ecc75b299e9759

### Bug description

How to reproduce:

* Create a team from console or from another plugin, add a player to it
* Set team's color to something other that white
* Join the server. Your color will be displayed correctly for a couple of ticks, then it will revert back to white
* This affects player glowing outlite color, player nametag color, but not color in chat or tablsit for some reason

**Comment by montlikadani** [comment]
This is an issue with the groups, you can test it out without using them by disabling `change-prefix-suffix-in-tablist`

**Comment by montlikadani** [comment]
I've made a temporary solution to fix this issue, download latest build from Actions page
