### ISSUE TITLE
URGENTLY. Nickname color depending on the world.

### ISSUE THREAD

**Issue by MrDenny4** [montlikadani/TabList#413]
### Description

URGENT!) I need help with the config. I want to make it so that when in the "WORLD" world, the nickname in TAB would be with the GREEN WORLD prefix. In the world "WORLD_NETHER" the color was DARK RED and so on. How to do it?

**Comment by MrDenny4** [comment]
I know how groups work and that you can SIMPLY change the color of the world there, but I need a color that is tied to the world.

I repeat once again, if the world is "WORLD" then the nickname is green (for example)
If the world is "WORLD_NETHER" then the nickname is red

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/wiki/Per-world-groups
