### ISSUE TITLE
Add a global playerlist to the Bungeecord version.

### ISSUE THREAD

**Issue by darealblack** [montlikadani/TabList#416]
### Description

Add a feature where you can set it so you can see all players connected to the whole proxy/server.

**Comment by montlikadani** [comment]
Bungeecord already have this option, see [bungee configuration](https://www.spigotmc.org/wiki/bungeecord-configuration-guide/) -> global playerlist

**Comment by darealblack** [comment]
It doesnt, even with having it on it doesn't show all players. Im on 1.19.
![image](https://github.com/montlikadani/TabList/assets/79378716/4ac2baaf-bb47-4765-a91b-93701d5560df)
@montlikadani 
Also your plugin doesn't work with global

**Comment by darealblack** [comment]
Note - Because BungeeCord 1.8+ use the new tablist, you are advised to use the plugin GlobalTablist or BungeeTabListPlus to have this feature in 1.8+.
@montlikadani

**Comment by montlikadani** [comment]
> Note - Because BungeeCord 1.8+ use the new tablist, you are advised to use the plugin GlobalTablist or BungeeTabListPlus to have this feature in 1.8+. @montlikadani

Pretty obvious what you need to use
