### ISSUE TITLE
Tablist not sorting players correctly

### ISSUE THREAD

**Issue by Conrad3k** [montlikadani/TabList#425]
### Type of bug

Other

### TabList version

5.7.0

### Software version

This server is running CraftBukkit version 3763-Spigot-7d7b241-5a5e43e (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)

### Relevant plugins

BetterPrefix

### Bug description

The Tablist sorts players wrongly. I have all the roles set, for example the owner having the highest priority, but despite that when a player with a letter in the beginning of the nickname joins, he is shown at the top of the tablist. I tried different name tag formatting plugins, but they do not seem to be causing the issue.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/issues/339

**Comment by Conrad3k** [comment]
Updated to newest version - still does not work.
