### ISSUE TITLE
Players disappearing from world when hide-players-from-tablist is set to true

### ISSUE THREAD

**Issue by iamkoldun** [montlikadani/TabList#427]
### Type of bug

Other

### TabList version

5.7.3

### Software version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4) You are running the latest version Previous version: git-Paper-130 (MC: 1.19.2)

### Relevant plugins

Only TabList is installed on my server

### Console error (if applicable)

Console is clear

### TabList configuration files

My config is totally default, except hide-players-from-tablist: true, anyway https://paste.gg/p/anonymous/f316df4ad53a45f58544fe3efbc93da8

### Bug description

When I use the feature of hiding players from the tab, players disappear in the world.

Steps to reproduce:
1) Two players are facing each other
2) One of the players flies far enough to unload from the other's screen
3) The player goes back
4) One of the players does not see the other (random of them)

**Comment by montlikadani** [comment]
This feature has been removed, because of the unfixable issues, see the attached commit description for more
