### ISSUE TITLE
console spaming a lot of time [WARN] message,but it is not ERROR

### ISSUE THREAD

**Issue by qaz13570111** [montlikadani/TabList#43]
it spaming [WARN] message in console and Unstoppable
![1](https://user-images.githubusercontent.com/35308267/44231232-fe352c80-a1cf-11e8-80f5-e75da1cc4e86.jpg)

and this is my in game tablist,it looks normal and good
![2018-08-17_03 47 33](https://user-images.githubusercontent.com/35308267/44231319-50764d80-a1d0-11e8-8980-b4b5f6f207b8.png)

and this is my config file setting
![a](https://user-images.githubusercontent.com/35308267/44231467-d72b2a80-a1d0-11e8-8c68-a78c4099494b.jpg)
![b](https://user-images.githubusercontent.com/35308267/44231471-d98d8480-a1d0-11e8-9ee7-4d3703608ac5.jpg)
![c](https://user-images.githubusercontent.com/35308267/44231474-db574800-a1d0-11e8-99a8-1bd43ddb2aab.jpg)
![d](https://user-images.githubusercontent.com/35308267/44231475-dc887500-a1d0-11e8-8425-ec8ad06a5cf9.jpg)
![e](https://user-images.githubusercontent.com/35308267/44231476-ddb9a200-a1d0-11e8-8748-1e6ca8f59003.jpg)

my server version: SPIGOT-1.12.2

please help my fix this bug,its very annoying
sorry for my poor english

my Tablist version are Newest (3.0)

**Comment by montlikadani** [comment]
I've found this bug and fixed it, so it will be visible in the next version.

**Comment by montlikadani** [comment]
_**This bug has been fixed in this version:** https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=239769_
