### ISSUE TITLE
Tablist sorting & custom object type

### ISSUE THREAD

**Issue by domzan** [montlikadani/TabList#430]
### Type of bug

Others issue

### TabList version

5.7.3.

### Software version

Paper version git-Paper-18 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 2e363c7)

### Relevant plugins

 AnimatedScoreboard, AuthMe, Citizens, CMI, CMILib, CoreProtect, DeluxeMenus, DiscordSRV, **LuckPerms**, MOTD, Multiverse-Core, Negativity, PhoenixCrates, PlaceholderAPI, Residence, Shopkeepers, **TabList**, Vault, *VoidGenerator, VoidSpawn, WorldEdit

### Console error (if applicable)

none

### TabList configuration files

https://paste.gg/p/anonymous/e87f2210eca546eba310209ac299506b

### Bug description

Tablist sorting via luckperms weight doesn't work - idk why, every group in luckperms have own weight
When I added sort-priority → still doesn't work

The next issue: I have custom object type → I set cmi placeholder, and when I log later than other players I cant see their values (see only 0)

**Comment by CammiePone** [comment]
I'm also having an issue with sort-priority not working. I'm using GroupManager myself, but still can't get a consistent tab list, regardless of groups

My view:
![2023-08-11_06 22 41](https://github.com/montlikadani/TabList/assets/16853086/c49df2e3-24dc-4b9a-b17c-36f2cf987884)

My partner's view:
![image](https://github.com/montlikadani/TabList/assets/16853086/159c86ad-19c4-4bc6-9e4c-ddcfb76c2128)

groups.yml:
![image](https://github.com/montlikadani/TabList/assets/16853086/566024e5-638c-4a71-9694-314af3994a1c)

**Comment by Patbun** [comment]
I'm also having the same issue.

**Comment by Darth-Sicaedus** [comment]
It is a known issue.

**Comment by Blandix** [comment]
Any update on this?

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/e3d8ee0a244cd9a654523f12a1f64138647b1596

Hopefully this fixes the sorting issue. I am reopening this issue if someone interested in testing this. The build is available on [Actions](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml) page, select the first one and find Artifacts.

**Comment by Patbun** [comment]
Hi, thank you for trying to sort the issue. It's completely broken tab now and is spamming console. 

![image](https://github.com/montlikadani/TabList/assets/142102174/525d2aaa-8bbd-4389-a3b8-b7bd5bef32aa)

[https://pastebin.com/LWYN27MT](url)

**Comment by montlikadani** [comment]
You probably have paper 1.20 version instead of 1.20.2, so it can't recognise it properly, but I pushed a fix again

**Comment by Patbun** [comment]
Yes you’re correct I’m on paper 1.20. Will this build be compatible with paper 1.20 or will I have to update to 1.20.2? Many thanks again.

**Comment by montlikadani** [comment]
It will be compatible with this build

**Comment by Patbun** [comment]
The build worked perfectly. Thank you so very much!

**Comment by montlikadani** [comment]
Is the sorting issue also fixed?

**Comment by Patbun** [comment]
Yes this is fixed, sorry should have stated that. Great work! Appreciate it
