### ISSUE TITLE
Folia Issues (after tps update i think)

### ISSUE THREAD

**Issue by f3f5-dev** [montlikadani/TabList#431]
### Type of bug

General issue

### TabList version

last from actions tps for folia

### Software version

folia last dev-commit

### Relevant plugins

only tablist

### Console error (if applicable)

https://pastes.dev/KrQ9c6wHCE

### TabList configuration files

default 

### Bug description

join to server

**Comment by montlikadani** [comment]
The above attached commit will fixes this issue
