### ISSUE TITLE
Memory Bar not working

### ISSUE THREAD

**Issue by KurtchenTheFur** [montlikadani/TabList#438]
### Type of bug

General issue

### TabList version

5.7.3

### Software version

This server is running Paper version git-Paper-102 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 13c9d3c) You are 1 version(s) behind Download the new version at: https://papermc.io/downloads/paper Previous version: git-Paper-70 (MC: 1.19)

### Relevant plugins

Server Plugins (32) Bukkit Plugins:
BetterRTP, ChestShop, CMILib, CoreProtect, DecentHolograms, *DisableWither, DiscordSRV, dynmap, Essentials, EssentialsChat
EssentialsSpawn, FarmProtect, GSit, HeadDatabase, JumpPads, LogBlock, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals
MyCommand, OpenInv, PlotSquared, SkQuery, Slap-Pro, SuperiorSkyblock2, SuperVanish, TabList, TNTRun_reloaded, Vault
WorldEdit, WorldGuard

### TabList configuration files

https://paste.gg/p/anonymous/3a8a0ecd2f29495eb64490647b5e5f27

### Bug description

Heya!
Not sure if im just to dumb to configure it, but after updating from 1.19 to 1.20.1 something broke.

I use in my tablist %memory_bar%, but this doesnt show me anymore any bar and just states "%memory_bar%" if i press Tab.
Trying to place it at a different location or with spaces around it didnt work.

Is there maybe something else wrong?

Thank you!

**Comment by montlikadani** [comment]
`%memory_bar%` variable was removed in v5.6.9, it was unused and it lack of customization

**Comment by KurtchenTheFur** [comment]
Ahh thank you!
I missed that. Thank you!
