### ISSUE TITLE
Tab not loading after updating server to 1.20.1 and a plugin update 

### ISSUE THREAD

**Issue by alex4926** [montlikadani/TabList#442]
### Type of bug

General issue

### TabList version

5.7.3

### Software version

This server is running Paper version git-Paper-119 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3b4839e) You are running the latest version Previous version: git-Paper-102 (MC: 1.20.1)

### Relevant plugins

Advanced Bad, Coordinates Hud, Custom Join Messages, DeathChest, InvisibleitemFrames, LagMonitor, LuckPerms, PlaceholderAPI, PlayerKits, spark, tabList, TreeFeller

### Console error (if applicable)

https://mclo.gs/MtCAExy

### TabList configuration files

https://paste.gg/p/anonymous/b54d739f4860424f8f1a9363c273f254
i hope it works lol

### Bug description

after updating server to 1.20.1 and a plugin update it refused to load and was spamming in console with errors. I tried to reset the config folder and then it loaded but after modifying tablist.yml it just wouldn't work and it worked in version 1.19.4.

**Comment by montlikadani** [comment]
One of the placeholder from placeholderAPI is causing this error. I think it is the `%statistic_deaths%`

**Comment by alex4926** [comment]
wow that response was fast thanks

**Comment by alex4926** [comment]
I'll remove the placeholder and see what happens thanks.

**Comment by alex4926** [comment]
And is this a bug in the tab plugin or in the PlaceholderAPI plugin?

**Comment by alex4926** [comment]
Yup that fixed it... Thanks so much. <3

**Comment by montlikadani** [comment]
> And is this a bug in the tab plugin or in the PlaceholderAPI plugin?

It is coming from PlaceholderAPI as you can see
