### ISSUE TITLE
i just keep getting error in my console

### ISSUE THREAD

**Issue by miner666** [montlikadani/TabList#45]
### Describe the bug (required)
Understand what the problem is with the plugin.

### Plugin version (required)
Describe the plugin version you are using now.

### Console error (required)
> 
> Send the console error if you have it.
>

### Config.yml or other file
Send the config.yml or other file.
(required)
```
config.yml
```

(optional)
```
other file
```

### Screenshots (optional)
Send a few pictures of the problem if you can.

**Comment by montlikadani** [comment]
Console error, configuration, plugin version? **You need to add those who are there.**
