### ISSUE TITLE
[Question] Does TabList not allow editing the nametag above players heads?

### ISSUE THREAD

**Issue by baailey** [montlikadani/TabList#453]
### Description

title

**Comment by montlikadani** [comment]
No
![image](https://github.com/montlikadani/TabList/assets/30026208/2a2a5f47-5e7a-4419-89c7-279bc0c2ab79)

**Comment by baailey** [comment]
rip, do you have any recommendations to allow modifying the nametag along with your plugin?

**Comment by montlikadani** [comment]
NameTagEdit

**Comment by baailey** [comment]
alright, thanks
