### ISSUE TITLE
Minecraft scoreboard global issue

### ISSUE THREAD

**Issue by KeyKatyu** [montlikadani/TabList#457]
### Type of bug

General issue

### TabList version

v5.7.4

### Software version

This server is running Paper version git-Paper-234 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: f613437) You are running the latest version Previous version: git-Paper-196 (MC: 1.20.1)

### TabList configuration files

https://paste.gg/p/anonymous/d4be70497b9c435db68c17d003c86f6a

### Bug description

Hello,
There's a major bug in the latest 1.20.2 version.
This concerns the scoreboard. There's a bug concerning "prefixes" in scoreboards. You can't define a prefix, otherwise the client or all connected players will crash (server disconnection). I'm using the latest version of Paper (build #234).
This bug causes almost all the existing plugins to malfunction, but this can be reproduced in vanilla:

/scoreboard objectives add Test dummy {"text":"Test","color":"yellow"}
/scoreboard objectives setdisplay sidebar Test
/scoreboard players set PlayerName Test 15
/team add Test {"text":"Test","color":"blue"}
/team join Test PlayerName
/team modify Test prefix {"text":"Test","color":"blue"}

**Comment by montlikadani** [comment]
Is this TabList's issue at all?

**Comment by KeyKatyu** [comment]
Yeah, I removed all my plugins one by one and it's this one that caused the problem

**Comment by montlikadani** [comment]
Thanks for reporting this issue, the above attached commit fixes this issue.
