### ISSUE TITLE
Proxy lost connection (probably installation error)

### ISSUE THREAD

**Issue by Dtar380** [montlikadani/TabList#463]
### Type of bug

Other

### TabList version

v5.7.4

### Software version

git-Purpur-2082 (MC: 1.20.2)

### Relevant plugins

EconomyShopGUI, AFKPlus, AFKPlusBungee, AFKPlusEventCommands, Afkpluspapi, AFKPlusPrefix, AFKPlusReconnect, BungeeGuard, Chunky, Citizens, CMILib, CommandPanels, Essentials, EssentialsChat, EssentialsSpawn, Factions, Jobs, lightEconomy, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, MyCommand, PlaceholderAPI, RealMines, SkinsRestorer, sleep-most, spark, SternalBoard, TabList, Vault, VoidGen, WorldEdit, WorldGuard

### Console error (if applicable)

Dtar380 lost connection: Internal Exception: java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because the return value of "net.minecraft.network.protocol.game.PacketPlayOutScoreboardTeam.f()" is null

### TabList configuration files

[configs.zip](https://github.com/montlikadani/TabList/files/13195666/configs.zip)

### Bug description

Im running a bungeecord network so I've installed the bungeecord plugin in the bungeecord server and in the main server (where I want the custom tab list) ive installed both the bungeecord and the normal plugin, but when I install the plugin it starts to show this error when connecting. 
![Captura de pantalla 2023-10-28 133908](https://github.com/montlikadani/TabList/assets/58855510/b7e6248a-c068-4e1c-a141-9b92478fda88)
Every time I uninstall the plugin it goes back to normal so I guess that the error is from the plugin (probably mine related to installation process on bungeecord networks)

**Comment by montlikadani** [comment]
This issue has already been fixed in the [latest builds](https://github.com/montlikadani/TabList/actions/workflows/gradle.yml)

**Comment by Dtar380** [comment]
I have installed the last version of the plugin, what do I have to do?

**Comment by montlikadani** [comment]
Wait for the next release

**Comment by Dtar380** [comment]
And then for now I cannot use it, or is there any solution. (I add that the server is cracked because I have cracked minecraft, in case its relevant)

**Comment by montlikadani** [comment]
Click on the "latest builds" in my first message, select the first build "cleanup" and find Artifacts, download the item and install the jar into you servers.

**Comment by Dtar380** [comment]
I'll try that, if it works Ill text and close, anyways, thanks for the quick response

**Comment by Dtar380** [comment]
As a question, do I install the bungeecord one in both servers (bungee and purpur) or just in the bungee and the bukkit plugin just in the purpur server?

**Comment by montlikadani** [comment]
Bungee version of TabList only required if you want to display for all servers, Bukkit version only needed if you only have 1 server or without network. Bukkit version has more features than Bungee

**Comment by Dtar380** [comment]
It worked, thanks for solving the problem and the quick response
