### ISSUE TITLE
Sponge - API 7 Issue: Sorting doesn't work. 

### ISSUE THREAD

**Issue by SaveasRPC** [montlikadani/TabList#487]
### Type of bug

General issue

### TabList version

Sponge 1.0.5

### Software version

Forge 1.12.2

### TabList configuration files

groups {
    Ace {
        permission="tablist.ace"
        prefix="&f[&l&fA&l&dce&f]&r "
        priority=6
    }
    Apprentice {
        permission="tablist.apprentice"
        prefix="&f[&l&aApprentice&f]&r "
        priority=3
    }
    Beta {
        permission="tablist.beta"
        prefix="&f[&3&lBeta&f]&r "
        priority=10
    }
    Builder {
        permission="tablist.builder"
        prefix="&f[&e&lBuilder&f]&r "
        priority=14
    }
    Champion {
        permission="tablist.champion"
        prefix="&f[&c&lChampion&f]&r "
        priority=12
    }
    Conqueror {
        permission="tablist.conqueror"
        prefix="&f[&4&lConqueror&f]&r "
        priority=11
    }
    Cryogen {
        permission="tablist.dcryogen"
        prefix="&f[&9&lCRYOGEN&f]&9 ➤&r "
        priority=18
    }
    Elite {
        permission="tablist.elite"
        prefix="&f[&l&fE&l&elite&f]&r "
        priority=4
    }
    Event {
        permission="tablist.event"
        prefix="&f[&d&lEvent&f]&r "
        priority=15
    }
    Frostwind {
        permission="tablist.dfrostwind"
        prefix="&f[&l&6FROSTWIND&f]&6 ➤&r "
        priority=20
    }
    Glacialist {
        permission="tablist.dglacialist"
        prefix="&f[&5&lGLACIALIST&f]&5 ➤&r "
        priority=19
    }
    Icebound {
        permission="tablist.dicebound"
        prefix="&f[&8&lICEBOUND&f]&8 ➤&r "
        priority=16
    }
    Newbie {
        permission="tablist.newbie"
        prefix="&f[&l&7Newbie&f]&r "
        priority=1
    }
    Owner {
        permission="tablist.owner"
        prefix="&l&bOWNER "
        priority=23
    }
    Permafrost {
        permission="tablist.dpermafrost"
        prefix="&f[&l&bPERMA&l&fFROST&f]&b ➤&r "
        priority=21
    }
    Pokemaster {
        permission="tablist.pokemaster"
        prefix="&f[&l&3P&l&boké&l&3M&l&baster&f]&r "
        priority=9
    }
    Polaric {
        permission="tablist.dpolaric"
        prefix="&f[&2&lPOLARIC&f]&a ➤&r "
        priority=17
    }
    Ranger {
        permission="tablist.ranger"
        prefix="&f[&l&fR&l&6anger&f]&r "
        priority=5
    }
    Sentinel {
        permission="tablist.sentinel"
        prefix="&f[&l&cSentinel&f]&r "
        priority=8
    }
    Slowpoke {
        permission="tablist.dslowpoke"
        prefix="&f[&l&dSLOW&l&fPOKE&f] &d➤&r "
        priority=22
    }
    Staff {
        permission="tablist.staff"
        prefix="&f[&l&eMod&f]&r "
        priority=13
    }
    Trainer {
        permission="tablist.trainer"
        prefix="&f[&l&9Trainer&f]&r "
        priority=2
    }
    Veteran {
        permission="tablist.veteran"
        prefix="&f[&l&5Veteran&f]&r "
        priority=7
    }
    # This is an example group. This will be ignored.
    exampleGroup {
        # This permission is used to allow for player to show this group.
        permission="tablist.exampleGroup"
        prefix="&6[&cExampleGroup&6] "
        # Used to sort the player in player list if have this priority and group.
        priority=5
        suffix="Suffix is optional"
    }
}

### Bug description

I followed the config as suggested but sorting still doesn't work. I don't know where to go from here.

**Comment by montlikadani** [comment]
Sponge version of tablist is not supported by me anymore. It is posted already on the main page.

**Comment by montlikadani** [comment]
Sorting did not work, due to lack of a solution

**Comment by SaveasRPC** [comment]
> Sorting did not work, due to lack of a solution

Thank you for responding. Just to clarify, sorting has never worked for Sponge and therefore I should stop looking for solutions regarding this version of the plugin? Thank you again.

**Comment by montlikadani** [comment]
As I mentioned earlier, the plugin is no longer under development, so the sorting issue will not be fixed. But if I were to develop it further and there was a solution for it, it could work.

**Comment by SaveasRPC** [comment]
Would you take commissions for it?

**Comment by montlikadani** [comment]
No
