### ISSUE TITLE
Issues with a DisplayName

### ISSUE THREAD

**Issue by Syncronicalerror** [montlikadani/TabList#49]
I Got A Problem with The Plugin I need  A fix this :c

The Last Version

### Console error (required)
02.09 17:03:29 [Server] INFO https://github.com/montlikadani/TabList/issues
02.09 17:03:29 [Server] WARN There was an error. Please report it here:
02.09 17:03:29 [Server] WARN at java.lang.Thread.run(Thread.java:745)
02.09 17:03:29 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
02.09 17:03:29 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
02.09 17:03:29 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
02.09 17:03:29 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
02.09 17:03:29 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
02.09 17:03:29 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02.09 17:03:29 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
02.09 17:03:29 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
02.09 17:03:29 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
02.09 17:03:29 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
02.09 17:03:29 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
02.09 17:03:29 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
02.09 17:03:29 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
02.09 17:03:29 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
02.09 17:03:29 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
02.09 17:03:29 [Server] WARN at hu.montlikadani.TabList.bukkit.Commands.onCommand(Commands.java:67)
02.09 17:03:29 [Server] WARN at hu.montlikadani.TabList.bukkit.TabList.cancelGroupUpdate(TabList.java:867)
02.09 17:03:29 [Server] WARN at hu.montlikadani.TabList.bukkit.TabList.unset(TabList.java:1064)
02.09 17:03:29 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:139)
02.09 17:03:29 [Server] WARN at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
02.09 17:03:29 [Server] WARN java.lang.IllegalArgumentException: Team name '?6[?7Owner?6]?4?kii?r' is longer than the limit of 16 characters

[config.zip](https://github.com/montlikadani/TabList/files/2343684/config.zip)

**Comment by montlikadani** [comment]
**Please update to the latest version because you do not have it.** ...and exceeded the 16-character limit for the Owner rank.
```
02.09 17:03:29 [Server] WARN java.lang.IllegalArgumentException: Team name '?6[?7Owner?6]?4?kii?r' is longer than the limit of 16 characters
```
_If you want more than 16 characters, update to 1.13 with the Bukkit/Spigot software._
