### ISSUE TITLE
Group Weighting - Does not appear to be working

### ISSUE THREAD

**Issue by lpjn** [montlikadani/TabList#496]
### Type of bug

General issue

### TabList version

5.7.5

### Software version

git-Paper-423 (MC: 1.20.4)

### Relevant plugins

LuckPerms, TabList

### Console error (if applicable)

N/A

### TabList configuration files

config.yml https://paste.gg/p/anonymous/136d798a33164a9b9f63772b4703125a
groups.yml https://paste.gg/p/anonymous/f8cefbff2ee64e0485edd0ffe8d8fa39
![image](https://github.com/montlikadani/TabList/assets/38690189/46dfb65e-c998-417b-b3c7-83ae5f6430e7)

### Bug description

A player whom is a member of the supporterplus group with a wright of 7, is being displayed as a Regular in the tablist which has a weight of 1. Am I missing something? thanks

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/wiki/Setting-sort-priority

**Comment by lpjn** [comment]
Thanks for getting back so quickly. I'll use the manual priority config instead of depending on the `use-luckperms-weight-to-order-groups-to-first-place:` setting
