### ISSUE TITLE
TAB Towny Placeholder is not updating POSSIBLE BUG

### ISSUE THREAD

**Issue by OscarGithub3** [montlikadani/TabList#499]
### Type of bug

Compatibility issue

### TabList version

This server is not running any plugin by that name.

### Software version

This server is running CraftBukkit version 3871-Spigot-d2eba2c-3f9263b (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Relevant plugins

-TAB
-Vault
-TownyAdvanced
-PlaceHolderAPI

### Console error (if applicable)

None

### TabList configuration files

This server is not running any plugin by that name.

### Bug description

The Placeholder does not update when it enters to a town, but when I use the hologram and put the place holder there it updates quickly as soon as you enter a town.

**Comment by montlikadani** [comment]
wrong plugin
