### ISSUE TITLE
suffix and prefix

### ISSUE THREAD

**Issue by RescoolCZ** [montlikadani/TabList#5]
Hello, I have a problem with the plugin. Tablist does not show suffix and prefix.

**Comment by montlikadani** [comment]
@RescoolCZ 
What plugin does it use?
Try to disable nick-enable.

**Comment by RescoolCZ** [comment]
Permissionsex

**Comment by montlikadani** [comment]
@RescoolCZ 
Use this version, I fixed this issue: http://www.mediafire.com/file/xh1xyqe4gwqa1zo/TabList.jar

**Comment by RescoolCZ** [comment]
ok thank you :)

**Comment by montlikadani** [comment]
@RescoolCZ 
Does it work now?

**Comment by RescoolCZ** [comment]
no :/

**Comment by montlikadani** [comment]
What plugin does you use for prefix and suffix?

**Comment by RescoolCZ** [comment]
permissionsex

**Comment by montlikadani** [comment]
Oh, I wrote ... I thought what plugin you used as tab prefix and suffix? Only PermissionsEx?

**Comment by RescoolCZ** [comment]
yes

**Comment by montlikadani** [comment]
I did that by deleting the nick features and replacing the tab name instead.

**Comment by montlikadani** [comment]
@RescoolCZ 
Try updating to the latest version.

**Comment by RescoolCZ** [comment]
ok :)


2018-03-21 15:55 GMT+01:00 montlikadani <notifications@github.com>:

**Comment by montlikadani** [comment]
@RescoolCZ 
Now show it?

**Comment by montlikadani** [comment]
@RescoolCZ 
### Thanks for notifying me!
**I added this as a new function to the plugin.** _New update:_ https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=218097
