### ISSUE TITLE
Problem in showing PREFIX  in dev 359

### ISSUE THREAD

**Issue by tantrum90** [montlikadani/TabList#517]
### Type of bug

Compatibility issue

### TabList version

17.06 18:26:32 [Server] INFO TabList version 5.7.5 17.06 18:26:32 [Server] INFO An alternative tablist plugin to replace vanilla empty tab 17.06 18:26:32 [Server] INFO Author: montlikadani.   /## I am using #359 latest build

### Software version

17.06 18:27:49 [Server] INFO This server is running Paper version 1.20.6-129-master@0513374 (2024-05-31T15:53:34Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT) 17.06 18:27:49 [Server] INFO You are 17 version(s) behind 17.06 18:27:49 [Server] INFO Download the new version at: https://papermc.io/downloads/paper 17.06 18:27:49 [Server] INFO Previous version: git-Paper-286 (MC: 1.20.2)

### Console error (if applicable)

no consol error

### TabList configuration files

https://paste.gg/p/anonymous/e022809b72ef4e4fb147241aba156e03

### Bug description

The PREFIX of the groups is not showed:
https://paste.gg/p/anonymous/bba3172460324be7b13c4907067efb11 - groups config. 
This was not problem when the server was on 1.20.2 and 1.20.4

<img width="1512" alt="image" src="https://github.com/montlikadani/TabList/assets/171391033/a7fe5990-f6a6-4007-a981-55cd577470ab">

**Comment by montlikadani** [comment]
I am unable to reproduce this, it works for me.

**Comment by SlimeDog** [comment]
I see prefixes with:
Paper 1.21-9
EssentialsX 2.21.0-dev+93-3a6fdd9
LuckPerms 5.4.134
TabList 5.7.5-b361

I don't use EssentialsXChat

**Comment by montlikadani** [comment]
EssentialsChat only modifies player list name once when the user sets someone's nick name through command and TL updates groups (which is player list name basically) every 4 (or the value set in config) milliseconds (server ticks). So it shouldn't be the case

**Comment by tantrum90** [comment]
I updated the Paper to latest #147 version, and still have the same problem.
https://paste.gg/p/anonymous/059d7cd1356a4e1bb78154e295a2366d


<img width="1512" alt="image" src="https://github.com/montlikadani/TabList/assets/171391033/6aa9ddb8-ccb7-44c4-af89-0e744282b996">

**Comment by montlikadani** [comment]
![image](https://github.com/montlikadani/TabList/assets/30026208/3c4c8106-fc10-4be9-8bd7-4fa57461f645)
Still works for me

**Comment by jurohn** [comment]
I have the same problem

Paper 1.21 Dev9
EssentialsX-2.21.0-dev+93-3a6fdd9.jar
LuckPerms-Bukkit-5.4.134.jar
TabList-bukkit-v5.7.5.jar

Prefix wont show in Tablist.

![image](https://github.com/montlikadani/TabList/assets/137065095/88745d14-0a2c-46b6-9890-65015f84acd9)

**Comment by jurohn** [comment]
@montlikadani Are you willing to share your tablist config? Maybe we do something wrong

**Comment by tantrum90** [comment]
While trying different solutions, i find out that if I set prefix per player it is working, but groups are not loaded.

https://paste.gg/p/anonymous/a49ce37c8dbf449bbb7eb6d8210d657c

<img width="1512" alt="image" src="https://github.com/montlikadani/TabList/assets/171391033/aa6324e6-91ce-4b00-807d-621a820f8e80">

and I know for sure that groups are set correctly:
Chat:
<img width="668" alt="image" src="https://github.com/montlikadani/TabList/assets/171391033/27ba0d41-a601-4fad-aedb-6903637d15cd">

Console:
<img width="794" alt="image" src="https://github.com/montlikadani/TabList/assets/171391033/001fb457-30cb-4fa9-aae2-5ed31aab4b03">

There must be something related to Vault or Luckperms that is preventing to read groups in 1.20.6

**Comment by tantrum90** [comment]
you can close the issue. I find it out what was the problem:

**The order of the groups matters
If a player has more than one group added, such as VIP and moderator, you want the moderator prefix to be visible. To do this, move the moderator at the bottom after the last group, or set a sort-priority value that the plugin will sort.
Or set priority for each group, please [refer to this document](https://github.com/montlikadani/TabList/wiki/Setting-sort-priority) how priorities are working.**

I moved the default group as last, and now everything works great

**Comment by montlikadani** [comment]
Oh yeah, I didn't thought about this multiple groups.

**Comment by jurohn** [comment]
Welll... i think this should be easier.
Tip for the owner:
Let add custom groups through luckperms, with prio's higher than the example groups.

Thanks to both however. I fixed my problem as well!

groups:
  ```
owner:
    prefix: '&#00b4fcOWNER '
    tabname: '%player%'
    suffix: ''
    sort-priority: 2
  default:
    prefix: '&#ffaa00MEMBER'
    tabname: '%player%'
    suffix: ''
    sort-priority: 1
  

```
