### ISSUE TITLE
1.21.1

### ISSUE THREAD

**Issue by jurohn** [montlikadani/TabList#525]
### Type of bug

Compatibility issue

### TabList version

Doesnt start.

### Software version

Paper 1.21.1

### Relevant plugins

None

### Console error (if applicable)

10.08 18:24:26 [Server] ERROR [TabList] Your server version does not supported 1.21.1-R0.1-SNAPSHOT
10.08 18:24:26 [Server] INFO [TabList] Disabling TabList v5.7.6
10.08 18:24:26 [Server] ERROR Error occurred while disabling TabList v5.7.6
10.08 18:24:26 [Server] INFO java.lang.NullPointerException: Cannot invoke "hu.montlikadani.tablist.tablist.groups.Groups.cancelUpdate()" because "this.groups" is null
10.08 18:24:26 [Server] INFO at TabList-bukkit-v5.7.6.jar/hu.montlikadani.tablist.TabList.onDisable(TabList.java:118) ~[TabList-bukkit-v5.7.6.jar:?]
10.08 18:24:26 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
10.08 18:24:26 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:26 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
10.08 18:24:26 [Server] INFO at TabList-bukkit-v5.7.6.jar/hu.montlikadani.tablist.TabList.onEnable(TabList.java:68) ~[TabList-bukkit-v5.7.6.jar:?]
10.08 18:24:26 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
10.08 18:24:26 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:26 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
10.08 18:24:26 [Server] INFO at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:26 [Server] INFO at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:26 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:26 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:26 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:26 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:26 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-3-70dfa46]
10.08 18:24:26 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### TabList configuration files

Not relevant.

### Bug description

Doesnt start

**Comment by tantrum90** [comment]
I have the same problem.
Paper 1.21.1 v.5

**Comment by montlikadani** [comment]
https://github.com/montlikadani/TabList/commit/fde7705581ac48377865cd3a8da2bd6a495d0426

New version will be released soon

**Comment by SlimeDog** [comment]
Confirmed fixed in dev build 5.7.6-b367. Thanks.

**Comment by jurohn** [comment]
![image](https://github.com/user-attachments/assets/9b1fb7ed-6697-4ad9-ab6d-4347ba3188bd)

@montlikadani Really really professional of you. Great respect for your users.

Anyway, thanks for updating.

**Comment by montlikadani** [comment]
> @montlikadani Really really professional of you. Great respect for your users.

professional? It's too basic to be and not even good solution
