### ISSUE TITLE
Tablist does not show all players 

### ISSUE THREAD

**Issue by PRMees** [montlikadani/TabList#53]
Hi I use this plugin and its great but some players keeps just randomly go away from the tablist even my self like 1 hour later i see myself and someone else doesnt see my or himself its all just weird and random I dont know if it is because of this plugin but I think it is because when I didnt had this plugin it was all good!

Thanks for taking your time!
(Here you see all the plugins I use)
https://dl.dropboxusercontent.com/s/k52paz0hldzzqho/2018-09-21_15-59-08.mp4

**Comment by montlikadani** [comment]
**This is not my plugin.**
