### ISSUE TITLE
Sorted names in tablist?

### ISSUE THREAD

**Issue by wryel2000** [montlikadani/TabList#535]
### Type of bug

Other

### TabList version

5.7.7

### Software version

1.16.5 velocity

### TabList configuration files

n/a

### Bug description

I would like to ask if there is any way to update the list of player positions frequently? The statistical names of the players do not reflect the movements of new players. (ps: I also use fakebot, I would like to mix them up)

**Comment by montlikadani** [comment]
Player positions on player list will be updated frequently with tablist groups depending on the interval value. If this not enabled, they will be positioned as how the client displays it, alphabetically.

**Comment by wryel2000** [comment]
Right,
Thanks for the answer, if the player has more than 1 group, will it position the player with the highest group?

**Comment by montlikadani** [comment]
If the group have higher priority, yes

**Comment by wryel2000** [comment]
tks, closed up
