### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by hydrawalnut** [montlikadani/TabList#54]
### Describe the bug (required)
Not showing other any other groups

### Plugin & software (Bukkit/Spigot) version (required)
Spigot

### Console error (required)
> 
> Send the console error if you have it.
>

### Config.yml or other file
Send the config.yml or other file.
(required)
```
[config.zip](https://github.com/montlikadani/TabList/files/2408430/config.zip)
[groups.zip](https://github.com/montlikadani/TabList/files/2408431/groups.zip)


config.yml
```

(optional)
```
other file
```

### Screenshots (optional)
![2018-09-23_00 15 16](https://user-images.githubusercontent.com/43509985/45924497-e9cb0a80-bec6-11e8-949c-7e92b56b077c.png)

**Comment by montlikadani** [comment]
Does the player have permission to receive the group?

**Comment by XXXJetfireXXX** [comment]
I think he means that the default group prefix is overlapping all another prefixes. (I have the same problem) (Also i think all players that inherits the default prefix permission will be showing up with it.)
Here's my groups.yml:
[groups.zip](https://github.com/montlikadani/TabList/files/2424572/groups.zip)

I'm admin on my server, and i have the "tablist.staff" permission, but i'm still showing up like a player (tablist.default).

**Comment by montlikadani** [comment]
As I said the player (as you) operator on the server (op)?
Nickname function is not in the TabList plugin.

**Comment by XXXJetfireXXX** [comment]
Sure, i'm operator on my server.

**Comment by XXXJetfireXXX** [comment]
About nickname: i was expecting that putting color code after prefix will change nickname color, but it doesn't change.
(prefix: '&4[&cAdmin&4]&6 ')

**Comment by montlikadani** [comment]
Changes but you are an operator on the server. This is an error and will be visible in the next version as I have fixed it.

**Comment by XXXJetfireXXX** [comment]
Okey, no problem. Thank you for the immediate response :)

**Comment by montlikadani** [comment]
https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=250164
