### ISSUE TITLE
Placeholders don't work

### ISSUE THREAD

**Issue by ExpertsGaming** [montlikadani/TabList#56]
### Describe the bug (required)
placeholders dont work it just displays %player%

### Software (Bukkit/Spigot) version (required)
Spigot 1.10.2

### Console error (required)
> 
> Send the console error if you have it.
>

### Config.yml or other file
https://pastebin.com/UqUgDKYW

**Comment by montlikadani** [comment]
%player% placeholder works only if PlaceholderAPI is not found on the server.
**If so, please update to the latest version.**
