### ISSUE TITLE
The tab menu doesn't even show up

### ISSUE THREAD

**Issue by TheMiscreatedGamer** [montlikadani/TabList#57]
I've got the plugin installed, and the config is default and everything should be working, but when I press tab, nothing is there.

My server is currently running Spigot 1.12.2

Config - https://pastebin.com/X0iX7QCQ

**Comment by montlikadani** [comment]
Please send the full plugin list.
Do you have disabled the tab with /tl toggle command?

**Comment by TheMiscreatedGamer** [comment]
I've updated the plugin, and now the config is completely different and kind of works, but none of the placeholders are  wanting to work.

**Comment by montlikadani** [comment]
wut??
Which placeholders do not appear?
