### ISSUE TITLE
Can't see other peoples ranks/prefixes

### ISSUE THREAD

**Issue by TheMiscreatedGamer** [montlikadani/TabList#58]
Whenever I use any type of scoreboard plugin, the prefixes on the tablist show mine and nobody else's. The same goes for other people, they can see their prefix, but nobody else's.  Once I remove the scoreboard plugin, the prefixes goes back to working just fine.

Spigot 1.12.2

Config - https://pastebin.com/Fd2se1Ly

https://gyazo.com/37d3ae7530408c48415b936658a7332c

**Comment by montlikadani** [comment]
Did you try to change the `change-prefix-suffix-in-tablist.use-external-scoreboard` boolean to **false**?

**Comment by montlikadani** [comment]
Try updating to the latest version.
