### ISSUE TITLE
v3.6 help

### ISSUE THREAD

**Issue by Anenokil228** [montlikadani/TabList#59]
[config.yml.txt](https://github.com/montlikadani/TabList/files/2526613/config.yml.txt)

![2018-10-29_21 33 52](https://user-images.githubusercontent.com/44585361/47672197-6afe7700-dbc2-11e8-83ad-4898d35b9077.png)

**Comment by montlikadani** [comment]
You can check the new config file and update it: https://github.com/montlikadani/TabList/blob/master/config.yml
