### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Matrixdoesmc** [montlikadani/TabList#6]
[22:07:16 WARN]: java.lang.ArrayIndexOutOfBoundsException: 0
> [22:07:16 WARN]: at hu.montlikadani.TabList.TabList.sendTabTitle(TabList.java:563)
> [22:07:16 WARN]: at hu.montlikadani.TabList.TabList$8.run(TabList.java:661)
> [22:07:16 WARN]: at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
> [22:07:16 WARN]: at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> [22:07:16 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [22:07:16 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [22:07:16 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by montlikadani** [comment]
**### Thank you for reporting it!**

_This issue is currently under repair..._

**Comment by montlikadani** [comment]
**This error has been resolved and an update has been completed.** https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=217083
