### ISSUE TITLE
No colored usernames.

### ISSUE THREAD

**Issue by steamtm** [montlikadani/TabList#60]
When I try to color a username like in the example picture, it just stays white. I am adding the color code I want to the end of my prefix, yet when I look in game at the tablist, my username just stays the same color, white. The actual prefixes are working with colorcodes but they are not affecting my username whatsoever. Please help.

**Comment by steamtm** [comment]
Server version: Paper 1.13.2
PAPI version: 2.9.2
Vault version: 1.6.7

**Comment by montlikadani** [comment]
Do you using the official Minecraft version or a cracked? If you use a cracked version then the name changing is not available. If you use the tabname function then you can change your name.

**Comment by steamtm** [comment]
Premium. I have the tabname turned on, but in the config it said if you use groups it overrides the tabname function. I can paste my config and my groups here to let you look at them and make sure they are right if you want.

**Comment by steamtm** [comment]
Config: https://pastebin.com/bw2SjaXM
Groups.yml: https://pastebin.com/AYCL3fLu

**Comment by montlikadani** [comment]
As I wrote in the comment in the configuration, the tabname function and the groups overwrite each other so both do not work at the same time. Disable one.

**Comment by steamtm** [comment]
Ok, I disabled the tabname function, but the only thing showing in game still is the prefix, not the prefix and a colored username.

**Comment by steamtm** [comment]
This is what shows in the tab. 
![image](https://user-images.githubusercontent.com/45522897/49342495-1a979080-f62a-11e8-93ae-bb57d0fb4eac.png)
I have the owner group's prefix set to: &c&lO &7&l so it should color the username bold grey.

**Comment by montlikadani** [comment]
Thanks. This is for me not to change the name color. I'm trying to fix it if it not correct, then it's a Minecraft or a Spigot/Paper error, and I would report it as a bug. I will test this in a separate test plugin where there is only one method.

**Comment by thedovy** [comment]
I have the exact same issue and it's very annoying... I hope you will be able to fix it @montlikadani

Waiting for news!:)

**Comment by NEZNAMY** [comment]
So name color does not change when using scoreboard teams for prefix/suffix on 1.13.2, but works fine on 1.12.2 ?

**Comment by NEZNAMY** [comment]
Because mojang changed how name color is changed in 1.13.2, it's not the last color of prefix anymore. You somehow need to change player's "chat format" using Team#setColor(ChatColor).

**Comment by montlikadani** [comment]
@NEZNAMY 
Thank you, I fixed this with `team.setColor(prefix)` method.

**Comment by montlikadani** [comment]
Fixed in the latest version.
