### ISSUE TITLE
Permission not working

### ISSUE THREAD

**Issue by NetyTV** [montlikadani/TabList#61]
I created a group "majitel" in groups.yml, I set the permission to "tablist.majitel", added the permission to pex group, anyway in tablist I am not in group "majitel".

Spigot 1.8.8.

groups.yml: https://pastebin.com/8gYE6PmK 
config.yml: https://pastebin.com/m63y3ZwV

My name then looks like this:
![obrazek](https://user-images.githubusercontent.com/42073765/49394441-2a030080-f734-11e8-826d-daf9de3bdd99.png)
But should look like "[Majitel] Nety" how it's in groups.yml.

**Comment by montlikadani** [comment]
The PermissionsEX plugin is not supported because it is obsolete. Use a [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) plugin.

**Comment by NetyTV** [comment]
I am now using LuckPerms, I've got the prefix, but it's not right. 
  
__**_Nety:
    prefix: '&a[&cMajitel&a] '_**__
I have prefix Majitel.

  **_nikolasniky:
    prefix: '&a[&cAdmin&a] '_**
nikolasniky is having prefix Majitel, too. He should have Admin. :/

groups.yml: https://pastebin.com/uFEi8uzX

**Comment by montlikadani** [comment]
Soon I will add the PEX to the TabList plugin to support.
