### ISSUE TITLE
%player_name% error

### ISSUE THREAD

**Issue by Huskei** [montlikadani/TabList#62]
### Describe the bug (required)
In tablist, the %player_name% wont show, it just shows the actual text "%player_name&" wondering if there was a fix. (I do have PlaceholderAPI)

### Software (Bukkit/Spigot) version (required)
Spigot-db6de12-18fbb22 (Spigot 1.8.8)
![image](https://user-images.githubusercontent.com/42254155/49478863-11a3ec00-f7ef-11e8-9f4b-91461f0668e8.png)

**Comment by montlikadani** [comment]
Do you have executed this command to register the player placeholders? `/papi ecloud download Player`

**Comment by Huskei** [comment]
At the moment I cannot check but it said something about how it couldn't download cloud expansions. I believe I'll be home in around 3 hours so I can send photos then.

**Comment by montlikadani** [comment]
The problem may be that the placeholderAPI configuration is not enabled in the `cloud_enabled` boolean.

**Comment by Huskei** [comment]
How would I fix the PlaceholderAPI?

**Comment by Huskei** [comment]
Also do you have a discord so we dont have to communicate through here?

**Comment by montlikadani** [comment]
Yes, I have dc, my name: montlikadani#1641

**Comment by Huskei** [comment]
[SOLVED] I had to turn off Papi (set to false) in tablist config then change %player_name% to %player% Thanks montilkadani!
