### ISSUE TITLE
Vanished player's gone

### ISSUE THREAD

**Issue by NetyTV** [montlikadani/TabList#63]
Hello, it's me again :smile: I've got **hide-group-when-player-vanished: false** but when I am vanished I'm still hidden in the tablist for other players. 

Spigot 1.8.8
Tablist: 3.7

**Comment by montlikadani** [comment]
wut? Please describe clearly what you want.

**Comment by NetyTV** [comment]
Of course. When I type /vanish, I am hidden in the tablist. But I want to be visible in the tablist even with /vanish on.

**Comment by montlikadani** [comment]
If you want to hide yourself from other players, enter this command: `/tl hideme`

And if it does, if the `change-prefix-suffix-in-tablist.hide-group-when-player-vanished` is enabled, enter `/vanish on`, it will be visible, but it will not appear on the tablist?

**Comment by montlikadani** [comment]
No, this option means to **hide the group** when the player /vanish on is in. If you want to do this, write it to true.
