### ISSUE TITLE
Unable to see the player name with %player_name%

### ISSUE THREAD

**Issue by TheRedSoldier6** [montlikadani/TabList#64]
### Describe the bug (required)
I just downloaded the plugin and if I click in game on TAB is says: %player_name% but it does not say my minecraft name that's the problem.

### Software (Bukkit/Spigot) version (required)
I'm using Spigot_1.11.2

### Console error (required)
> 
> I don't have a console error
>

### Config.yml or other file
Send the config.yml or other file.
https://pastebin.com/btKNtF86
(required)
https://pastebin.com/btKNtF86
config.yml
https://pastebin.com/btKNtF86

(optional)
https://pastebin.com/btKNtF86
other file
https://pastebin.com/btKNtF86

### Screenshots (optional)
<a href="http://nl.tinypic.com?ref=2i6jsx4" target="_blank"><img src="http://i68.tinypic.com/2i6jsx4.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by montlikadani** [comment]
Do you executed this command?: `/papi ecloud download Player`
**Please read the full page of the plugin.**
