### ISSUE TITLE
Animation brakes

### ISSUE THREAD

**Issue by cenaamil** [montlikadani/TabList#68]
When a person joins the server, all of the animations just stop. Only way to fix it is to re log into the server. 
I'm on version 3.8 of the plugin, using the latest version of craftbukkit

**Comment by montlikadani** [comment]
Try with the latest version.

**Comment by FakAWg** [comment]
I am using 3.9 version of spigot 1.10 and I've the same issue. I already tried the solution of the post and it did not solve it

**Comment by montlikadani** [comment]
This is no longer the case with recent versions.
