### ISSUE TITLE
Error refresh Number Of Player Server

### ISSUE THREAD

**Issue by TheCalypso** [montlikadani/TabList#69]
### Describe the bug (required)
Understand what the problem is with the plugin.
Hello, in the screen I just sent you I'm TheCalypso, you can see that the TAB shows 2 players while we are on the server "Survival". And when someone arrives it is not updated. For information the top and bottom of the TAB list is managed by your plugin and the middle (player view) is managed by the BungeeTabListPlus plugin with the latest version of the plugin in devbuild which worked very well before.

### Software (Bukkit/Spigot) version (required)
Describe the software version you are using now.

### Console error (required)
> No
> Send the console error if you have it.
>No

### Config.yml or other file
Send the config.yml or other file.
You can send (if you want) files link e.g. pastebin.com or paste a code block.
(required)
``
https://pastebin.com/2ybEyC9b```

```
### Screenshots (optional)
Send a few pictures of the problem if you can.
![image](https://user-images.githubusercontent.com/33781244/51270397-10a4d380-19c5-11e9-80b9-5d42d4a8688b.png)

**Comment by montlikadani** [comment]
Check the following:
- Make sure the player is live and not a fake player.
- The player is not vanish, so you can see.
- Make sure that the player has actually joined that server.

**Comment by TheCalypso** [comment]
Hello, 
I want to say that it still does not work! Even with the latest version of TabList 3.9 the TAB still does not update, I want to say that I have the latest PlaceholderAPI extensions which are Bungee, Essentials, ListPlayers, Player, Server, Vault, WorldGuard.

**Comment by montlikadani** [comment]
Are you sure you have disabled BungeeTabListPlus to modify playerlist (players) in tablist?

**Comment by TheCalypso** [comment]
Why do I need to disable BungeeTabList?

**Comment by montlikadani** [comment]
Oh, sorry not to disable the plugin, but at the playerlist that would handle it the BTLP.
