### ISSUE TITLE
Minor TabList Bug

### ISSUE THREAD

**Issue by Sam-Diggity** [montlikadani/TabList#7]
I've discovered a miniature bug:
Every time I log into my server with TabList installed, the tab list itself doesn't appear until I execute /tablist reload. I've checked the console; no errors. Everything works fine after the fact that I tell it to activate.

**Comment by montlikadani** [comment]
@Sam-Diggity 
When is it connected to the server, will it still appear on the tab?
Will it not only appear when you've disabled it and reloaded it?

**Comment by Sam-Diggity** [comment]
@montlikadani 
If I'm understanding you correctly, you are asking if the tab list itself shows without me reloading it. To answer your question, no. I must activate it before it displays the tab list. It's not disabled nor is it showing up as red when I do /plugins.

**Comment by montlikadani** [comment]
@Sam-Diggity 
I do not know why it does not work for you, but it works fine for me.

**Comment by Sam-Diggity** [comment]
I'm not really sure why you marked this thread as invalid. I reported a bug where I was told do to so and get no help in return. The bug is honestly almost enough to make me switch TabList plugins.

**Comment by Julianvb97** [comment]
Did you try the updated version? And the try the reload the plugin. That should work!

**Comment by Sam-Diggity** [comment]
Update 2.2 doesn't fix this problem

**Comment by Sam-Diggity** [comment]
Just tried the newest update (2.3) and it worked. Thanks guys. (That's embarrassing :P)

**Comment by montlikadani** [comment]
I was not here and you solved it...

**Comment by Sam-Diggity** [comment]
Yes, and I apologize. Thanks for your updates.
