### ISSUE TITLE
Prefixes don't load after someone votes with the weather vote plugin or time vote plugin.

### ISSUE THREAD

**Issue by MrRonald234** [montlikadani/TabList#73]
### Describe the bug (required)
Understand what the problem is with the plugin.
So the tab works perfectly and I really like it a lot. But when someone initiates a vote for the vote plugin for time or the weather which uses the boss bar the whole tab glitches out. It refreshes instantly after a few seconds and it will work again but it only refreshes my own prefix. Once I do /tl reload it doesn't help at all and everyone else doesnt have a prefix untill I relog.
### Software (Bukkit/Spigot) version (required)
Describe the software version you are using now.
Spigot 1.13.2 (Using V3.9 off this plugin)
### Console error (required)
> 
> Send the console error if you have it.
>

### Config.yml or other file

Send the config.yml or other file.
You can send (if you want) files link e.g. pastebin.com or paste a code block.
(required)
```
[config.yml.txt](https://github.com/montlikadani/TabList/files/2797147/config.yml.txt)
```

(optional)
```
other file
```

### Screenshots (optional)
Send a few pictures of the problem if you can.
![2019-01-25_18 31 10](https://user-images.githubusercontent.com/47037946/51762220-6e28d680-20cf-11e9-83cb-db57f1ac17f9.png)

**Comment by MrRonald234** [comment]
![2019-01-25_18 51 49](https://user-images.githubusercontent.com/47037946/51763230-53a42c80-20d2-11e9-9412-2621bbfdb040.png)
After a relog it all works again. So why does this happen? Since we use timevote and weathervote quite a lot.

**Comment by montlikadani** [comment]
There is also no enabled **change-prefix-suffix-in-tablist.enable** function in the TabList configuration.

The plugin might overwrite the tablist groups so it doesn't work. Make sure you disabled the functions associated with the tablist in that plugin.

**Comment by MrRonald234** [comment]
[config.yml.txt](https://github.com/montlikadani/TabList/files/2797218/config.yml.txt)

Sorry this is the right config. I uploaded one of my earlier backups by accident

I will take a look if the plugins overwrite the tablist at any point during the voting process

**Comment by MrRonald234** [comment]
This is the config of the weather vote plugin:

Version: 1.42
GameVersion:
  SetOwn: false
  Version: v1_13_R2
ColoredConsoleText: true
VotingTime: 35
RemindingTime: 25
TimeoutPeriod: 15
UseScoreboard: true
UseVoteGUI: true
UseBossBar: true
UseTitle: false
CheckForHiddenPlayers: false
PrematureEnd: true
Price: 0.0
RawMessages: true
DisabledWorld:
- world_nether
- world_the_end
VotingInventoryMessages: true
ShowOnlyToPlayersWithPermission: false
RefundVotingPriceIfVotingFails: true

**Comment by MrRonald234** [comment]
Might have something to do with the scoreboard?

**Comment by MrRonald234** [comment]
I found the problem!
The problem is that the other plugins use the scoreboard. So when that activates the tab reloads so to say and fcks everything up. So I disabled the scoreboard in the plugins and everything works as it should! Thanks for looking with me
