### ISSUE TITLE
Group Permission

### ISSUE THREAD

**Issue by Tvyxline** [montlikadani/TabList#74]
Hello, I have created group in the .yml file with prefixes and when I had the permission node to my permission plugin, my prefix doesnt came up in tab. I use permissionEX so I did /pex group Admin add groups.admin and it was exacly the same in the tablist plugin. The only way was to /tl setprefix (Name) (Prefix) But Its very much work, and when someone buys a rank I have to join all server and set his prefix.

**Comment by montlikadani** [comment]
The `/tl setprefix` command makes it possible for the specified player to create a group that allows the player to display on the tab and overwrites the set groups that have the permission string.
The PEX plugin is supported, only very obsolete and has not been developed (if you want a better and error-free permission plugin, use the LuckPerms plugin).
First, send me a TabList groups.yml file to know what it contains.

**Comment by Tvyxline** [comment]
https://pastebin.com/0xpKhwjq

**Comment by Tvyxline** [comment]
> The `/tl setprefix` command makes it possible for the specified player to create a group that allows the player to display on the tab and overwrites the set groups that have the permission string.
> The PEX plugin is supported, only very obsolete and has not been developed (if you want a better and error-free permission plugin, use the LuckPerms plugin).
> First, send me a TabList groups.yml file to know what it contains.

https://pastebin.com/0xpKhwjq

**Comment by montlikadani** [comment]
@Tvyxline _Do not send the message again because I see that I have not yet tested whether it works._

**Comment by montlikadani** [comment]
I've just tested it and it worked for me. Can you send me a screenshot of the tablist in the game?

**Comment by Tvyxline** [comment]
It worked! I joined with a another account and It worked,
