### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by DarkMonolith** [montlikadani/TabList#78]
**!** required

**If ! mark is not specified then not need to write.**

### Describe the bug (!)
Understand what the problem is with the plugin.
console spam

(!) Software (Bukkit/Spigot/Paper) name & version:
1.13.2

(!) Plugin version:
Latest

Java version:

### Console error (!)
12.04 17:37:58 [Server] WARN Plugin TabList v4.2 generated an exception while executing task 19
12.04 17:37:58 [Server] INFO java.lang.NullPointerException: null
12.04 17:37:58 [Server] INFO at hu.montlikadani.tablist.TabList.sendTab(TabList.java:726) ~[?:?]
12.04 17:37:58 [Server] INFO at hu.montlikadani.tablist.TabList.access$1(TabList.java:674) ~[?:?]
12.04 17:37:58 [Server] INFO at hu.montlikadani.tablist.TabList$8.run(TabList.java:639) ~[?:?]
12.04 17:37:58 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.04 17:37:58 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Spigot_Latest.jar:git-Spigot-3cb9dcb-0f708cb]
12.04 17:37:58 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
12.04 17:37:58 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
12.04 17:37:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

### Config.yml (!)
https://pastebin.com/GSCmeSXk

### Screenshots
Send a few pictures of the problem if you can.

**Comment by montlikadani** [comment]
Restart your server completely.

**Comment by DarkMonolith** [comment]
this was just after installing it and starting the server up, though. Nothing had changed.

**Comment by montlikadani** [comment]
Do you take a screenshot about your server plugins? (enough if take in-game)

**Comment by DarkMonolith** [comment]
![image](https://user-images.githubusercontent.com/26663571/56058625-e3e82a00-5d2f-11e9-94a3-0a110eeda77a.png)

**Comment by montlikadani** [comment]
So is this all plugins?

**Comment by DarkMonolith** [comment]
yes. and tablist

**Comment by montlikadani** [comment]
Did you try to run a server on **your computer** with the tablist plugin?

**Comment by montlikadani** [comment]
**Fixed in the latest version.**
