### ISSUE TITLE
Tablist not show to individual.

### ISSUE THREAD

**Issue by pumegaming** [montlikadani/TabList#79]
Normally tablist will not show at all
but however when i toggle plugin off and on
it work again
but if player leave and re-login
tablist no longer show for them

Software Spigot name & version: Spigot 2148
Plugin version: 4.2
Java version: 8

Console error
> Plugin TabList v4.2 has failed to register events for class hu.montlikadani.tablist.Listeners because net/ess3/api/events/AfkStatusChangeEvent does not exist.

Config.yml
https://pastebin.com/XDRnaczg

**Comment by montlikadani** [comment]
Will be fixed in the next release.

**Comment by montlikadani** [comment]
**Fixed in the latest version.**
