### ISSUE TITLE
Reload command is broken after doing 1 reload

### ISSUE THREAD

**Issue by Julianvb97** [montlikadani/TabList#8]
Hi, 

I'm here because of a problem with the /tl reload command. I tried it a couple of times but continually after 1 or 2 tries I'm getting this error: https://pastebin.com/ragGVjii

I hope this could be solved in the next update?

**Comment by montlikadani** [comment]
@Julianvb97 
### Thank you for reporting it!
_This bug has just been fixed and will soon update..._

**Comment by montlikadani** [comment]
**This error has been resolved and an update has been completed.** https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=217083
