### ISSUE TITLE
BungeeCord Console spam issue

### ISSUE THREAD

**Issue by Starystars67** [montlikadani/TabList#80]
**!** required

**If ! mark is not specified then not need to write.**

### Describe the bug (!)
The bungee console is spammed with the error shown in the screenshot, it also appears to show text behind the tab list and it also is not centring the text properly.

(!) Software (Bukkit/Spigot/Paper) name & version:
BungeeCord (downloaded 23/03/2019)
(!) Plugin version:
Latest (as of 24/02019)
Java version:
8
### Console error (!)
See screenshot below

### Config.yml (!)
Send the config.yml or other file.
You can send files link e.g. [pastebin.com](https://pastebin.com/) or paste a code block.
https://pastebin.com/hxkHiHJX

### Screenshots
Send a few pictures of the problem if you can.
![image](https://user-images.githubusercontent.com/15389482/56725254-6f0beb80-6744-11e9-8d85-e9e3cbc5f9bf.png)
![image](https://user-images.githubusercontent.com/15389482/56725808-78e21e80-6745-11e9-8270-9dad74a24345.png)

**Comment by montlikadani** [comment]
Will be fixed in the next version.
What does it mean that the text does not appear correctly behind the tablist?

**Comment by Starystars67** [comment]
Much appreciated, when is this likely to be?

If you open the second image (In-game image) and look closely at the "to" in Welcome to you will notice text behind it that is the same text as what i have in the tablist but for some reason it is showing behind the tablist.
Also do you have any idea as to why the bottom two lines are not centred correctly? They are put on new lines using the \n and there are no spaces as you can see in my config.

**Comment by montlikadani** [comment]
Isn't a hologram behind the tablist?
Just use `\n` it twice or more times.

**Comment by Starystars67** [comment]
Unfortunately not, it seems to be something with your plugin. I am currently running it on a Bungee setup and it worked when it was in a spigot server but after moving it to bungee it has fabricated these issues.

I will try the multiple new line characters but im not sure how that will help as it isn't another new line i need, but to centre the text.

**Comment by montlikadani** [comment]
The TabList.jar is exists on your Bukkit server?

**Comment by Starystars67** [comment]
No, i had previously run it there, I then moved (deleted from bukkit and
installed in bungee).

**Comment by montlikadani** [comment]
Are you using any other plugins on your Bungeecord server? (If you have many plugins, then take a screenshot)

**Comment by Starystars67** [comment]
Yes, only NuVotifier and MyCMDs.

**Comment by montlikadani** [comment]
It's strange because can't create one, whatever we want. This can only be a Minecraft flaw because it creates a tablist for the monitor where there may be texts behind such text that are the same. This cannot be fixed in the plugin. The reason I think may be that you wrote too long text in the header, so it was caused by this.

**Comment by Starystars67** [comment]
Fair enough thank you. When was that new update likely to be released if you don't mind me asking?

**Comment by montlikadani** [comment]
I do not know. As I'm ready for the 1.14 update. But this may take up to 1 month because I have other things to do.

**Comment by Starystars67** [comment]
okay then thanks, if i was to take the current source here from master would it be still be good to use on 1.12.2 and solve that console spam issue?

**Comment by montlikadani** [comment]
No, because it's an internal bug that only the developer can fix.

**Comment by Starystars67** [comment]
Okay

**Comment by montlikadani** [comment]
Try in the latest release.

**Comment by Starystars67** [comment]
Will do, I will close this as of now unless the issue persists. Otherwise Thank you.
