### ISSUE TITLE
Tablist not working

### ISSUE THREAD

**Issue by MajorLOLGaming** [montlikadani/TabList#81]
**!** required

**If ! mark is not specified then not need to write.**

### Describe the bug (!)
Understand what the problem is with the plugin.

(!) Software (Bukkit/Spigot/Paper) name & version: Spigot 1.12

(!) Plugin version: 4.3

Java version:

### Console error (!)
> 
> [INFO] [TabList] Enabling TabList v4.3
[INFO] [TabList] Disabling TabList v4.3
[WARN] java.lang.NullPointerException
[WARN]     at hu.montlikadani.tablist.TabList.onDisable(TabList.java:167)
[WARN]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[WARN]     at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[WARN]     at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421)
[WARN]     at hu.montlikadani.tablist.TabList.onEnable(TabList.java:84)
[WARN]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[WARN]     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[WARN]     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[WARN]     at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
[WARN]     at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
[WARN]     at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
[WARN]     at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[WARN]     at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[WARN]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[WARN]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[WARN]     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
[WARN]     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
[WARN]     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
[WARN]     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[WARN]     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[WARN]     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[WARN]     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[WARN]     at java.util.concurrent.FutureTask.run(Unknown Source)
[WARN]     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[WARN]     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[WARN]     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[WARN]     at java.lang.Thread.run(Unknown Source)
[WARN] [TabList] There was an error. Please report it here:
https://github.com/montlikadani/TabList/issues
>

### Config.yml (!)
Send the config.yml or other file.
You can send files link e.g. [pastebin.com](https://pastebin.com/) or paste a code block.
```
https://pastebin.com/LVis0FNW
```

### Screenshots
Send a few pictures of the problem if you can.
![2019-04-27_22 15 25](https://user-images.githubusercontent.com/32457983/56854633-07b78c80-693a-11e9-9071-2ab186647fb1.png)

**Comment by montlikadani** [comment]
The configuration is invalid.

**Comment by MajorLOLGaming** [comment]
oh okay. did you change the way the config is?

**Comment by montlikadani** [comment]
The default config is https://github.com/montlikadani/TabList/blob/master/config.yml

**Comment by MajorLOLGaming** [comment]
Okay, that fixed it. Thank you. good support ;)
