### ISSUE TITLE
Can't display player name normally

### ISSUE THREAD

**Issue by AndiSlash0723** [montlikadani/TabList#82]
Can't display player name normally, not sure what happened
The player name displayed as "%player_name%"

Like this :
https://imgur.com/a/KDztywl

**Comment by montlikadani** [comment]
PLEASE READ THE MAIN PAGE FOR MORE INFO!

Your problem is you not using the PlaceholderAPI and this not work, you need to use %player% instead of %player_name%

**Comment by AndiSlash0723** [comment]
Very sorry, my bad. It was a long time since my last time hosting a server...
But does PlaceholderAPI have 1.14 version?

**Comment by montlikadani** [comment]
Yea from Jenkins: http://ci.extendedclip.com/job/PlaceholderAPI/
