### ISSUE TITLE
Sort Priority Is not working properly.

### ISSUE THREAD

**Issue by ofek156737** [montlikadani/TabList#84]
**!** required

**If ! mark is not specified then not need to write.**

### Describe the bug (!)
It's kind of complicated.
when I try to sort the my groups using the "sort-priority:" thing, it changes the rank of everyone in the tablist to be the same. 
so for example, if I apply this code to every one of my ranks and type /tablist reload on the server, it changes everyone in the tablist to be [Member] or [Owner] or any other rank.
My goal is to just put the Owner first in the tablist in case he is online, and then co-owner, admin, mod etc..
I sorted them by using 1,2,3,4,5 and 5,4,3,2,1 just to check if thats the prob, and its not.
If I change the sort-priority code to "priority:", everyone is showing up with their rank on the tab correctly, but again, the sorting is not working because Co-Owner can show up after Member and I miss my goal. 
I hope it will get resolved soon. 
Examples:

This Groups config: https://pastebin.com/FeSjgQ3Y
Leads to everyone being the same rank (red arrow is actually co-owner) - 
![image](https://user-images.githubusercontent.com/50209428/57087293-6a2cd600-6d08-11e9-8aef-1b1677b1525f.png)

This Groups Config: https://pastebin.com/33x2Dsdt
Leads to everyone showing up with their correct rank - but not sorted. 
![image](https://user-images.githubusercontent.com/50209428/57087422-a9f3bd80-6d08-11e9-957a-70c512deef64.png)

This Groups Config: https://pastebin.com/G0BtKtCn
Leads to the first result - everyone is showing up with the same rank, even tho its not their real rank. (red arrow - actually not co-owner)
![image](https://user-images.githubusercontent.com/50209428/57087533-ee7f5900-6d08-11e9-9bb1-8819f32732b2.png)

(!) Software (Bukkit/Spigot/Paper) name & version: Spigot 1.13.2

(!) Plugin version: 4.3

Java version:

### Console error (!)
> 
> Send the console error if you have it.
>

### Config.yml (!)
Send the config.yml or other file.
You can send files link e.g. [pastebin.com](https://pastebin.com/) or paste a code block.
```
There u go - https://pastebin.com/kLAY7uCc
```

### Screenshots
Send a few pictures of the problem if you can.
They are up at the start where they belong :P

**Comment by montlikadani** [comment]
**Thanks for your report!**

I never tested this, if this works or not, because I could only solve one by one to sort the players on the tablist and on other players to sort him and me.
I don't know if it will be improve.
The added integer for sorting on the tablist is the `sort-priority` integer format. The top and bottom images are similar.

**Comment by ofek156737** [comment]
Hey, Thanks for the fast response.
Can you please clarify what are you saying by this? what do u mean by "I solved one by one to sort the players.."?

**Comment by montlikadani** [comment]
I'm tested alone the sort-priority option with two accounts.

**Comment by ofek156737** [comment]
That's exactly what I did..so...?

**Comment by montlikadani** [comment]
Uh, this buggy, because the twice account on same computer is not the correct. So this in twice Mc account is not work. If you try with other player on other computer, it will work.

**Comment by ofek156737** [comment]
I'll try to test it out with another person and I'll post the updates here, for the meantime, thx :P

**Comment by ofek156737** [comment]
Well, I tested it with a friend and it still doesn't work. Now Im on top while I should be at the bottom. 
![image](https://user-images.githubusercontent.com/50209428/57099186-80488f80-6d24-11e9-8df6-cdde2ea3bc9b.png)

**Comment by montlikadani** [comment]
Weird, anyway thanks for your contribution and the test.

**Comment by ofek156737** [comment]
So there won't be any solution to this dude?

**Comment by montlikadani** [comment]
Not now

**Comment by ofek156737** [comment]
Do you think it's a bug or something that I'm doing wrong?

**Comment by montlikadani** [comment]
It's a bug.

_Anyway, join my discord server to get the dev latest versions. Link found in the main page._

**Comment by montlikadani** [comment]
Should work in the latest version.
