### ISSUE TITLE
Bad-ping Placholder color not working

### ISSUE THREAD

**Issue by ILoveRedPandas** [montlikadani/TabList#85]
When a player has a bad-ping on the server server just spits out a error on the Tablist
![javaw_2019-06-04_16-18-32](https://user-images.githubusercontent.com/30881760/58888507-c8721d80-86e7-11e9-9b6d-387d8706b045.png)

**Comment by montlikadani** [comment]
Could you please send me a TabList config.yml file?

**Comment by ILoveRedPandas** [comment]
Coundt upload as yml but converted to txt for upload to github
[config (copy).txt](https://github.com/montlikadani/TabList/files/3252971/config.copy.txt)

**Comment by montlikadani** [comment]
You not using the correct basic specified path name. The correct is:
```
ping-placeholder-format:
  bad-ping: "&c"
```
To the bad-ping is not be able to specify the amount of ping, because if it is more than medium-ping, it will automatically switch to that color.

**Comment by ILoveRedPandas** [comment]
chagned the format still get the same error reloaded plugin and server and restarted

**Comment by montlikadani** [comment]
So wtf?? Send me the currently modified ping-placeholder-format section to pastebin.com site.

**Comment by ILoveRedPandas** [comment]
https://pastebin.com/vxQwsTed

**Comment by montlikadani** [comment]
What I'm posted to https://github.com/montlikadani/TabList/issues/85#issuecomment-498705651
use the `bad-ping: "&c"` and **NOT**
```
bad-ping:
  color: "&c"
```

**Comment by ILoveRedPandas** [comment]
sorry im fucking retadted
