### ISSUE TITLE
Name not fitting

### ISSUE THREAD

**Issue by iTwitchTV** [montlikadani/TabList#87]
**!** required

**If ! mark is not specified then not need to write.**

### Describe the bug (!)
Understand what the problem is with the plugin.
**Name & rank can be cut off in the tab**
(!) Software (Bukkit/Spigot/Paper) name & version:
**Spigot v4.4**
(!) Plugin version:
**v4.4**
### Console error (!)
```
None
```

### Config.yml (!)
Send the config.yml or other file.
You can send files link e.g. [pastebin.com](https://pastebin.com/) or paste a code block.
```
https://pastebin.com/uXWCb9dx
```

### Screenshots
Send a few pictures of the problem if you can.
In this screenshot the rank is cut off - http://prntscr.com/o2cvpx
In this screenshot the name is cut off - http://prntscr.com/o2cvxq

**Comment by montlikadani** [comment]
Wut? You not using any namer option in tablist configuration. So check the other namer plugin that handles.

**Comment by iTwitchTV** [comment]
Ok, I had AnimatedNames installed and deleted that, and now there is no prefix what so ever.

http://prntscr.com/o2kbca

**Comment by montlikadani** [comment]
If you used the AnimatedNames, then disable the tabname option in tablist configuration and check in AnimatedNames configuration the prefix/suffix for name cutting.

**Comment by iTwitchTV** [comment]
The tabname option was disabled I reinstalled AnimatedNames and now the placeholder doesn't work

http://prntscr.com/o2khls

**Comment by montlikadani** [comment]
Report it to AnimatedNames plugin owner. This is not my problem.

**Comment by iTwitchTV** [comment]
Well then why doesn't any prefix show up in the tab when I removed AnimatedNames

**Comment by montlikadani** [comment]
Because it does not set the tab name.
