### ISSUE TITLE
PerWorldPlugins and Tablist

### ISSUE THREAD

**Issue by Julianvb97** [montlikadani/TabList#9]
Got this error as well, maybe you can do something with it. I don't know if it is a PerWorldPlugins error or an Tablist error.

Error: https://pastebin.com/YNxc414d

**Comment by montlikadani** [comment]
@Julianvb97 
This is a duplicate, the same mistake. #8

**Comment by Julianvb97** [comment]
But why does the plugin stop working after this?

**Comment by montlikadani** [comment]
@Julianvb97 
Because the PerWorldPlugins plugin is set so that if you find an error in one plugin, it will disable it. **Try to overwrite the interval 1 in the TabList configuration.**

**Comment by Julianvb97** [comment]
Aha will do thanks for the information :)

**Comment by montlikadani** [comment]
@Julianvb97 
Please wait for my patience to refresh...

**Comment by montlikadani** [comment]
**This error has been resolved and an update has been completed.** https://www.spigotmc.org/resources/animated-tab-tablist.46229/update?update=217083
