### ISSUE TITLE
1.14.4 conflict with armorstands and mobs

### ISSUE THREAD

**Issue by 4Cris** [montlikadani/TabList#90]
mobs and armor stands are invisible with 1.14.4

**Comment by montlikadani** [comment]
not my plugin

**Comment by 4Cris** [comment]
If i disable your plugin i don't have this issue anymore...

**Comment by montlikadani** [comment]
But, man... This issue is not my plugin, because I'm not implemented ANY related to mob editing code. This issue is TAB not TabList.
