### ISSUE TITLE
Error while using /tablist reload

### ISSUE THREAD

**Issue by 1vomarek1** [montlikadani/TabList#91]
[20:22:03 INFO]: 1vomarek1 issued server command: /tablist
> [20:22:11 INFO]: 1vomarek1 issued server command: /tablist reload
> [20:22:11 WARN]: java.lang.NoSuchMethodError: org.bukkit.scheduler.BukkitTask.isCancelled()Z
> [20:22:11 WARN]: at hu.montlikadani.tablist.TabList.cancelGroupUpdate(TabList.java:895)
> [20:22:11 WARN]: at hu.montlikadani.tablist.Commands.onCommand(Commands.java:79)
> [20:22:11 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [20:22:11 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
> [20:22:11 WARN]: at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675)
> [20:22:11 WARN]: at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1393)
> [20:22:11 WARN]: at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1198)
> [20:22:11 WARN]: at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [20:22:11 WARN]: at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
> [20:22:11 WARN]: at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
> [20:22:11 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [20:22:11 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [20:22:11 WARN]: at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
> [20:22:11 WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:839)
> [20:22:11 WARN]: at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
> [20:22:11 WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
> [20:22:11 WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
> [20:22:11 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by montlikadani** [comment]
Will be fixed in the next release.

**Comment by 1vomarek1** [comment]
k <3

**Comment by montlikadani** [comment]
Do not close it, i will close it if I released the new version.

**Comment by 1vomarek1** [comment]
kk :)

**Comment by montlikadani** [comment]
**Update time...**
