### ISSUE TITLE
Minecraft 1.14.4 name Placeholder

### ISSUE THREAD

**Issue by xLegendofJohnx** [montlikadani/TabList#93]
### With a Minecraft server 1.14.4 ( Paper 197 ) the Placeholder name does not work there are no errors at the console or some where just doesn´t replace the placeholder. 

i have already tried to get any other name placeholder from all the plugins that are working with yours but nothing works:

- PlaceholderAPI is installed

### Details
Plugin version: v4.5
Software (Spigot/Bukkit etc.. `/version`) version: Paper 197

### Console error
none

Send the console error if you have it.
none

### Configuration file(s)
Send the configuration file(s).
[config.zip](https://github.com/montlikadani/TabList/files/3509196/config.zip)
` 
 header:
  - "%anim:tablist%"
  - "&7<75> %anim:welcome% %player_name%&c!&7 <74>\n&6Ping:&r %ping%&7ms"
  - "<lines>"
`
configuration file
config.yml

### Screenshots (optional)
![image](https://user-images.githubusercontent.com/54174404/63162333-90118880-c022-11e9-9b26-303cb44941f5.png)

![2019-08-16_12 54 41](https://user-images.githubusercontent.com/54174404/63163233-2a72cb80-c025-11e9-808a-ce958dcc244f.png)

**Comment by montlikadani** [comment]
Because you not installed the Player expansion with `/papi ecloud download Player` and reload.
