### ISSUE TITLE
Wrong prefix and sort priority

### ISSUE THREAD

**Issue by Nety01** [montlikadani/TabList#94]
Server version: PaperSpigot 1.13.x 1.13.2 Build 642, development
Plugin version: 4.5

Config.yml: https://pastebin.com/ynBHzcyV
Groups.yml: https://pastebin.com/ztAZZij1

Problem:
If I am connected with my account I see myself with prefix Majitel that's right, but I am at the bottom:
https://imgur.com/lHjQc1Q

If I connect at the same time with player account, I don't see Nety with prefix Majitel but with prefix Donator and it's on the top:
https://imgur.com/vXJ0ex5 

Correctly, me (Nety) should have prefix Majitel and be on the top of the tablist.

**Comment by montlikadani** [comment]
Because you not negated the Donator permission in Majitel group. Sort priority already removed if you rode it.

**Comment by NetyTV** [comment]
I did tablist.donator false in Majitel group, but it's still the same problem

**Comment by montlikadani** [comment]
And you reloaded the tablist and the permission system plugin?

**Comment by NetyTV** [comment]
Yes, I reloaded them both

**Comment by Nety01** [comment]
Fixed
