### ISSUE TITLE
Issues with latest update.

### ISSUE THREAD

**Issue by topthat177** [montlikadani/TabList#97]
Hi,

Plugin was working normally until I updated to the latest release this morning. Now having some issues. The player tags in game above heads are not working and I got this error from doing /tablist toggle. Think there is an issue with the groups too. I have set my prefix in the groups.yml for my player name as well as my rank/class the same. Should output Owner in blue and my name in red. However, its showing up in the tablist with my prefix as defined by my permissions plugin LuckPerms which is different to Tablist. My name in chat is also displaying as defined by LuckPerms but that should be the case as you said in the update notes that TabList doesn't affect the chat anymore.

https://pastebin.com/pfQ3nHDH

Running latest version of plugin and Paper Spigot 1.14.4.

Also cheeky feature request on here too. Would it be possible to have an option to use nicknames from essentials but use the Tablist groups as well? Like use the groups but when it fills the name, hook it from essentials? Because if I just use essentials, all the names a white unless you colour and add the appropriate prefix before the name for each player. To much effort. However if a player has a nickname on my server, their client name still displays in the tablist.

Cheers.

**Comment by montlikadani** [comment]
- Any screenshot about the problem?
- What Java version are you using?
- Suggestions in bug reports are not accepted, should be opened a new Issue.

**Comment by topthat177** [comment]
Hi,

Java version is 1.8.

I've attached a copy of my config and groups file as well as screenshots. topthat177's name should be set as he is defined in the Player Section. SublimeGaming as seen by the permissions plugin is in the group Adventurer and should have a grey name by getting the prfix '&7'.

Files and Screenshots here: https://mega.nz/#F!v6QRBATA!wgQpWCePf3XTB06liMbTiA

I'll re post my suggestion. 

Cheers.

**Comment by montlikadani** [comment]
Currently the name-tag-visibility are not work in the latest update if you rode the changes. And send me the console error.

**Comment by topthat177** [comment]
Console error from /tablist toggle - https://pastebin.com/pfQ3nHDH

**Comment by montlikadani** [comment]
The console error will be fixed in the next release.

**Comment by topthat177** [comment]
So this plugin will no longer change players name tags at all or its will be fixed in the next update?

**Comment by montlikadani** [comment]
Will be removed in the next release, due to this feature is not tablist related. Use NameTagEdit to edit the name tag.

**Comment by topthat177** [comment]
Ok will do. Thanks for your help :)

**Comment by montlikadani** [comment]
Do not close it, we need this to do not forgot to fix this issue. I will close it if I release a new version.
