### ISSUE TITLE
two tasks generated exceptions

### ISSUE THREAD

**Issue by NatTheChicken** [montlikadani/TabList#98]
Here are the two errors I am getting:

`[23:21:11] [Server thread/WARN]: [TabList] Task #43 for TabList v4.5 generated an exceptionjava.lang.NullPointerException: null at hu.montlikadani.tablist.TabList.getAnim(TabList.java:781) ~[?:?] at hu.montlikadani.tablist.TabList.sendTab(TabList.java:831) ~[?:?] at hu.montlikadani.tablist.TabList.access$1(TabList.java:791) ~[?:?] at hu.montlikadani.tablist.TabList$2.run(TabList.java:768) ~[?:?] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:77) ~[craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:833) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192][23:21:11] [Server thread/WARN]: [TabList] Task #57 for TabList v4.5 generated an exceptionjava.lang.NullPointerException: null at hu.montlikadani.tablist.TabList.getAnim(TabList.java:781) ~[?:?] at hu.montlikadani.tablist.TabList.sendTab(TabList.java:831) ~[?:?] at hu.montlikadani.tablist.TabList.access$1(TabList.java:791) ~[?:?] at hu.montlikadani.tablist.TabList$2.run(TabList.java:768) ~[?:?] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:77) ~[craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:833) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695) [craftbukkit-1.13.2-R0.1.jar:git-Bukkit-a46fdbc] at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]`

And my config file is:
https://pastebin.com/40zS93e8

I was working on making an animated thing and after i made it, i tested it and got these two errors so here is my animated config too:
https://pastebin.com/miHxQBCu

**Comment by montlikadani** [comment]
You missed the `:` after Line section. I think after edited a config use the YAML checker to check what you missed.
