### ISSUE TITLE
Use groups and essentials nicknames

### ISSUE THREAD

**Issue by topthat177** [montlikadani/TabList#99]
Would it be possible to have an option to use nicknames from essentials but use the Tablist groups function as well to determine their prefixes etc? Like use the groups but when it fills the name, hook it from essentials. Because if I just use the essentials nickname option in config, all the names a white unless you colour and add the appropriate prefix before the name for each player. To much effort. However if a player has a nickname on my server, their client name still displays in the tablist.

If this would be possible that would be great.

Cheers.

**Comment by montlikadani** [comment]
Not possible, because groups and nickname are different and overwrites. Otherwise, set the nick name in the essentials to get it on the tablist.
